### ISSUE TITLE
Design the Landing Page for UC Next

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#110]
[UCNext mockup 7.16.pdf](https://github.com/universityofcalifornia/NeXt/files/752/UCNext.mockup.7.16.pdf)

**Comment by rrocchio** [comment]
![home page design](https://cloud.githubusercontent.com/assets/718820/8749610/8d9a2ade-2c57-11e5-9b49-93d6c175d778.png)

**Comment by rrocchio** [comment]
[UCNext mockup 7.23 logos.pdf](https://github.com/universityofcalifornia/NeXt/files/883/UCNext.mockup.7.23.logos.pdf)

**Comment by rrocchio** [comment]
[UCNext mockup 7.23 photos.pdf](https://github.com/universityofcalifornia/NeXt/files/884/UCNext.mockup.7.23.photos.pdf)

**Comment by rrocchio** [comment]
![screen shot 2015-07-24 at 9 06 44 am](https://cloud.githubusercontent.com/assets/718820/8879006/68bddbe8-31e3-11e5-806b-9f285edd945a.png)

**Comment by rrocchio** [comment]
Meeting Comments for Lauren - EVERYone likes it! - A few tweaks:
1)  Switch UCLA with UC Santa Cruz
2)  Make the surf board just a little bit bigger
3)  Add some skinny lines around the logos - to make them look like stickers
4) Add some text above the surf board that says:  "Catch the Wave"
5) Change "Legal" to "Privacy"
6) Rose will work on getting images of UCCSC - from years past... either UCSF - or ones previously hosted at UCLA

**Comment by ctmcintyre** [comment]
Oh PLEASE!  ;-)

I really don't care about #1.  No need to change it!

> RoseRocchio <mailto:notifications@github.com>
> July 24, 2015 at 9:16 AM
>
> Meeting Comments for Lauren - EVERYone likes it! - A few tweaks:
> 1) Switch UCLA with UC Santa Cruz
> 2) Make the surf board just a little bit bigger
> 3) Add some skinny lines around the logos - to make them look like
> stickers
> 4) Add some text above the surf board that says: "Catch the Wave"
> 5) Change "Legal" to "Privacy"
> 6) Rose will work on getting images of UCCSC - from years past...
> either UCSF - or ones previously hosted at UCLA
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/110#issuecomment-124570663>.
>
> RoseRocchio <mailto:notifications@github.com>
> July 17, 2015 at 7:41 AM
>
> UCNext mockup 7.16.pdf
> <https://github.com/universityofcalifornia/NeXt/files/752/UCNext.mockup.7.16.pdf>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/110>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
![ucnext 7 24](https://cloud.githubusercontent.com/assets/13141571/8886350/85993566-321d-11e5-97da-5f5b891dc8e6.jpg)
Here is a new proof. Please let me know any revisions.

**Comment by laurencullen** [comment]
I just made font changes (removing Proxima Nova because it is available with Typekit but not on Google Fonts). Here is a new version:
![ucnext 7 24](https://cloud.githubusercontent.com/assets/13141571/8886499/26b21588-3220-11e5-993b-0abd06a55219.jpg)

**Comment by laurencullen** [comment]
@rrocchio, please let me know if I need to submit the design to Chris and Lloyd for accessibility check before posting the header and footer images in here. Thanks!

**Comment by laurencullen** [comment]
Posting the new version - worked on accessibility with colors and links as well as added updated wave graphic. Please let me know any feedback. Thanks!
[UCNext mockup 7.30.pdf](https://github.com/universityofcalifornia/NeXt/files/1055/UCNext.mockup.7.30.pdf)

**Comment by laurencullen** [comment]
Here are the pngs of all assets at 300 dpi as we discussed on the call:
![about](https://cloud.githubusercontent.com/assets/13141571/9016508/9444c99a-3786-11e5-9c38-8bde4fb8610f.png)
![engagementmeter](https://cloud.githubusercontent.com/assets/13141571/9016509/94480240-3786-11e5-8172-76a238aeebb9.png)
![events](https://cloud.githubusercontent.com/assets/13141571/9016510/944c67f4-3786-11e5-859d-9582ea5ddd70.png)
![facebook](https://cloud.githubusercontent.com/assets/13141571/9016511/944e81e2-3786-11e5-8770-d41aee2e4bfe.png)
![groups](https://cloud.githubusercontent.com/assets/13141571/9016512/9452aa06-3786-11e5-8a0b-54bfdf7ad2e7.png)
![ideas](https://cloud.githubusercontent.com/assets/13141571/9016513/9454af18-3786-11e5-9b0d-5ba9d047c6d9.png)
![ideaslg](https://cloud.githubusercontent.com/assets/13141571/9016514/945d26ac-3786-11e5-9907-aaafd246f29f.png)
![login](https://cloud.githubusercontent.com/assets/13141571/9016515/9461fd9e-3786-11e5-91ed-4e0189d139d4.png)
![people](https://cloud.githubusercontent.com/assets/13141571/9016516/9466cd92-3786-11e5-8b25-6f38eb796f79.png)
![projects](https://cloud.githubusercontent.com/assets/13141571/9016517/9468c57a-3786-11e5-8353-112680888079.png)
![projectslg](https://cloud.githubusercontent.com/assets/13141571/9016518/946c918c-3786-11e5-815a-75bf1b81ccf6.png)
![search](https://cloud.githubusercontent.com/assets/13141571/9016519/9470acb8-3786-11e5-8a79-1c44589de3aa.png)
![social](https://cloud.githubusercontent.com/assets/13141571/9016520/94752d92-3786-11e5-850e-07dc14d19ef8.png)
![surfboardwave](https://cloud.githubusercontent.com/assets/13141571/9016521/947aadf8-3786-11e5-8ada-522055fe2ab8.png)
![twitter](https://cloud.githubusercontent.com/assets/13141571/9016522/947f5ad8-3786-11e5-86f0-abd43b650fd5.png)
![ucseal](https://cloud.githubusercontent.com/assets/13141571/9016523/94830818-3786-11e5-80ad-d122dcffce9f.png)

Please let me know if you need anything else. Thanks!

**Comment by laurencullen** [comment]
Also, the white assets with transparent background are previewing above as blank spaces, but the files are attached here. This includes Facebook, Twitter, UC seal, and projects.

**Comment by laurencullen** [comment]
Here are the pngs for the badges:

![silver](https://cloud.githubusercontent.com/assets/13141571/9016815/d6c22838-3788-11e5-9652-a5a0af43ec0d.png)
![golden](https://cloud.githubusercontent.com/assets/13141571/9016816/d6c86144-3788-11e5-8f33-cd2ac6b13636.png)

**Comment by laurencullen** [comment]
@rrocchio here is the jpg of the most recent proof posted above as a pdf before logged in and logged out versions. This proof includes work with color/link accessibility. Please let me know any feedback.
![ucnext mockup 7 30](https://cloud.githubusercontent.com/assets/13141571/9072674/76203390-3ab1-11e5-929b-1ee099e67881.jpg)

**Comment by laurencullen** [comment]
Here is a png of the UC Next logo. Hoping to obtain a larger version soon.
![ucnextlogo](https://cloud.githubusercontent.com/assets/13141571/9072724/b26be696-3ab1-11e5-8273-4091e209d65c.png)

**Comment by laurencullen** [comment]
Here is a new engagement meter graphic because the yellow was just too light before. Thanks!
![new-engagement-meter](https://cloud.githubusercontent.com/assets/13141571/9100563/48b52b1e-3b91-11e5-81ca-7dcabaa51837.png)

**Comment by ctmcintyre** [comment]
We need to figure out a lean way to make sure we include all locations in the engagement meter (campuses, med centers, labs, anr, ucop, etc)

**Comment by krozett** [comment]
The above commit will show all organizations on the full engagement meter page, but not the home page, ideas, or projects pages. We can easily change these though.

**Comment by laurencullen** [comment]
@krozett please replace wave image with this new version - attached 2 different sizes for you. Also, I touched up one piece of the wave and replaced a couple of logos, so this will replace the wave on all pages. Thanks!!

![newwavelg](https://cloud.githubusercontent.com/assets/13141571/10108745/9390e9f8-6377-11e5-9829-5a2f3bd24705.png)
![newwavesm](https://cloud.githubusercontent.com/assets/13141571/10108755/b59b1dca-6377-11e5-8b03-2def5b4f3bc0.png)
