### ISSUE TITLE
Add deletes across the system on all the items

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#111]
We need to be able to delete the test data across the system

**Comment by rrocchio** [comment]
@krozett  - is there a way to delete a user - for a super admin user?

**Comment by krozett** [comment]
@rose we don't have a way to delete users yet. I can add that, though. I believe local and shibbed users are treated the same, the only difference is a few fields and how they are created. Do I have that right, @ebollens ?

**Comment by ctrance** [comment]
I can now delete ideas, projects, events, people, and groups. Closing this...
