### ISSUE TITLE
Define THE ENGAGEMENT METER F(X)

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#112]
3)  INTRODUCTION of GAMIFIED Collaboration

The Collaboration Engagement METER formula

     a)  Setting up a Profile = 2 points for you and your campus
     b)  Inputting a New Idea = 5 points for you and your campus
     c)  Inputting a New Project = 5 points for you and your campus
     d)  Liking a project or an idea = 1 point each for you and your campus
     e) Volunteer to participate on a project  = 7 points for you and your campus
     e)  Winning a GOLD Sautter Award for your campus = 50 points for you and your campus
     f)  Winning a SILVER Sautter Award for your campus = 25 points for you and your campus

**Comment by ctmcintyre** [comment]
Good stuff and a great start!

The Sautter awards should be more points, perhaps 150 for gold and 100 for silver.  They shouldn't be the same as saying you want to volunteer on two projects.  ;-)

**Comment by rrocchio** [comment]
@ctmcintyre  - how about 25 and 50 ?  One thing is if the Sautter awards give too much of a lead the other campuses won't have any chance of catching up....

**Comment by ctmcintyre** [comment]
It depends on how prestigious we want the Sautter award to rank.  To me,
it's more than 4 people stating they'll volunteer for a project... 

> RoseRocchio <mailto:notifications@github.com>
> July 24, 2015 at 2:25 PM
>
> @ctmcintyre <https://github.com/ctmcintyre> - how about 25 and 50 ?
> One thing is if the Sautter awards give too much of a lead the other
> campuses won't have any chance of catching up....
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/112#issuecomment-124729619>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by joshuaselsky** [comment]
Closing because this has been implemented.
