### ISSUE TITLE
Create the Final version of the Design for the Header/Mast Head

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#113]
Create the Final version of the Design for the Header/Mast Head - Add the images needed to put into the Header Design into this ticket.

**Comment by laurencullen** [comment]
All images are listed in landing page design. Here are the ones just for header and nav:
![ucnextlogo](https://cloud.githubusercontent.com/assets/13141571/9072831/5f7ec5e2-3ab2-11e5-8947-d9caebdb8b0c.png)
![login](https://cloud.githubusercontent.com/assets/13141571/9072842/6aadcb52-3ab2-11e5-9e6c-569cc6620737.png)
![search](https://cloud.githubusercontent.com/assets/13141571/9072845/71de3c86-3ab2-11e5-9029-3298e2d40086.png)
![events](https://cloud.githubusercontent.com/assets/13141571/9072859/8e25b644-3ab2-11e5-8309-ad6093bd0c48.png)
![groups](https://cloud.githubusercontent.com/assets/13141571/9072857/8e238d88-3ab2-11e5-887e-071469bc614c.png)
![ideas](https://cloud.githubusercontent.com/assets/13141571/9072860/8e275332-3ab2-11e5-998d-eb62d05fd0f2.png)
![people](https://cloud.githubusercontent.com/assets/13141571/9072861/8e2729ac-3ab2-11e5-822f-8f3c9a01cc92.png)
![projects](https://cloud.githubusercontent.com/assets/13141571/9072862/8e2b06e4-3ab2-11e5-8656-737bcf855a59.png)
![about](https://cloud.githubusercontent.com/assets/13141571/9072858/8e23d298-3ab2-11e5-9a22-2be2d65563c2.png)

**Comment by laurencullen** [comment]
@krozett here is the magnifying glass without the blue background. It is attached but doesn't show because it is white on transparent. Please let me know if you need anything else.

![magnify](https://cloud.githubusercontent.com/assets/13141571/9229817/de2e567e-40d3-11e5-9e75-89467afe577f.png)

**Comment by krozett** [comment]
Thanks!

**Comment by laurencullen** [comment]
I recreated the original design crowd logo in Illustrator because it is showing blurry. Here is the new, larger file. Please let me know if you need anything else or another size because I can send. Thanks!

![uc next logo-02](https://cloud.githubusercontent.com/assets/13141571/9552207/2f8b4ae2-4d6b-11e5-8549-55344d97cb86.png)

**Comment by krozett** [comment]
@laurencullen could you please reduce the space above and below the image?

**Comment by laurencullen** [comment]
@krozett attached png file should have no background space. Please let me know if you need anything else. Thanks!
![logo-new-size](https://cloud.githubusercontent.com/assets/13141571/9584005/6b228a70-4fc3-11e5-9d49-524602fe563d.png)
