### ISSUE TITLE
Create the final version of the Footer for UC Next

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#115]
Create the final version of the Footer for UC Next - Add all of the components needed to create this

**Comment by laurencullen** [comment]
All images were listed in landing page thread. Attached are the images just for the footer (incl the surfboard/wave):
![surfboardwave](https://cloud.githubusercontent.com/assets/13141571/9072909/cd51d56e-3ab2-11e5-9b36-4e41ae51312c.png)
![ucseal](https://cloud.githubusercontent.com/assets/13141571/9072912/d132eb00-3ab2-11e5-97c5-0ad2656e7894.png)
![facebook](https://cloud.githubusercontent.com/assets/13141571/9072916/d72da3ba-3ab2-11e5-802c-03e6a528dd46.png)
![twitter](https://cloud.githubusercontent.com/assets/13141571/9072921/db2e03ec-3ab2-11e5-9ed6-508aee14e6d2.png)
