### ISSUE TITLE
Finalize the selection of fonts for the Typography for the site

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#116]
Select a set of fonts for the Typography

Go with a casual or Modern feel - but warm - not corporate....

Give guidance for H1, H2, H3 and regular font

**Comment by laurencullen** [comment]
Here are ideas, please let me know any feedback on this and if you need more details (sizing, etc.):

h1: Source Sans Pro Semibold
h2: Open Sans Semibold
h3: Open Sans Condensed Bold
p: Open Sans

**Comment by laurencullen** [comment]
Here are some samples from the proofs of these fonts:

[UC Next Fonts.pdf](https://github.com/universityofcalifornia/NeXt/files/1085/UC.Next.Fonts.pdf)

Please let me know any feedback or revisions. Thanks!

**Comment by laurencullen** [comment]
Here are the fonts in jpg format so that you can see it here:
![uc next fonts](https://cloud.githubusercontent.com/assets/13141571/9073026/9041016c-3ab3-11e5-9fc9-6f86dcf960f3.jpg)

**Comment by krozett** [comment]
@laurencullen could we get the font sizes as well as line heights for these? In pixels for all would be easiest, but I can also do in percentages if you tell me what the pixel size for the base font is.

**Comment by laurencullen** [comment]
Here are the details. I think that this will make more sense than the way I assigned it before. Sorry about it not being clear before and please let me know if you need anything else/ have any questions.

![uc next fonts-03](https://cloud.githubusercontent.com/assets/13141571/9146323/ac81bde4-3d10-11e5-9468-620c8927b07f.jpg)

**Comment by laurencullen** [comment]
Here are the details. I think that this will make more sense than the way I assigned it before. Sorry about it not being clear before and please let me know if you need anything else/ have any questions.

![uc next fonts-03](https://cloud.githubusercontent.com/assets/13141571/9146408/5e209250-3d11-11e5-8317-58c30ba853ac.jpg)
