### ISSUE TITLE
Create a "Remove Vote" option on Ideas and Projects

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#118]
Create a "Remove Vote" option on Ideas and Projects 

* Only works on your own vote  - but an Admin should also be able to remove votes...

**Comment by joshuaselsky** [comment]
For projects, this will be a new button that is displayed on the project details page when a user is logged in and has previously selected Good Project. 

For ideas, this will be a new button that is displayed on the idea details page when a user is logged in and has previously selected Good Project.

**Comment by joshuaselsky** [comment]
This has already been implemented for Ideas. For Projects, we will add Withdraw Support and Withdraw Participation buttons exactly how it is done for Ideas.

**Comment by joshuaselsky** [comment]
On the main Projects page, this functionality should also be added to the +1 lightbox. 

The "remove vote" functionality is also missing from the main Ideas page +1 lightbox, so it be added there as well.

**Comment by ctrance** [comment]
Fixed on Ideas page but I can't test Projects for now since the page throws error when launching.

**Comment by ctrance** [comment]
Fixed on Projects too.
