### ISSUE TITLE
Design a standard look for forms - start with the Profile screen

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#119]
Design a standard look for forms - start with the Profile screen 

In other words - you don't have to design up the whole form, just layout an attractive way of presenting a form - such as the Profile form, and then Keith can lay that in.... - consider things like spacing, indentation, fonts, and the styles of some of the various fields:

1) Open text boxes
2) Drop down list selections
3) Radio buttons ( if there are any )

**Comment by rrocchio** [comment]
@laurencullen  - keep in mind that the site has to be RESPONSIVE  - so the forms have to have a way of collapsing attractively!

**Comment by laurencullen** [comment]
Here is a rough draft of the edit profile page (I'll post the profile page soon). How does the upload profile picture functionality work? For the bio, will all of the options be available that are on the current site for styling? Please let me know any feedback and revisions.
Thanks!
[UCNext edit profile.pdf](https://github.com/universityofcalifornia/NeXt/files/952/UCNext.edit.profile.pdf)

**Comment by ctmcintyre** [comment]
I would like to see the badges on the upper right

> laurencullen <mailto:notifications@github.com>
> July 28, 2015 at 3:32 PM
>
> Here is a rough draft of the edit profile page (I'll post the profile
> page soon). How does the upload profile picture functionality work?
> For the bio, will all of the options be available that are on the
> current site for styling? Please let me know any feedback and revisions.
> Thanks!
> UCNext edit profile.pdf
> <https://github.com/universityofcalifornia/NeXt/files/952/UCNext.edit.profile.pdf>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/119#issuecomment-125771488>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Proof with badges on upper right:
[UCNext edit profile.pdf](https://github.com/universityofcalifornia/NeXt/files/954/UCNext.edit.profile.pdf)

**Comment by ctmcintyre** [comment]
Looks good. 

> laurencullen <mailto:notifications@github.com>
> July 28, 2015 at 4:29 PM
>
> Proof with badges on upper right:
> UCNext edit profile.pdf
> <https://github.com/universityofcalifornia/NeXt/files/954/UCNext.edit.profile.pdf>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/119#issuecomment-125781158>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Here is a rough draft of the profile page. Please let me know any changes. 

Also, I'm not able to login or see profiles today... maybe there are updates being done on the site? If I left any info off of the profile page, please let me know because I'm going by memory.

Thanks!
[UCNext profile.pdf](https://github.com/universityofcalifornia/NeXt/files/983/UCNext.profile.pdf)

**Comment by krozett** [comment]
For the badges, I actually implemented a feature that allows users to "showcase" a limited number of badges on their profile. There is only enough space to show 4 or 5 on their profile page, and there is a separate page to see all of a user's badges.

It would be useful to have checkboxes (or another kind of toggle control) for the badges on the Edit Profile page only, which will control whether the badges are showcased or not.

**Comment by laurencullen** [comment]
Attached is a revised version. Please let me know any changes.
Thanks!
[UCNext profile new.pdf](https://github.com/universityofcalifornia/NeXt/files/1010/UCNext.profile.new.pdf)

**Comment by laurencullen** [comment]
Here are new versions of the edit profile page and profile page including the changes to the badges. Please let me know any revisions. Thanks!
[UCNext edit profile new.pdf](https://github.com/universityofcalifornia/NeXt/files/1013/UCNext.edit.profile.new.pdf)
[UCNext profile new.pdf](https://github.com/universityofcalifornia/NeXt/files/1014/UCNext.profile.new.pdf)

**Comment by laurencullen** [comment]
Attached are new edit profile and profile pages. I worked on some feedback as well as on accessible colors and links. Edit profile 1 has the bio as one column whereas edit profile 2 has the bio as two columns. Please let me know any revisions. Thanks!
[UCNext profile.pdf](https://github.com/universityofcalifornia/NeXt/files/1052/UCNext.profile.pdf)
[UCNext edit profile 2.pdf](https://github.com/universityofcalifornia/NeXt/files/1053/UCNext.edit.profile.2.pdf)
[UCNext edit profile 1.pdf](https://github.com/universityofcalifornia/NeXt/files/1054/UCNext.edit.profile.1.pdf)

**Comment by laurencullen** [comment]
Attached are new edit profile and profile pages. I worked on some feedback as well as on accessible colors and links. Edit profile 1 has the bio as one column whereas edit profile 2 has the bio as two columns. Please let me know any revisions. Thanks!
[UCNext profile.pdf](https://github.com/universityofcalifornia/NeXt/files/1058/UCNext.profile.pdf)
[UCNext edit profile 1.pdf](https://github.com/universityofcalifornia/NeXt/files/1059/UCNext.edit.profile.1.pdf)
[UCNext edit profile 2.pdf](https://github.com/universityofcalifornia/NeXt/files/1060/UCNext.edit.profile.2.pdf)

**Comment by laurencullen** [comment]
Please see attached proofs. Revises for accessibility. Please let me know if you have any changes.
![ucnext form-01](https://cloud.githubusercontent.com/assets/13141571/9073726/51fc4632-3ab8-11e5-9f54-d411aa9e90d1.jpg)
![ucnext form-02](https://cloud.githubusercontent.com/assets/13141571/9073728/51fe1f3e-3ab8-11e5-8ef2-ad1c325dee35.jpg)
![ucnext form-03](https://cloud.githubusercontent.com/assets/13141571/9073727/51fd1ada-3ab8-11e5-9e40-41afbbb18616.jpg)

**Comment by krozett** [comment]
The forms should be very easy. I changed the panel and form CSS so you can just take groups of the input-group divs and put them in panels. Everything should just work.

One thing I did not get to was the dropdowns. Those will require extra work to style, because browsers don't really let you control the look. You have to do a "fake" dropdown, which I have to look into.

**Comment by laurencullen** [comment]
Not looking to create more work right now... for drop downs, I think default ones should work. We can always add style here later.

**Comment by laurencullen** [comment]
@krozett Not looking to create more work right now... for drop downs, I think default ones should work. We can always add style here later.

**Comment by ebollens** [comment]
> Not looking to create more work right now

Agree, so I'm not going to make setting badge visibility through the edit page (it's got its own page right now).

**Comment by ctmcintyre** [comment]
Competencies aren't showing up when looking at people's profiles.  EEEK!
