### ISSUE TITLE
Design a look for the panels or body of the site....

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#120]
@ebollens  -not sure what Lauren is defining here - if the background of the site is white...  Can you add some guidance?  Thanks!

**Comment by laurencullen** [comment]
Yes, I think the background of the site would be good is white. Then the box around certain areas be very light blue (#e0ebf4) with blue border (#0054a6) as seen in the proof.

Please let me know any feedback and if you are looking for something else here.

Example of page with blue panels:
[UCNext edit profile 1.pdf](https://github.com/universityofcalifornia/NeXt/files/1084/UCNext.edit.profile.1.pdf)

**Comment by krozett** [comment]
Devs: These are just plain old Bootstrap panels, as we've already been doing throughout the site.
http://getbootstrap.com/components/#panels

Just make sure you use `panel-default` and not `panel-info` or any other variants. We only use the default colors.
