### ISSUE TITLE
Create a Groups Module Interface for Users

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#121]
Users can do the following:

1) See a list of existing Groups
2) Search the list of existing Groups (should we use elastic search - @ebollens ?)
3) Click on a Group and see a "Group Detail view"
4) The Group Detail view should have these elements:

     a) Group Name
     b) Group Founder
     c) Group Purpose
     d) Group email list
     e) Group collaboration website
     f) Group Profile this should be an aggregate of members by location

I think that this is a way of telling how active a group is in the aggregate - so adding a field for the 11 campuses and one for UCOP should work:

So I am thinking a numeric field, where we do a +1 for the campus where the user's email domain is from a specific campus...

1) UCLA
2) UC Berkeley
3) UC San Diego
4) UCSC
5) UCSB
6) UCI
7) UC Riverside
8) UCSF
9) UC Hastings
10) UC Merced
11) UC Davis
12) UCOP
13) UC ANR

**Comment by krozett** [comment]
@rrocchio It looks like most of this functionality is in the system now, everything but website and aggregate of members by location. Do we still want these?

**Comment by joshuaselsky** [comment]
Closing because Group Details feature is in place. We can open an issue in the future for enhancements.
