### ISSUE TITLE
Implement the Engagement Meter

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#123]
To do this,

The first step is to add a field to the Person table - called Engagement_Points (- I think it should probably be Numeric...)

Then the second step is to to add a table for the Org Aggregate Engagement Meter:

Org_id (numeric)
Org_Name (varchar (40))
Total_Engagement_Points ( Numeric)
Update_date - datetime
Updated_by - varchar(30)

The third step is to add the inserts of points to all of the items that get people points:
--------------------------------------------------

1) Setting up a Profile ADD 2 points; DELETE a profile SUBTRACT 2 points
2) Create a project ADD 5 points ; DELETE a project SUBTRACT 5 points
4) Like a project ADD 1 point
5) Comment on a project - ADD 2 points
3) Create an Idea ADD 3 points; DELETE an Idea SUBTRACT 3 points
4) Like an Idea ADD 1 point
5) Comment on an idea - ADD 2 points
6) Create a Group ADD 3 points  ( DELETE a group - can only be done - if you are the only person in the group)
7) Join a Group ADD 1 point; LEAVE a group SUBTRACT 1 point
8) Awarding a GOLD Sautter Award for your campus = 50 points for you and your campus
 9) Awarding a SILVER Sautter Award for your campus = 25 points for you and your campus
10) Removing an award subtracts those points

**Comment by krozett** [comment]
We don't have the "comment on a project" feature but I'll add this once we do.
I'm not sure what "setting up a profile" entails, @rrocchio could you clarify?

**Comment by ctrance** [comment]
@krozett - I notice that there are 2 engagement meters (1-ideas and 2-projects). If I do actions that are not related to idea/project, like set up profile, group management, and awarding will those actions be added onto both engagement meters? Or is there an Org Aggregate Engagement Meter page, which I don't see in the app.

**Comment by krozett** [comment]
@ctrance The meter on the main page and the "engagement meter" page count up all the points, which covers things like setting up a profile. That's the aggregate meter you refer to.

**Comment by ctrance** [comment]
@krozett - Is there a test site where I can play around with the meter? I don't want to touch the prod version. Basically I want to test if doing the actions above reflects the points earned/deducted on the meter.

**Comment by ctrance** [comment]
I don't see this implemented yet "The first step is to add a field to the Person table - called Engagement_Points (- I think it should probably be Numeric...)"

**Comment by krozett** [comment]
@ctrance unfortunately we don't have a test site yet. However, if you want, you can test out reversible actions. For example, join a group, and then leave one.

**Comment by ctrance** [comment]
@krozett - Thanks, that's what I have in mind! To check the engagement meter values increasing/decreasing I need to see the total engagement points on the UI (maybe on hover over?)

**Comment by krozett** [comment]
@ctrance that's actually a good idea to have hover show the points. For now, if you look at the HTML source of the page and search for elements that look like `<span class="sr-only">` you can see the point numbers there. I'll add the points in the hover text as well, but I don't know when that'll be deployed.

**Comment by ctrance** [comment]
Will test this once login is fixed on test site

**Comment by ctrance** [comment]
@krozett - How do I comment on a project? I don't see a comment button or field
![capture](https://cloud.githubusercontent.com/assets/1034174/11247048/4ddc2210-8dcf-11e5-84b8-0cd8550e3814.PNG)

**Comment by ctrance** [comment]
@krozett - I joined group "Golden Sautter Award Winners - 2004" then the app added "26 points" on the engagement meter. Then I checked my profile and it also added the "2004 Golden Sautter Award Winner" badge.

**Comment by ctrance** [comment]
@krozett - App only adds 25 points for "8) Awarding a GOLD Sautter Award for your campus = 50 points for you and your campus"

**Comment by ctrance** [comment]
@krozett - App only adds 10 pts for "9) Awarding a SILVER Sautter Award for your campus = 25 points for you and your campus"

**Comment by ctrance** [comment]
@krozett - It would be nice to see who joined the group " Create a Group ADD 3 points ( DELETE a group - can only be done - if you are the only person in the group)". I can test delete groups that I created for now, since there's no way to see who the group members are in the Group page.

**Comment by ctrance** [comment]
Other actions are adding/subtracting correctly. I'll close this and create individual tickets for issues mentioned above.

**Comment by ctrance** [comment]
Since I can now see the group members, deleting a group reduce points on Engagement Meter.
