### ISSUE TITLE
Fix CSS

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#125]
There are some CSS and formatting issues.  
Example 1: Groups header has no style
Example 2: When selecting "Good Project", the following text shows up raw: "Your support of <strong>NeXt Ideation Platform</strong> is appreciated!"

**Comment by pmeads** [comment]
The "raw" message has to do with rails flash not working properly. this was reported in issue #80

**Comment by pmeads** [comment]
This was addressed during the initial beta rollout. closing
