### ISSUE TITLE
Create these new badges for UC Next

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#130]
Lets create these new badges for UC Next:

a.	UCCSC 2015 Attendee - use the UCCSC 2015 logo - https://uccsc.ucr.edu/ 
b.	UCCSC 2015 Presenter
c.	UC Next – First 100 Idea Generator
d.	UC Next - First 100 Project Collaborator
e.	UC Next Corp – Anyone who creates a project or volunteers to participate on a project
f.      UC Next Developer

**Comment by laurencullen** [comment]
Here are the rough drafts of these badges. There are two versions of UCCSC - one with the logo in the official logo color and one where the logo color is changed to white so that we can change the background color and still be accessible. Please let me know any changes.
![uccsc attendee 1](https://cloud.githubusercontent.com/assets/13141571/9075662/5449bc80-3acc-11e5-8d60-74bc17ee97d5.jpg)
![uccsc attendee 2](https://cloud.githubusercontent.com/assets/13141571/9075663/544ab518-3acc-11e5-82e2-cc03b2970d84.jpg)
![uccsc presenter 1](https://cloud.githubusercontent.com/assets/13141571/9075664/544b6c38-3acc-11e5-8769-9ebe5f07dc69.jpg)
![uccsc presenter 2](https://cloud.githubusercontent.com/assets/13141571/9075665/544c58e6-3acc-11e5-8b4a-7bf0848c8116.jpg)
![corp](https://cloud.githubusercontent.com/assets/13141571/9075667/5e2b3328-3acc-11e5-8c5f-c241d8ae19b9.jpg)
![developer](https://cloud.githubusercontent.com/assets/13141571/9075668/5e3d33c0-3acc-11e5-843f-ed102312b2c4.jpg)
![idea generator](https://cloud.githubusercontent.com/assets/13141571/9075669/5e41da56-3acc-11e5-9053-42f65055fd81.jpg)
![project collaborator](https://cloud.githubusercontent.com/assets/13141571/9075670/5e453c32-3acc-11e5-89b5-27d4d65bd625.jpg)

**Comment by ctmcintyre** [comment]
How about "UC Next - Dev Corps"

> laurencullen <mailto:notifications@github.com>
> August 4, 2015 at 5:15 PM
>
> Here are the rough drafts of these badges. There are two versions of
> UCCSC - one with the logo in the official logo color and one where the
> logo color is changed to white so that we can change the background
> color and still be accessible. Please let me know any changes.
> uccsc attendee 1
> <https://cloud.githubusercontent.com/assets/13141571/9075662/5449bc80-3acc-11e5-8d60-74bc17ee97d5.jpg>
> uccsc attendee 2
> <https://cloud.githubusercontent.com/assets/13141571/9075663/544ab518-3acc-11e5-82e2-cc03b2970d84.jpg>
> uccsc presenter 1
> <https://cloud.githubusercontent.com/assets/13141571/9075664/544b6c38-3acc-11e5-8769-9ebe5f07dc69.jpg>
> uccsc presenter 2
> <https://cloud.githubusercontent.com/assets/13141571/9075665/544c58e6-3acc-11e5-8b4a-7bf0848c8116.jpg>
> corp
> <https://cloud.githubusercontent.com/assets/13141571/9075667/5e2b3328-3acc-11e5-8c5f-c241d8ae19b9.jpg>
> developer
> <https://cloud.githubusercontent.com/assets/13141571/9075668/5e3d33c0-3acc-11e5-843f-ed102312b2c4.jpg>
> idea generator
> <https://cloud.githubusercontent.com/assets/13141571/9075669/5e41da56-3acc-11e5-9053-42f65055fd81.jpg>
> project collaborator
> <https://cloud.githubusercontent.com/assets/13141571/9075670/5e453c32-3acc-11e5-89b5-27d4d65bd625.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130#issuecomment-127801622>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre would Dev Corps be an edit to an existing badge or a new one? If a new badge, please let me know the description of what it would be awarding (this way I have context for the design). Thanks!

**Comment by ctmcintyre** [comment]
"Dev Corps" replaces "Corp"

I don't think "Corp" is a word.

> laurencullen <mailto:notifications@github.com>
> August 5, 2015 at 9:23 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> would Dev Corps be an edit
> to an existing badge or a new one? If a new badge, please let me know
> the description of what it would be awarding (this way I have context
> for the design). Thanks!
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130#issuecomment-128057311>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre Here is the badge for Dev Corps
Please let me know if there is anything else.
![devcorps](https://cloud.githubusercontent.com/assets/13141571/9094346/1c5ab578-3b66-11e5-95af-434952f17f3f.jpg)

**Comment by ctmcintyre** [comment]
beautiful!

> laurencullen <mailto:notifications@github.com>
> August 5, 2015 at 11:35 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> Here is the badge for Dev
> Corps
> Please let me know if there is anything else.
> devcorps
> <https://cloud.githubusercontent.com/assets/13141571/9094346/1c5ab578-3b66-11e5-95af-434952f17f3f.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130#issuecomment-128102712>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 11:42 AM
>
> Lets create these new badges for UC Next:
>
> a. UCCSC 2015 Attendee - use the UCCSC 2015 logo - https://uccsc.ucr.edu/
> b. UCCSC 2015 Presenter
> c. UC Next -- First 100 Idea Generator
> d. UC Next - First 100 Project Collaborator
> e. UC Next Corp -- Anyone who creates a project or volunteers to
> participate on a project
> f. UC Next Developer
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@krozett Here are the png files for all of the badges including changes discussed today. I will also post these in another thread to make sure you see them. Please let me know if you need anything else. Thanks!

![devcorps](https://cloud.githubusercontent.com/assets/13141571/9278885/b3e49edc-4268-11e5-8110-1b404ce539b3.png)
![developer](https://cloud.githubusercontent.com/assets/13141571/9278886/b3e699ee-4268-11e5-99c9-e61cb8a60b92.png)
![idea generator](https://cloud.githubusercontent.com/assets/13141571/9278887/b3ec2206-4268-11e5-91f8-f2886c410768.png)
![project collaborator](https://cloud.githubusercontent.com/assets/13141571/9278888/b3ef6826-4268-11e5-9330-2c91f718979c.png)
![sautter gold 2014](https://cloud.githubusercontent.com/assets/13141571/9278889/b3f08b8e-4268-11e5-8c58-d43644a367cb.png)
![sautter gold 2015](https://cloud.githubusercontent.com/assets/13141571/9278890/b3f48040-4268-11e5-944b-7ba28b0cac54.png)
![sautter silver 2014](https://cloud.githubusercontent.com/assets/13141571/9278891/b3f9b38a-4268-11e5-8284-54f133bea1ac.png)
![sautter silver 2015](https://cloud.githubusercontent.com/assets/13141571/9278892/b3fd77ea-4268-11e5-9530-ee3b349f4b6f.png)
![uccsc attendee](https://cloud.githubusercontent.com/assets/13141571/9278893/b4037a32-4268-11e5-9611-875be6b711ba.png)
![uccsc presenter](https://cloud.githubusercontent.com/assets/13141571/9278894/b407bd0e-4268-11e5-9466-67799a700afc.png)

**Comment by krozett** [comment]
@laurencullen great, I will upload these to the production site! (though anyone else is free to do so, it can be done entirely through the admin interface)

**Comment by ctmcintyre** [comment]
It's always "CORPS" with an "S".  UC NEXT CORP needs to be changed to UC NEXT CORPS.  (Pronounced "CORE").  The image needs to be updated.

**Comment by laurencullen** [comment]
@ctmcintyre I'm replacing the UC NEXT DEV CORPS WITH UC NEXT CORPS. Please let me know if you need anything else.

![corps](https://cloud.githubusercontent.com/assets/13141571/9311074/d5a15a9e-44c8-11e5-93c3-15e6114b6986.png)

**Comment by ctmcintyre** [comment]
Awesome!  Thank you!

> laurencullen <mailto:notifications@github.com>
> August 17, 2015 at 10:16 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> I'm replacing the UC NEXT
> DEV CORPS WITH UC NEXT CORPS. Please let me know if you need anything
> else.
>
> corps
> <https://cloud.githubusercontent.com/assets/13141571/9311074/d5a15a9e-44c8-11e5-93c3-15e6114b6986.png>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130#issuecomment-131893693>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 11:42 AM
>
> Lets create these new badges for UC Next:
>
> a. UCCSC 2015 Attendee - use the UCCSC 2015 logo - https://uccsc.ucr.edu/
> b. UCCSC 2015 Presenter
> c. UC Next -- First 100 Idea Generator
> d. UC Next - First 100 Project Collaborator
> e. UC Next Corp -- Anyone who creates a project or volunteers to
> participate on a project
> f. UC Next Developer
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/130>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre Here is the new badge for MMWCON attendee. Please let me know if you need anything else with it. 
![mmwcon badge](https://cloud.githubusercontent.com/assets/13141571/9892166/28bbe028-5bc1-11e5-962b-aea3b2cb36c3.png)

**Comment by laurencullen** [comment]
@ctmcintyre @krozett @rrocchio Here are the three new badges for CFTM winners 2015. Please let me know if you have any changes or if you need any other years.

![cftm education 2015](https://cloud.githubusercontent.com/assets/13141571/10081143/51fea162-62a8-11e5-9335-ce62457c4edd.png)
![cftm service 2015](https://cloud.githubusercontent.com/assets/13141571/10081145/51ffafbc-62a8-11e5-9efc-55ca326c9051.png)
![cftm research 2015](https://cloud.githubusercontent.com/assets/13141571/10081144/51ff1174-62a8-11e5-8750-4d84d7e2b296.png)
