### ISSUE TITLE
Design an About page for UC Next

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#132]
Please design up an about page for UC Next  ( It will be the same Logged in and Not Logged in)

It should have the following content:

What "is" UC Next?

UC Next is an IT crowd sourced movement to bring about more UC System collaboration, more innovative ideation and IT community camaraderie towards our shared UC Mission of excellence in Education, Research and Service.  It is a project that was born out of the (ITLC) Information Technology Leadership Council's  Collaborative Technology Group (CTG).  We presented our concept to the ITLC in the fall of 2014, did an alpha demo for them in February of 2015 and are launching our Beta version of the system at UCCSC 2015 @ UC Riverside!

** Note to Lauren - we should link Information Technology Leadership Council to this link: (http://www.ucop.edu/information-technology-services/initiatives/information-technology-leadership-council.html)

What is the UC Next Platform?

o	The UC NeXt Platform brings the 7000 UC IT staff together to work on great ideas.
o	UC NeXt is a community for UC IT staff to work on new ideas together.
o	The UC NeXt Platform produces the best of UC IT

What does the UC NEXT Platform do?

The UC NeXt Platform will allow passionate and inspired technologists to grow their innovative projects and ideas into broader system-wide collaborations.  IT staff can “like” ideas, offer comments to improve them, and even volunteer their time towards helping grow them.  Project Managers can search for specific expertise across the entire UC system.  Engineers can engage with projects they have passion in and build their reputation.

**Comment by ctmcintyre** [comment]
"What is the UC Next Platform" should be one bullet/definition:

I prefer: "UC NeXt is a community for UC IT staff to work on new ideas
together."

> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 12:59 PM
>
> Please design up an about page for UC Next ( It will be the same
> Logged in and Not Logged in)
>
> It should have the following content:
>
> What "is" UC Next?
>
> UC Next is an IT crowd sourced movement to bring about more UC System
> collaboration, more innovative ideation and IT community camaraderie
> towards our shared UC Mission of excellence in Education, Research and
> Service. It is a project that was born out of the (ITLC) Information
> Technology Leadership Council's Collaborative Technology Group (CTG).
> We presented our concept to the ITLC in the fall of 2014, did an alpha
> demo for them in February of 2015 and are launching our Beta version
> of the system at UCCSC 2015 @ UC Riverside!
>
> ** Note to Lauren - we should link Information Technology Leadership
> Council to this link:
> (http://www.ucop.edu/information-technology-services/initiatives/information-technology-leadership-council.html)
>
> What is the UC Next Platform?
>
> o The UC NeXt Platform brings the 7000 UC IT staff together to work on
> great ideas.
> o UC NeXt is a community for UC IT staff to work on new ideas together.
> o The UC NeXt Platform produces the best of UC IT
>
> What does the UC NEXT Platform do?
>
> The UC NeXt Platform will allow passionate and inspired technologists
> to grow their innovative projects and ideas into broader system-wide
> collaborations. IT staff can "like" ideas, offer comments to improve
> them, and even volunteer their time towards helping grow them. Project
> Managers can search for specific expertise across the entire UC
> system. Engineers can engage with projects they have passion in and
> build their reputation.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/132>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Attached is a rough draft proof of this page. @ctmcintyre please let me know if I made the text revises to what you are looking for.

Please let me know any feedback.

![about](https://cloud.githubusercontent.com/assets/13141571/9096107/06955dc4-3b70-11e5-93ab-11596a95bf26.jpg)

**Comment by ctmcintyre** [comment]
Love it! 

> laurencullen <mailto:notifications@github.com>
> August 5, 2015 at 12:46 PM
>
> Attached is a rough draft proof of this page. @ctmcintyre
> <https://github.com/ctmcintyre> please let me know if I made the text
> revises to what you are looking for.
>
> Please let me know any feedback.
>
> about
> <https://cloud.githubusercontent.com/assets/13141571/9096107/06955dc4-3b70-11e5-93ab-11596a95bf26.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/132#issuecomment-128127166>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 12:59 PM
>
> Please design up an about page for UC Next ( It will be the same
> Logged in and Not Logged in)
>
> It should have the following content:
>
> What "is" UC Next?
>
> UC Next is an IT crowd sourced movement to bring about more UC System
> collaboration, more innovative ideation and IT community camaraderie
> towards our shared UC Mission of excellence in Education, Research and
> Service. It is a project that was born out of the (ITLC) Information
> Technology Leadership Council's Collaborative Technology Group (CTG).
> We presented our concept to the ITLC in the fall of 2014, did an alpha
> demo for them in February of 2015 and are launching our Beta version
> of the system at UCCSC 2015 @ UC Riverside!
>
> ** Note to Lauren - we should link Information Technology Leadership
> Council to this link:
> (http://www.ucop.edu/information-technology-services/initiatives/information-technology-leadership-council.html)
>
> What is the UC Next Platform?
>
> o The UC NeXt Platform brings the 7000 UC IT staff together to work on
> great ideas.
> o UC NeXt is a community for UC IT staff to work on new ideas together.
> o The UC NeXt Platform produces the best of UC IT
>
> What does the UC NEXT Platform do?
>
> The UC NeXt Platform will allow passionate and inspired technologists
> to grow their innovative projects and ideas into broader system-wide
> collaborations. IT staff can "like" ideas, offer comments to improve
> them, and even volunteer their time towards helping grow them. Project
> Managers can search for specific expertise across the entire UC
> system. Engineers can engage with projects they have passion in and
> build their reputation.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/132>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by rrocchio** [comment]
@laurencullen - Love it!
