### ISSUE TITLE
Need to Design the sub page for Ideas - logged in and not logged in

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#135]
The NON-Logged in page for Ideas, should show the 5 Top Trending Ideas, but not any more, also, it needs to ask the User to LOGIN - if they click on those ideas to see the details

Use this content:
--------------------------
Ideas are the currency of the 21st Century, so collecting them, sharing them, and valuing them is the first step in creating a culture of innovation in the IT community at the UC!  As you are going through your day keep in mind that your ideas are important, they matter, and that others might help you with them, if they just knew about them.  Think of the UC Next platform - when you have that stroke of Genius, as the place to put these ideas, so that collectively we can move the bar across the system, and innovate faster with more alignment with our shared mission of Education, Research and Service!

The Information Technology Leadership council has agreed that a tool like UC Next is the kind of platform that the IT community of the UC needs!  They have agreed to look at our top 5 new ideas each month at their monthly meetings, that explains just how important the CIOs of the UC feel your ideas are!
---------------------

Then lets display the meter of what is hot - in the ideas space

and then have the links ask for login - if clicked on...

Engagement meter for ideas - by campus.....

--------------------------------------------------------
The logged in view of Ideas might look something like this:  (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet )

**Comment by rrocchio** [comment]
@ctmcintyre  - have a look at this content - tell me what you think - tweak as you like....

**Comment by ctmcintyre** [comment]
Agreed

> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Here is a rough draft of the NOT logged in state. I included one option with the engagement meter in new coloring to distinguish it from the project engagement meter and another version with the same coloring as the project engagement meter. Please let me know any feedback. Thanks!

![ideas2](https://cloud.githubusercontent.com/assets/13141571/9100702/ce364fc4-3b92-11e5-9f83-979568761657.jpg)
![ideas1](https://cloud.githubusercontent.com/assets/13141571/9100703/ce3823bc-3b92-11e5-8d0e-71761f52803d.jpg)

**Comment by ctmcintyre** [comment]
The copy is a bit dense.  It took me a couple reads to ready understand
it.  We should thin it out or put some paragraph breaks in between the
sentences.

> laurencullen <mailto:notifications@github.com>
> August 5, 2015 at 4:56 PM
>
> Here is a rough draft of the NOT logged in state. I included one
> option with the engagement meter in new coloring to distinguish it
> from the project engagement meter and another version with the same
> coloring as the project engagement meter. Please let me know any
> feedback. Thanks!
>
> ideas2
> <https://cloud.githubusercontent.com/assets/13141571/9100702/ce364fc4-3b92-11e5-9f83-979568761657.jpg>
> ideas1
> <https://cloud.githubusercontent.com/assets/13141571/9100703/ce3823bc-3b92-11e5-8d0e-71761f52803d.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-128186502>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre attached is a version with more paragraphs. Please let me know if you would like to edit the text or do something different.

Also, do you like the blue idea engagement meter or the idea engagement meter that is in the same colors as the project engagement meter?

![ideas 8 6](https://cloud.githubusercontent.com/assets/13141571/9117609/4b70921e-3c20-11e5-92b3-d45ea6e4c861.jpg)

**Comment by ctmcintyre** [comment]
Can you add another paragraph break between "them." and "Think"?

I liked the yellow-orange meter since they're warmer colors.  The blue
is nice b/c it's congruent with the rest of the color scheme but it's a
bit "cold". 

> laurencullen <mailto:notifications@github.com>
> August 6, 2015 at 9:49 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> attached is a version with
> more paragraphs. Please let me know if you would like to edit the text
> or do something different.
>
> Also, do you like the blue idea engagement meter or the idea
> engagement meter that is in the same colors as the project engagement
> meter?
>
> ideas 8 6
> <https://cloud.githubusercontent.com/assets/13141571/9117609/4b70921e-3c20-11e5-92b3-d45ea6e4c861.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-128438408>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre I agree that the yellow-orange meter looks better because it is warmer. Is it ok that the idea engagement meter and project engagement meter are not visually distinguishable?

Here is a new proof:
![ideas-01](https://cloud.githubusercontent.com/assets/13141571/9118533/d070c290-3c25-11e5-92ac-07aab54f03c8.jpg)

**Comment by laurencullen** [comment]
Here is a rough draft proof of the ideas page logged in. Please let me know any changes.

![ideasloggedin](https://cloud.githubusercontent.com/assets/13141571/9121090/05b83cf8-3c35-11e5-92ce-f98f1a677341.jpg)

**Comment by ctmcintyre** [comment]
Looks great!

> laurencullen <mailto:notifications@github.com>
> August 6, 2015 at 12:17 PM
>
> Here is a rough draft proof of the ideas page logged in. Please let me
> know any changes.
>
> ideasloggedin
> <https://cloud.githubusercontent.com/assets/13141571/9121090/05b83cf8-3c35-11e5-92ce-f98f1a677341.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-128478750>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by ctmcintyre** [comment]
For now I'm OK with same color.  Perhaps make Ideas and Projects more
distinguishable?


> laurencullen <mailto:notifications@github.com>
> August 6, 2015 at 10:28 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> I agree that the
> yellow-orange meter looks better because it is warmer. Is it ok that
> the idea engagement meter and project engagement meter are not
> visually distinguishable?
>
> Here is a new proof:
> ideas-01
> <https://cloud.githubusercontent.com/assets/13141571/9118533/d070c290-3c25-11e5-92ac-07aab54f03c8.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-128451305>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
I tried making the word more distinguishable... if you like this, I will also do this on non logged in state and on homepage for projects. Please let me know what you think.

![ideasloggedinnew-01](https://cloud.githubusercontent.com/assets/13141571/9124935/577f809e-3c50-11e5-8416-66ec290741d7.jpg)

**Comment by ctmcintyre** [comment]
I love the idea cards below. I didn't see those before. 

Not sure about the bulb-IDEAS-bulb. Kind of busy. Perhaps we don't need to say ideas again since it's the ideas page? The word "ideas" is already a title 4x on the page. Perhaps we just say "Engagement Meter". 


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by laurencullen** [comment]
Changed it to engagement meter. Please let me know if you have any revisions.
The idea cards only appear in logged in state. (Logged out page is the same but without the idea cards as seen in proof above.)

![ideasloggedin-01](https://cloud.githubusercontent.com/assets/13141571/9140394/ccf41e9e-3ce5-11e5-8512-fc4cfd99020b.jpg)

**Comment by ctmcintyre** [comment]
Great!

> laurencullen <mailto:notifications@github.com>
> August 7, 2015 at 9:23 AM
>
> Changed it to engagement meter. Please let me know if you have any
> revisions.
> The idea cards only appear in logged in state. (Logged out page is the
> same but without the idea cards as seen in proof above.)
>
> ideasloggedin-01
> <https://cloud.githubusercontent.com/assets/13141571/9140394/ccf41e9e-3ce5-11e5-8512-fc4cfd99020b.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-128754237>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
For the top five, would you like metrics added to match project page?

**Comment by rrocchio** [comment]
@laurencullen - Let's change the text under the meter and call it "Idea Points"

**Comment by rrocchio** [comment]
Let's call it the "Idea Engagement Meter"

**Comment by rrocchio** [comment]
@laurencullen - otherwise Love it!!!

**Comment by rrocchio** [comment]
@laurenc

**Comment by rrocchio** [comment]
Keep closing by accident

**Comment by laurencullen** [comment]
Attached is a proof with the engagement meter text revisions. Please let me know if you need anything else.

![ideasloggedin-01](https://cloud.githubusercontent.com/assets/13141571/9178334/82efa166-3f4b-11e5-8fe9-b6fe01b1ba0f.jpg)

**Comment by laurencullen** [comment]
Here is logged out state:
![ideas-01](https://cloud.githubusercontent.com/assets/13141571/9178357/b791fb94-3f4b-11e5-9482-2dd3ed68c263.jpg)

**Comment by laurencullen** [comment]
@krozett In response to @ctmcintyre's email, here is a proof of the ideas page with trending ideas on left and the engagement meter by itself on the right.

![ideasloggedin-02](https://cloud.githubusercontent.com/assets/13141571/9283261/24d8099e-4287-11e5-9183-7091ae3698ef.jpg)

**Comment by ctmcintyre** [comment]
Thanks Lauren!  It's still not succeeding at reducing empty space. 
@krozett - when you lay this in, try to minimize the empty space between
the top elements and the idea cards.

> laurencullen <mailto:notifications@github.com>
> August 14, 2015 at 1:20 PM
>
> @krozett <https://github.com/krozett> In response to @ctmcintyre
> <https://github.com/ctmcintyre>'s email, here is a proof of the ideas
> page with trending ideas on left and the engagement meter by itself on
> the right.
>
> ideasloggedin-02
> <https://cloud.githubusercontent.com/assets/13141571/9283261/24d8099e-4287-11e5-9183-7091ae3698ef.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135#issuecomment-131229967>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 1:48 PM
>
> The NON-Logged in page for Ideas, should show the 5 Top Trending
> Ideas, but not any more, also, it needs to ask the User to LOGIN - if
> they click on those ideas to see the details
>
> Use this content:
>
> display the meter of what is hot - and then have the links ask for
> login - if clicked on...
>
> Engagement meter for ideas - by campus.....
>
> ------------------------------------------------------------------------
>
> The logged in view of Ideas might look something like this:
> (https://www.jivesoftware.com/resource-library/?_type[]=analystreport&_type[]=casestudy&_type[]=infographic&_type[]=datasheet
> <https://www.jivesoftware.com/resource-library/?_type%5B%5D=analystreport&_type%5B%5D=casestudy&_type%5B%5D=infographic&_type%5B%5D=datasheet>
> )
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/135>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839
