### ISSUE TITLE
The Projects Sub Page....

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#136]
For Projects - Lets use the same Design that we come up with for IDEAS - only with a little bit different "heading" on the grid boxes...

For projects lets add this prose:
------------------------------------------------------------------------------------------
Projects are how we work together and actually coordinate our collaboration!  UC Next is a place to find out who is looking for partners, collaborators and anyone who might be trying to solve the same or similar problems.  It's not a stodgy portfolio tool, but rather a virtual meeting place to find like minded team members who can help us get solutions in place faster, more efficiently and with a shared purpose of furthering our shared mission of providing World Class Education, Research support and Service.

----------------------------------------------------------------------------------------------------------------------------------------

**Comment by ctmcintyre** [comment]
remove "stodgy"

> RoseRocchio <mailto:notifications@github.com>
> August 4, 2015 at 3:02 PM
>
> For Projects - Lets use the same Design that we come up with for IDEAS
> - only with a little bit different "heading" on the grid boxes...
>
>
>     For projects lets add this prose:
>
> Projects are how we work together and actually coordinate our
> collaboration! UC Next is a place to find out who is looking for
> partners, collaborators and anyone who might be trying to solve the
> same or similar problems. It's not a stodgy portfolio tool, but rather
> a virtual meeting place to find like minded team members who can help
> us get solutions in place faster, more efficiently and with a shared
> purpose of furthering our shared mission of providing World Class
> Education, Research support and Service.
>
> ------------------------------------------------------------------------
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/136>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Here are rough draft proofs of not logged in and logged in. Please let me know any changes. Also, would you like to add more text so that it is more similar to ideas page?

![projects](https://cloud.githubusercontent.com/assets/13141571/9147441/fc33009a-3d1b-11e5-9a00-6a8579e04475.jpg)
![projectsloggedin](https://cloud.githubusercontent.com/assets/13141571/9147443/07accadc-3d1c-11e5-9414-a3d7247d47ae.jpg)

**Comment by ctmcintyre** [comment]
They look great!

For the top trending ideas and projects, we should put metrics (how many up votes, etc)

C


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by laurencullen** [comment]
Sounds good! Do you mean something like where Facebook lists a number of likes in a little box coming off of the like button? We could also put the +1 sign next to the box for the logged in state so that users could quickly take action... 

Proofs attached, please let me know what you think.

![projects](https://cloud.githubusercontent.com/assets/13141571/9148229/c930d01a-3d29-11e5-833b-a55c75e14fb1.jpg)
![projectsloggedin](https://cloud.githubusercontent.com/assets/13141571/9148230/c9319ff4-3d29-11e5-9b11-13bb10d8a36c.jpg)

**Comment by rrocchio** [comment]
@laurencullen - LOVE this idea!!!!

**Comment by rrocchio** [comment]
@ctmcintyre - Awesome idea!!!

**Comment by rrocchio** [comment]
@krozett  - Found a content error on the first sentence under the "UC Next Projects" heading.  The first sentence needs to be finished off with "our collaboration!".

Thanks!

**Comment by ctrance** [comment]
@krozett - I don't see metrics for the 5 top trending projects

**Comment by ctrance** [comment]
@krozett - On Lauren's design the "not logged in" version of Projects doesn't show the UC NEXT PROJECTS section list.

**Comment by laurencullen** [comment]
@krozett this was something decided originally in the requirements for the design. The projects list is supposed to be hidden for users who aren't logged in.

**Comment by krozett** [comment]
@laurencullen but does it make sense? After all, users can still access any project page. Why not just show the list?

Anyone else want to weigh in? I simply can't think of any reason to not list them all, but I can think of many reasons to list them. Consistency, better user experience, SEO, etc.

**Comment by joshuaselsky** [comment]
Closing because we will add "visibility status" to projects
