### ISSUE TITLE
Design for the Events sub page for UC Next

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#137]
This can be the same for logged in and not logged in users

Lets just pretty this up  - and it should probably start like a list, but we may go to a monthly grid once we have more events in it... -

**Comment by laurencullen** [comment]
Attached is the events sub page rough draft. Is it possible for the event listing to be an accordion? This proof shows the first event opened. If not, I can make one page for listings and a second page for details, so please let me know.

![events-01](https://cloud.githubusercontent.com/assets/13141571/9124684/f9f05f18-3c4d-11e5-9595-6022b92dcacb.jpg)

**Comment by ctmcintyre** [comment]
That's gorgeous!  Wow!


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by laurencullen** [comment]
Here are proofs of the events put into a list page and a details page. Please let me know any changes.

![events-1](https://cloud.githubusercontent.com/assets/13141571/9146698/b77d4260-3d13-11e5-8952-dd6539f23bf2.jpg)

![events-2](https://cloud.githubusercontent.com/assets/13141571/9146703/c3b141a8-3d13-11e5-80e8-5303e07378c0.jpg)

**Comment by laurencullen** [comment]
@ctmcintyre Thanks :)

**Comment by rrocchio** [comment]
@laurencullen - yes!  I love it!!!!
