### ISSUE TITLE
Lay in the Final Design for the UC Next Landing page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#139]
[UCNext.mockup.7.30 - FINAL mockup.pdf](https://github.com/universityofcalifornia/NeXt/files/1153/UCNext.mockup.7.30.-.FINAL.mockup.pdf)

**Comment by rrocchio** [comment]
@laurencullen  - We are going to want the photo montage to reduce down in size - by those blocks using Media Query... Lauren can you create about 5 different sizes of the images - so that Keith can make the home page use the smaller images as the size of the window reduces down....  

** I have requested UCSF to send me images from the last UCCSC conference - but if you create the images now, we can swap out the the files for Keith later...

**Comment by krozett** [comment]
See my notes in individual issues for how to use the new styles:

Buttons - https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-128606499
Panels - https://github.com/universityofcalifornia/NeXt/issues/120#issuecomment-128607099

To get the alternating color effect, use the list-group Bootstrap component:
http://getbootstrap.com/components/#list-group

If you want yellow instead of pale blue, give the list group the `list-group-secondary` class **in addition** to the `list-group` class.

**Comment by krozett** [comment]
Question for @laurencullen - I feel a bit silly asking, maybe it's already been mentioned, but is this design fixed width for the content? I assume the header/footer take up the full width, but it's hard to tell with the body.

**Comment by laurencullen** [comment]
@krozett Yes, the header/footer take up the full width and the body should scale. What would be best for you from a development perspective?

**Comment by laurencullen** [comment]
Here is the final design. It is a PDF that can be opened and edited in Adobe Illustrator.

[UCNext mockup 8.7.pdf](https://github.com/universityofcalifornia/NeXt/files/1244/UCNext.mockup.8.7.pdf)

**Comment by krozett** [comment]
@laurencullen okay, great! That's what we are already doing anyway :laughing: 

BTW, it looks like the only change in the latest mockup is the yellow in the engagement meter bars and "speedometer" image. Is that right?

**Comment by laurencullen** [comment]
@krozett Yes, looks the same except for the yellow was brightened. Please let me know if you need anything else with it :)

**Comment by laurencullen** [comment]
@krozett please change the background light blue throughout from#eef4f9 to #dfeaf3. This will be a little easier to see. Thanks!

**Comment by krozett** [comment]
@laurencullen okay, done

**Comment by laurencullen** [comment]
@krozett great, thanks!!

**Comment by ctrance** [comment]
@krozett - I don't see the social section on the landing page.

**Comment by krozett** [comment]
@ctrance We decided to axe that section for now, we can always create a new issue if we want to add it back.

**Comment by ctrance** [comment]
Got it, closing this then!
