### ISSUE TITLE
Can you add a screen shot of the current Groups page 

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#141]
@krozett   - can you add a screen shot of the current Groups page - we need to see what this looks like so Lauren can redesign it - we can't get in to test until @ebollens  - adds a local login - or our Shibb connection works....

**Comment by krozett** [comment]
Main groups page with no groups
![screenshot 2015-08-05 at 17 43 29](https://cloud.githubusercontent.com/assets/1661295/9101290/cc94db8e-3b99-11e5-8771-4f6329ac9f57.png)

**Comment by krozett** [comment]
Popup which appears when you start typing
![screenshot 2015-08-05 at 17 43 46](https://cloud.githubusercontent.com/assets/1661295/9101294/de1a87be-3b99-11e5-9ed0-7fddfc4fffd9.png)

**Comment by krozett** [comment]
Popup for creating a new group
![screenshot 2015-08-05 at 17 44 10](https://cloud.githubusercontent.com/assets/1661295/9101297/ec3b5800-3b99-11e5-880d-8f0888f14ab7.png)

**Comment by krozett** [comment]
Groups page after joining some groups
![screenshot 2015-08-05 at 17 44 51](https://cloud.githubusercontent.com/assets/1661295/9101301/f968e1c8-3b99-11e5-9689-9831c39a91e9.png)

**Comment by ctmcintyre** [comment]
Let's put some language here that says something like, "Please consider
joining an existing group before creating a new group"

> Keith Rozett <mailto:notifications@github.com>
> August 5, 2015 at 5:47 PM
>
> Groups page after joining some groups
> screenshot 2015-08-05 at 17 44 51
> <https://cloud.githubusercontent.com/assets/1661295/9101301/f968e1c8-3b99-11e5-9689-9831c39a91e9.png>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/141#issuecomment-128196228>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by joshuaselsky** [comment]
Since the UI has changed drastically since this thread, we (@joshuaselsky @krozett) are closing this. We can open a new issue or issues if necessary.
