### ISSUE TITLE
Design for the UC Next input screen

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#145]
@laurencullen  - this can be the same styling as the profile input screen

**Comment by laurencullen** [comment]
Here is a proof of the event input page:
![ucnext event input-01](https://cloud.githubusercontent.com/assets/13141571/9125340/b1485494-3c54-11e5-8c47-4847c0a3a47d.jpg)

**Comment by laurencullen** [comment]
Image size to upload: 700x230px

**Comment by laurencullen** [comment]
Here is the input screen for Propose Idea. Create Project would be the same. Please let me know if you need anything else.

![idea-input](https://cloud.githubusercontent.com/assets/13141571/9204484/72fc3d4c-4012-11e5-90bf-1aaaa50b5aab.jpg)

**Comment by ctmcintyre** [comment]
Shouldn't it read "Required Competencies"?



> laurencullen <mailto:notifications@github.com>
> August 11, 2015 at 10:19 AM
>
> Here is the input screen for Propose Idea. Create Project would be the
> same. Please let me know if you need anything else.
>
> idea-input
> <https://cloud.githubusercontent.com/assets/13141571/9204484/72fc3d4c-4012-11e5-90bf-1aaaa50b5aab.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/145#issuecomment-129977041>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 6, 2015 at 10:32 AM
>
> @laurencullen <https://github.com/laurencullen> - this can be the same
> styling as the profile input screen
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/145>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
Here is a new proof if you decide to change it to Required Competencies:

![idea-input2-01](https://cloud.githubusercontent.com/assets/13141571/9207582/6d70ff1e-4023-11e5-874c-53ed010bc406.jpg)
