### ISSUE TITLE
Successful account creation message shows html code

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#146]
I just created an account on FF 39.0 Windows 7 and see html code in the message, see below:
![capture](https://cloud.githubusercontent.com/assets/1034174/9119172/2d9e942a-3c2a-11e5-98e2-6a8021182811.PNG)

**Comment by krozett** [comment]
It's caused by issue #80

**Comment by krozett** [comment]
Should be fixed now.

**Comment by ctrance** [comment]
@krozett Can you also fix the "Login with campus account" button? The button is too small for the text, see below.
![capture](https://cloud.githubusercontent.com/assets/1034174/9173694/9654de08-3f30-11e5-8fb4-6658a1ef0ccb.jpg)

**Comment by ctrance** [comment]
fixed
