### ISSUE TITLE
Create a Design for the Groups page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#152]
@laurencullen  - please create a design for this page... here is what users will do on this page:

1)  See a list of the Groups they have "joined"
2) Search for Groups
3) Click on them to see details about them
4) Join them
5) Click on a Group they have joined and have the option to "Leave group"

**Comment by laurencullen** [comment]
Here are two options of logged in groups page. Please let me know any feedback. Also, I'll work on details pages. Do you need a logged out view as well?

![groups page-01](https://cloud.githubusercontent.com/assets/13141571/9186916/5a114680-3f7f-11e5-88f0-82017010ada8.jpg)
![groups page-02](https://cloud.githubusercontent.com/assets/13141571/9186915/5a103fb0-3f7f-11e5-9e49-0dc2fe40ab80.jpg)

**Comment by ctmcintyre** [comment]
Tiles!  Short Description nails it.

> laurencullen <mailto:notifications@github.com>
> August 10, 2015 at 4:46 PM
>
> Here are two options of logged in groups page. Please let me know any
> feedback. Also, I'll work on details pages. Do you need a logged out
> view as well?
>
> groups page-01
> <https://cloud.githubusercontent.com/assets/13141571/9186916/5a114680-3f7f-11e5-88f0-82017010ada8.jpg>
> groups page-02
> <https://cloud.githubusercontent.com/assets/13141571/9186915/5a103fb0-3f7f-11e5-9e49-0dc2fe40ab80.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/152#issuecomment-129648317>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 6, 2015 at 8:18 PM
>
> @laurencullen <https://github.com/laurencullen> - please create a
> design for this page... here is what users will do on this page:
>
> 1) See a list of the Groups they have "joined"
> 2) Search for Groups
> 3) Click on them to see details about them
> 4) Join them
> 5) Click on a Group they have joined and have the option to "Leave group"
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/152>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by rrocchio** [comment]
Hi All,  @laurencullen  - I agree with Charles, the tiles are the best!

**Comment by laurencullen** [comment]
Here is the details page rough draft. Please let me know if you need any revisions or if you need any additional related pages.

![groups-details-leave](https://cloud.githubusercontent.com/assets/13141571/9204122/1da90e58-4010-11e5-8e15-c758d41240ee.jpg)
![groups-details-join](https://cloud.githubusercontent.com/assets/13141571/9204126/20c1f726-4010-11e5-818e-dd182c6ad900.jpg)

**Comment by joshuaselsky** [comment]
@krozett please see #193 for the groups icons.

**Comment by joshuaselsky** [comment]
There are two more items to take care of before this issue can be closed.

1. Add the members to the page.
2. Add the group badge to the page.

This will also take care of #297.

**Comment by joshuaselsky** [comment]
@krozett I just added this to your queue if you can get to it. If we decide later that there is a graphic design task, we can address it then.

**Comment by joshuaselsky** [comment]
We decided to model the changes in [this comment](https://github.com/universityofcalifornia/NeXt/issues/152#issuecomment-163441480) using the design of the existing [badge details page](https://staging.ucnext.org/badges/2).

**Comment by krozett** [comment]
Index page is done (minus the search feature, which I've been ignoring so far on Ideas and Projects as well). All that remains is group details pages.

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - The group tiles look big for me it's that really how we're showing them? Also, I don't see the members on the group details page.
![capture](https://cloud.githubusercontent.com/assets/1034174/12430179/0e44c62a-bea3-11e5-970c-a06c355a01d9.PNG)

**Comment by krozett** [comment]
It looks like what is going on is that some of the groups have very long descriptions. We need to figure out what to do about this. I agree that it looks bad.

Projects and Ideas use the same layout, and they'll have the same problem with long descriptions, so we should apply the fix everywhere.

**Comment by ctrance** [comment]
@krozett and @joshuaselsky - Maybe we can limit the appearance of description length just on this page? If description is longer than the limit then we show "..." at the end to indicate there's more.

**Comment by krozett** [comment]
Let's see how a limit of 400 characters looks...

**Comment by ctrance** [comment]
Looks better now!
