### ISSUE TITLE
Hook up the UC Next app button to the site, so when the users "saves to homescreen" a bookmark gets created

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#162]
Hook up the UC Next app button ( this is coming, so you may need to use a place holder button for the time being...) to the site, so when the users "saves to homescreen" a bookmark gets created

**Comment by ebollens** [comment]
You can always save a webpage to home screen. Provide me with an icon, and I'll set it up so that you get that icon to show. Assigning to @laurencullen for the icon. Should use the standard iOS size for appicon.

**Comment by laurencullen** [comment]
Attached are five options for icons at 180x180px for you to choose from. I based size on what was listed here: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html. Please let me know if you have any changes or need the icons in a different size.

![ucnexticon-01](https://cloud.githubusercontent.com/assets/13141571/9177954/615a404e-3f49-11e5-82df-76d403146bf2.png)
![ucnexticon-02](https://cloud.githubusercontent.com/assets/13141571/9177955/61710bbc-3f49-11e5-8dd4-2b0e82370199.png)
![ucnexticon-03](https://cloud.githubusercontent.com/assets/13141571/9177957/6174a5a6-3f49-11e5-8655-32c176fe243e.png)
![ucnexticon-04](https://cloud.githubusercontent.com/assets/13141571/9177958/6177330c-3f49-11e5-911b-c7320858d8e9.png)
![ucnexticon-05](https://cloud.githubusercontent.com/assets/13141571/9177956/61747400-3f49-11e5-9e4a-8fe175ebfba0.png)

**Comment by ctmcintyre** [comment]
I vote for the 2nd from the top (light blue background, the wave and UC
NEXT at the top)

C

> laurencullen <mailto:notifications@github.com>
> August 10, 2015 at 10:20 AM
>
> Attached are five options for icons at 180x180px for you to choose
> from. I based size on what was listed here:
> https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html.
> Please let me know if you have any changes or need the icons in a
> different size.
>
> ucnexticon-01
> <https://cloud.githubusercontent.com/assets/13141571/9177954/615a404e-3f49-11e5-82df-76d403146bf2.png>
> ucnexticon-02
> <https://cloud.githubusercontent.com/assets/13141571/9177955/61710bbc-3f49-11e5-8dd4-2b0e82370199.png>
> ucnexticon-03
> <https://cloud.githubusercontent.com/assets/13141571/9177957/6174a5a6-3f49-11e5-8655-32c176fe243e.png>
> ucnexticon-04
> <https://cloud.githubusercontent.com/assets/13141571/9177958/6177330c-3f49-11e5-911b-c7320858d8e9.png>
> ucnexticon-05
> <https://cloud.githubusercontent.com/assets/13141571/9177956/61747400-3f49-11e5-9e4a-8fe175ebfba0.png>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/162#issuecomment-129533383>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@rrocchio and @ebollens - here are app icons to choose from.

**Comment by laurencullen** [comment]
High res versions and wave with blue background added:
![ucnexticon-01](https://cloud.githubusercontent.com/assets/13141571/9292595/6a24a4f8-43b8-11e5-97cd-849c489bfcf3.png)
![ucnexticon-02](https://cloud.githubusercontent.com/assets/13141571/9292596/6a426100-43b8-11e5-8696-b03f50f6dfb2.png)
![ucnexticon-03](https://cloud.githubusercontent.com/assets/13141571/9292597/6a45b7d8-43b8-11e5-85bb-915585150a10.png)
![ucnexticon-04](https://cloud.githubusercontent.com/assets/13141571/9292598/6a4951ea-43b8-11e5-88be-0a2c37e841e0.png)
![ucnexticon-05](https://cloud.githubusercontent.com/assets/13141571/9292599/6a4cf80e-43b8-11e5-9668-84db9a417e28.png)
![ucnexticon-06](https://cloud.githubusercontent.com/assets/13141571/9292600/6a4f46cc-43b8-11e5-83d9-64e43b1dadc3.png)
