### ISSUE TITLE
Lay in the final design for the Ideas page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#163]
Lay in the final design for the Ideas page - please see #135

**Comment by rrocchio** [comment]
![ideas image](https://cloud.githubusercontent.com/assets/718820/9186088/a5cb63de-3f76-11e5-94f7-4cdb853cbf07.jpg)

**Comment by rrocchio** [comment]
@krozett  - Can you please add the content of the "Ideas" page into that page.... This content is critically important!

**Comment by ctmcintyre** [comment]
It seems that we don't see over 9 ideas.  We need to make sure people can see their new ideas.

**Comment by krozett** [comment]
@ctmcintyre I created a test idea and verified that it showed up on the page, for a total of 10 ideas. Why do you say there are only 9?

**Comment by ctmcintyre** [comment]
I thought we had more to begin with and some folks said they put in
ideas, but I didn't see more than 1 new one.  Mostly I was just trying
to make sure it /would/ display more than 9.

Thank you for double-triple-checking!

C

> Keith Rozett <mailto:notifications@github.com>
> August 20, 2015 at 10:35 AM
>
> @ctmcintyre <https://github.com/ctmcintyre> I created a test idea and
> verified that it showed up on the page, for a total of 10 ideas. Why
> do you say there are only 9?
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/163#issuecomment-133088388>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 7, 2015 at 11:54 PM
>
> Lay in the final design for the Ideas page - please see #135
> <https://github.com/universityofcalifornia/NeXt/issues/135>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/163>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by ctrance** [comment]
I'm basing the new Idea format off of #208, as mentioned by @krozett he made Ideas look like projects page. I'm closing this...
