### ISSUE TITLE
Lay in a Design for the People Sub-page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#167]
@ebollens  - I never got a chance to ask @laurencullen  - to design the "People" Sub page, that lists everyone... Can you infer a design... Do you think it should have a "Leader board" on it?  Not sure...

**Comment by ebollens** [comment]
I think for now, let's go ahead and just leave it as a list of people. But in the future, yes, a leaderboard or something like that would make a lot of sense.

**Comment by rrocchio** [comment]
@ebollens  - Lauren will work on a non-logged in view - with a little more style, but we can keep the list - for now... then she will add some features to the logged in view, like the profile image and recent badges....

**Comment by rrocchio** [comment]
@ebollens  - we are going to see what it looks like to see the UC Logo instead of the text of the location....

**Comment by laurencullen** [comment]
Here is a proof of non-logged in state:

![people-01](https://cloud.githubusercontent.com/assets/13141571/9182176/2a198f08-3f5e-11e5-9082-1c5cae2fe19d.jpg)

**Comment by laurencullen** [comment]
Here is the logged in page with profile images added on left:
![peopleimg-02](https://cloud.githubusercontent.com/assets/13141571/9182375/300e51e0-3f5f-11e5-85fd-29eef1efdab2.jpg)

**Comment by laurencullen** [comment]
I'll do one more view for logged in option that includes badges... 
please let me know any feedback :)

**Comment by laurencullen** [comment]
Here is a logged in version with badges:
![people-03](https://cloud.githubusercontent.com/assets/13141571/9183092/19bd3c14-3f62-11e5-9631-911cf04cc759.jpg)

**Comment by laurencullen** [comment]
With badges, I had to reduce the character number under position. Will there be a character number set for name and position?

Please let me know any changes. Thanks!

**Comment by rrocchio** [comment]
I think that this looks good right now - no need to change it
