### ISSUE TITLE
Create a page to showcase UC Next's badges

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#169]
Create a page to showcase UC Next's badges - link to it from the People sub page..

The link could be something simple like "See all the UC Next Badges"

@krozett  - can you infer a design for this using the profile detail page on #119?  If you don't get to this, please reassign to EB

**Comment by laurencullen** [comment]
@krozett new png files for badges including badges for 2014 and 2015 Sautter awards now listed in #130 and pasted below. Please let me know if you need anything else. Thanks!

![devcorps](https://cloud.githubusercontent.com/assets/13141571/9278966/29bf7e1a-4269-11e5-975c-01d119a9f3dd.png)
![developer](https://cloud.githubusercontent.com/assets/13141571/9278967/29c86cdc-4269-11e5-97b1-a7eb362451fe.png)
![idea generator](https://cloud.githubusercontent.com/assets/13141571/9278968/29cb82b4-4269-11e5-982e-1826683df65d.png)
![project collaborator](https://cloud.githubusercontent.com/assets/13141571/9278969/29cc8c68-4269-11e5-97fb-2c17a041f2dd.png)
![sautter gold 2014](https://cloud.githubusercontent.com/assets/13141571/9278970/29d2470c-4269-11e5-98e1-a17361beb4d0.png)
![sautter gold 2015](https://cloud.githubusercontent.com/assets/13141571/9278971/29d7b23c-4269-11e5-883d-8dc06b69ef97.png)
![sautter silver 2014](https://cloud.githubusercontent.com/assets/13141571/9278972/29d99b7e-4269-11e5-990f-cde1939395d9.png)
![sautter silver 2015](https://cloud.githubusercontent.com/assets/13141571/9278973/29e006ee-4269-11e5-8449-66576e76a33d.png)
![uccsc attendee](https://cloud.githubusercontent.com/assets/13141571/9278974/29e4baae-4269-11e5-9228-525ecf4204a9.png)
![uccsc presenter](https://cloud.githubusercontent.com/assets/13141571/9278975/29e58f6a-4269-11e5-9337-a15980a3b9b1.png)

**Comment by ctrance** [comment]
Badges are now showcased on user's profile page.
