### ISSUE TITLE
Social Feed

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#175]
There's a section of the landing page devoted to this but no specifications anywhere. We should figure this out or drop it from the landing page.

**Comment by ctmcintyre** [comment]
We didn't talk much about this but something about a simple live feed that folks could post and respond to questions, and it could auto-announce new ideas and badges and when ideas are resources, etc. not sure if there's some gem out there that could just be roughed in for now...


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by joshuaselsky** [comment]
Closing because the Twitter feed has been added to the home page.
