### ISSUE TITLE
Update "About" link in footer

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#181]
The about link in footer currently points to https://ucnext.org/#; needs to point to https://ucnext.org/about

**Comment by ctmcintyre** [comment]
"Contact" and "Legal" also need pages

**Comment by rrocchio** [comment]
@ctmcintyre  - what do you think we should do with the contact page?  I think it should send an email to the UC Next Chair and Past - Chair....Do you want to create a listserv for us?

@ctmcintyre  - what about the "LEGAL" page - probably want a "user agreement" and mention of the license.

**Comment by ctmcintyre** [comment]
I'll create a new google group for ucnext. For now, I'll out you and me in it. 

Sounds good for LEGAL, I have no idea regarding the specifics. 

C


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by ctrance** [comment]
The about link is now pointing to the right page now, closing this!
