### ISSUE TITLE
Got error when deleting a created event

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#184]
I just created a future event then deleted it but I got the error below:
![capture](https://cloud.githubusercontent.com/assets/1034174/9181809/edc9e7ac-3f5b-11e5-9d70-06d0908461a8.PNG)

**Comment by krozett** [comment]
I can't reproduce the issue. Can you check to see if it's still happening?

**Comment by ctrance** [comment]
Deleting event doesn't throw error anymore. I'm closing this.
