### ISSUE TITLE
Add the Footer to the Design

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#187]
We need to add the UC Crest to the footer, I will add it here shortly!

**Comment by rrocchio** [comment]
I am attaching the WHITE images into this comment box
![projects](https://cloud.githubusercontent.com/assets/718820/9192817/3c5aa94e-3fc3-11e5-9bf2-22b01d7bfe6b.png)
![projects](https://cloud.githubusercontent.com/assets/718820/9192818/426f9bf0-3fc3-11e5-99bc-520e7141f8b7.png)

![ucseal](https://cloud.githubusercontent.com/assets/718820/9192822/473fcc86-3fc3-11e5-8a2b-690a8fd466ab.png)

![twitter](https://cloud.githubusercontent.com/assets/718820/9192827/4ec4a904-3fc3-11e5-983c-ff560748c310.png)

**Comment by ctrance** [comment]
fixed
