### ISSUE TITLE
Implement the Header Design

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#188]
@krozett  - we need to implement the header design....

**Comment by laurencullen** [comment]
@krozett the Nav bar hover isn't accessible. Some possible solutions could include the hover changing it to an accessible yellow/orange like #ffc277 and/or underlining the text. Please let me know if you have any questions on this. Thanks!

**Comment by krozett** [comment]
@laurencullen no problem, I made the color changed and had the links underline when hovering

**Comment by rrocchio** [comment]
@laurencullen  and @krozett  - thanks !

**Comment by laurencullen** [comment]
Awesome, thanks @krozett!

**Comment by ctrance** [comment]
fixed
