### ISSUE TITLE
Please lay in the REST of the design for the Projects Page: The content, the top 5 projects and make them appear in a grid

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#189]
![projects](https://cloud.githubusercontent.com/assets/718820/9186416/5aca4c30-3f79-11e5-98a8-38c5c2d6a77f.jpg)

**Comment by rrocchio** [comment]
@krozett - Can you please make the following changes:

1) Please add the content of the "Projects" page into that page.... This content is critically important!
2) If we don't have time to do a specific "projects" engagement meter, then we can leave it off, but we should repeat the top level projects and we need the prose
3) Please make the projects show up in a "grid format" instead of rows
4) Please move the vote to the top right hand corner of the grid boxes

**Comment by ctrance** [comment]
@krozett - Everything looks good! I have a question though, how come some projects don't have vote icon on the upper right of grid boxes?

**Comment by krozett** [comment]
@ctrance If the user already voted for the project, they don't get a vote icon.

**Comment by ctrance** [comment]
@krozett - I must have forgotten voting on some of the projects. I just tested voting on other projects and the icon goes away. Thanks for the clarification!
