### ISSUE TITLE
Please implement this design for the Groups subpage

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#193]
![groups](https://cloud.githubusercontent.com/assets/718820/9193077/7a83c8c0-3fc5-11e5-9a8e-1fee6dad91e7.png)

**Comment by laurencullen** [comment]
Attached is the groups icon for this page and the group search icon.

The color of Create Group button is #ffc277 and for border #9c5500
The color of Join button is #fff48b and for border #fdba35
The color of More Information button is #77d8ff and for border #347bad

Please let me know if you need anything else.

![groups-icon](https://cloud.githubusercontent.com/assets/13141571/9203156/3e13ae2e-400a-11e5-9fd2-0a769d197b75.png)
![search-groups](https://cloud.githubusercontent.com/assets/13141571/9203250/de7a3d88-400a-11e5-9d1a-6ba6bf30b938.png)

**Comment by joshuaselsky** [comment]
Closing in favor of #152.
