### ISSUE TITLE
Lay in final design for People sub page - Not logged in

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#194]
** Please note - that the PEOPLE listed should sort Alphabetically...

![people-not-logged-in](https://cloud.githubusercontent.com/assets/718820/9193155/3801c866-3fc6-11e5-9ff1-7e17e7c1b357.png)

**Comment by laurencullen** [comment]
Here are all the assets and icons:

![people-icon](https://cloud.githubusercontent.com/assets/13141571/9203402/dbf2c296-400b-11e5-8eb8-98f14ab3e780.png)
![website](https://cloud.githubusercontent.com/assets/13141571/9203405/e217fc5e-400b-11e5-9f0b-3ae3eb959963.png)
![social](https://cloud.githubusercontent.com/assets/13141571/9203413/ec03d760-400b-11e5-98c8-15b60c34bf4a.png)

![twitter](https://cloud.githubusercontent.com/assets/13141571/9203419/f3b72476-400b-11e5-80a4-4609aed08e95.png)
![linkedin](https://cloud.githubusercontent.com/assets/13141571/9203424/fa66751a-400b-11e5-9fba-0733a290efe6.png)
![github](https://cloud.githubusercontent.com/assets/13141571/9203432/02a5e7b0-400c-11e5-80e8-3e7da42dacbc.png)

![linkedin](https://cloud.githubusercontent.com/assets/13141571/9203442/0cf28386-400c-11e5-9bbf-f6401305203b.png)

**Comment by laurencullen** [comment]
![google](https://cloud.githubusercontent.com/assets/13141571/9203450/1b43111c-400c-11e5-8d87-2df10cc83372.png)

**Comment by laurencullen** [comment]
![ucla](https://cloud.githubusercontent.com/assets/13141571/9203559/bf267ae4-400c-11e5-8911-acfcf793b2ed.png)
![ucsc](https://cloud.githubusercontent.com/assets/13141571/9203560/bf27c6ce-400c-11e5-8932-2c362585254e.png)
![ucsd](https://cloud.githubusercontent.com/assets/13141571/9203561/bf29d7ca-400c-11e5-976c-3205824457cf.png)

**Comment by laurencullen** [comment]
![ucsd](https://cloud.githubusercontent.com/assets/13141571/9203620/0bd122d6-400d-11e5-8c0c-504ae50de097.png)
![ucla](https://cloud.githubusercontent.com/assets/13141571/9203618/0bcbce76-400d-11e5-9ce6-3249ab385ee2.png)
![ucsc](https://cloud.githubusercontent.com/assets/13141571/9203619/0bd08aba-400d-11e5-9901-59bb6402745d.png)

**Comment by ctrance** [comment]
@krozett - People are still not listed alphabetically and the org icons are not showing.

**Comment by joshuaselsky** [comment]
Link to #195.

**Comment by ctrance** [comment]
fixed
