### ISSUE TITLE
Lay in final design for People sub page  - Logged in view

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#195]
This page should sort alphabetically as well as offer a SEARCH f(x)

The LOGGED in view - has images and also recent 
![people-logged-in-view](https://cloud.githubusercontent.com/assets/718820/9193222/b7a09958-3fc6-11e5-968a-ea910746ec35.png)
badges attained

**Comment by rrocchio** [comment]
@laurencullen  - when you get a chance, can you put all the logos from the campuses into this ticket - thanks!

**Comment by krozett** [comment]
Pull #217 will implement this. Badge display, school logos, and search will have to come later.

**Comment by laurencullen** [comment]
Here are hi res png files. Please let me know if you need anything else.

![berkeley](https://cloud.githubusercontent.com/assets/13141571/9310776/e4c3214e-44c6-11e5-9601-311d0d75c6f0.png)
![ucdavis](https://cloud.githubusercontent.com/assets/13141571/9310782/e4c955c8-44c6-11e5-8d31-d2d86ba30682.png)
![uchastings](https://cloud.githubusercontent.com/assets/13141571/9310779/e4c7eeae-44c6-11e5-9bf6-9d2e2cf3c8a1.png)
![uci](https://cloud.githubusercontent.com/assets/13141571/9310778/e4c70700-44c6-11e5-9ce7-f065df94f54c.png)
![ucla](https://cloud.githubusercontent.com/assets/13141571/9310780/e4c8bc80-44c6-11e5-9730-4debe7834de6.png)
![ucmerced](https://cloud.githubusercontent.com/assets/13141571/9310781/e4c8e73c-44c6-11e5-84cb-d6de185810be.png)
![ucriverside](https://cloud.githubusercontent.com/assets/13141571/9310783/e4d4ab4e-44c6-11e5-9f9d-6fb18486a0e3.png)
![ucsb](https://cloud.githubusercontent.com/assets/13141571/9310787/e4dd4fd8-44c6-11e5-89db-99b5a1d81643.png)
![ucsc](https://cloud.githubusercontent.com/assets/13141571/9310786/e4dc3d32-44c6-11e5-88ac-3acaf77dce05.png)
![ucsd](https://cloud.githubusercontent.com/assets/13141571/9310785/e4db8018-44c6-11e5-8faf-b8a1cbb05e7c.png)
![ucsf](https://cloud.githubusercontent.com/assets/13141571/9310784/e4d9af9a-44c6-11e5-9b3b-3076c19b551e.png)

**Comment by ctrance** [comment]
@krozett - The people list is not sorted by name in alpha order and there's no search fx to filter the list.

**Comment by krozett** [comment]
I'll look into adding a search.

@ctrance The list is sorted by last name. The person at the top probably put a space or something at the beginning of their last name.

@laurencullen Could you add logos for the labs and other locations as well? The engagement meter should have a complete list.

**Comment by ctrance** [comment]
@krozett - It doesn't look like it's sorting by last name, see below:
![capture](https://cloud.githubusercontent.com/assets/1034174/9860625/373aa7cc-5ae2-11e5-82ad-1cdb4e194724.PNG)

**Comment by krozett** [comment]
@ctrance Except for the first entry, the names look to be in last name order to me.

**Comment by ctrance** [comment]
@krozett - Yes, but still "Nnambi" shouldn't be the first on the list.

**Comment by laurencullen** [comment]
Here are more logos. Also, please use this UCSD logo instead of previous one. The ones that I could not find in vector are a little blurry - please let me know if these need to be recreated or if the ones from the web work. Also, if there is anything else you need or missing, please let me know.

![anr](https://cloud.githubusercontent.com/assets/13141571/10003414/18ff305a-6061-11e5-8dc5-3b8e3716094b.png)
![cdl](https://cloud.githubusercontent.com/assets/13141571/10003413/18ff1818-6061-11e5-802a-e7dc2b7539db.png)
![lanl](https://cloud.githubusercontent.com/assets/13141571/10003416/1900acb4-6061-11e5-98bc-c5191373d5e3.png)
![lbl](https://cloud.githubusercontent.com/assets/13141571/10003418/1901016e-6061-11e5-8e43-aeb87918f27d.png)
![llnl](https://cloud.githubusercontent.com/assets/13141571/10003415/1900bb78-6061-11e5-8c1d-645040b2b91a.png)
![uc](https://cloud.githubusercontent.com/assets/13141571/10003417/19012c02-6061-11e5-96ed-8448bc53d69b.png)
![ucsd](https://cloud.githubusercontent.com/assets/13141571/10003419/190f5e08-6061-11e5-99af-2f16a91f3bc7.png)

**Comment by ctrance** [comment]
Issues:
1. If I'm not logged in, I still see member photos 
2. Organization logo are still not showing

**Comment by joshuaselsky** [comment]
Assigning to @shaun965 for the last batch of fixes.

**Comment by shaun965** [comment]
Is it correct to assume office of the president should use the university of california picture?

**Comment by shaun965** [comment]
![screen shot 2015-11-17 at 5 30 24 pm](https://cloud.githubusercontent.com/assets/9622332/11230179/75771cd6-8d51-11e5-874f-a15aa9c8e892.png)
All the pictures seem good, only the one for the berkeley lab is not prominent enough.

**Comment by joshuaselsky** [comment]
> Is it correct to assume office of the president should use the university of california picture?

yes, it should!

**Comment by joshuaselsky** [comment]
@laurencullen can you attach a new text-based image for Berkeley Lab?

**Comment by laurencullen** [comment]
@joshuaselsky @shaun965 Here's a new logo. Please let me know if you need anything else or if you need a different size.

![berkeley_lab_text](https://cloud.githubusercontent.com/assets/13141571/11313595/e73e5e54-8f92-11e5-9e18-19dcda388c39.png)

**Comment by ctrance** [comment]
@shaun965 and @joshuaselsky - the Lawrence Berkeley Lab is showing old org icon, please use Lauren's new icon from https://github.com/universityofcalifornia/NeXt/issues/195#issuecomment-158543769. Also, the search tool is still missing.

**Comment by joshuaselsky** [comment]
The new Berkeley icon will be merged in with a new pull request. 

For the search feature, I am opening a new issue because there is too much going on in this one.

**Comment by ctrance** [comment]
fixed
