### ISSUE TITLE
Add this content into the 'ABOUT' Page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#198]
( I think we can put it under the cloud graphic)

<strong>UC Next Engagement Meter</strong> ( should open a page with Engagement details)
UC Next is all about incentivizing collaboration using gamification techniques.  This includes a UC System wide Engagement meter, which allows the campus locations a friendly but competitive measure of engagement.  Points are given to participants in different amounts for winning awards, submitting ideas and collaborating on projects.

**Comment by rrocchio** [comment]
(Please put this content under the Engagement Meter Text)
<strong>UC Next Badges</strong>
Collaborating can be hard work.  UC Next Badges are our new tool to recognize UC Technologist Leaders.  By creating and awarding badges we can recoginize the unsung heros among us who go the extra mile and take on the hard task of doing their work in a way that works for the good of the system, their campus and not just their immediate need.

**Comment by laurencullen** [comment]
@krozett just in case you need a proof of what this would look like:
![about-01](https://cloud.githubusercontent.com/assets/13141571/9280420/0060d2d0-4273-11e5-81c3-db783885a49c.jpg)

**Comment by ctmcintyre** [comment]
Great!

> laurencullen <mailto:notifications@github.com>
> August 14, 2015 at 10:56 AM
>
> @krozett <https://github.com/krozett> just in case you need a proof of
> what this would look like:
> about-01
> <https://cloud.githubusercontent.com/assets/13141571/9280420/0060d2d0-4273-11e5-81c3-db783885a49c.jpg>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/198#issuecomment-131194840>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 14, 2015 at 6:43 AM
>
> ( I think we can put it under the cloud graphic)
>
> strong
> UC Next is all about incentivizing collaboration using gamification
> techniques. This includes a UC System wide Engagement meter, which
> allows the campus locations a friendly but competitive measure of
> engagement.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/198>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by rrocchio** [comment]
@krozett  - please implement this as our highest priority tonight - along with the styling for the people page list

**Comment by ctrance** [comment]
@krozett - I don't see the Engagement Meter in About page. Also, on Lauren's design UC Next Badges has same text color (blue) as other titles.

**Comment by krozett** [comment]
@ctrance The problem with making the link the same color is that users will have no idea that it's a link. Although I think a better option is to not use the header for a link at all, but have a separate link below the paragraph.

@rrocchio Do we want to add the engagement meter to this page? I was basing my work off Lauren's design, but her design doesn't show the meter.

**Comment by joshuaselsky** [comment]
@krozett - the last thing to do here is to add the text about how the engagement meter works.

**Comment by joshuaselsky** [comment]
@shaun965 see the previous comment for the last bit of work to do on this issue.

**Comment by ctrance** [comment]
I still don't see the the text about how the engagement meter works.

**Comment by ctrance** [comment]
fixed
