### ISSUE TITLE
How do I assign badges to someone?

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#199]
How do I give someone a badge?  There is a "badge Group" - but I don't know how it works....

**Comment by krozett** [comment]
Right now the only way to do it is to go to a user's "all badges" page. There is supposed to be a link on their profile page, but it's gone now for some reason. Anyway, once there, if you have permission to give any badges (by being an owner or giver for that badge) there is a button in the top right saying "give this user a badge".

For now, you can manually go to /users/11/badges/new (replace 11 with the user id) and that will let you give that user a badge. It's broken right now though, and I'm not sure why. It works just fine on my local server...

**Comment by krozett** [comment]
Okay, the button will be visible once pull #214 is deployed. Anyone who has badge-giving permission (they are a badge owner or giver or are a super-admin) will see a button near the top of the profile

**Comment by ctrance** [comment]
Will retest this once I got admin access...

**Comment by ctrance** [comment]
Badge can now be assigned by the following:
1. When creating a new badge, group(s) can be assigned and whoever joins the group will get the badge.
2. To assign badge to yourself go to "My Profile" page, then click "Give badge/award" button.
3. To assign a badge to a person, go to "People" list > select a person > click "Give badge/award" button.
