### ISSUE TITLE
We need a design for a page to explain how the Engagement Meter works

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#200]
@laurencullen  - we need a page that explains how the engagement meter works:

Something that introduces it with content like this:

<Strong>UC Next Engagement Meter </strong>
UC Next is all about incentivizing collaboration using gamification techniques. This includes a UC System wide Engagement meter, which allows the campus locations a friendly but competitive measure of engagement. Points are given to participants in different amounts for winning awards, submitting ideas and collaborating on projects.

And then an area like this:

<strong> How to get points: </strong>

1) Setting up a Profile ADD 2 points; DELETE a profile SUBTRACT 2 points
2) Create a project ADD 5 points ; DELETE a project SUBTRACT 5 points
4) Like a project ADD 1 point
5) Comment on a project - ADD 2 points
3) Create an Idea ADD 3 points; DELETE an Idea SUBTRACT 3 points
4) Like an Idea ADD 1 point
5) Comment on an idea - ADD 2 points
6) Create a Group ADD 3 points ( DELETE a group - can only be done - if you are the only person in the group)
7) Join a Group ADD 1 point; LEAVE a group SUBTRACT 1 point
8) Awarding a GOLD Sautter Award for your campus = 50 points for you and your campus
9) Awarding a SILVER Sautter Award for your campus = 25 points for you and your campus
10) Removing an award subtracts those points

**Comment by laurencullen** [comment]
@krozett and @rrocchio here is a proof for the engagement page. I wasn't sure on headline text for paragraph. Please let me know if you need any revisions.
![engagement meter-01](https://cloud.githubusercontent.com/assets/13141571/9280200/93ca13e4-4271-11e5-8357-d282b41059c1.jpg)

**Comment by laurencullen** [comment]
@rrocchio please let me know if you also need a design of the engagement meter pop up we discussed for the home page.

**Comment by ctmcintyre** [comment]
Nice!

> laurencullen <mailto:notifications@github.com>
> August 14, 2015 at 10:57 AM
>
> @rrocchio <https://github.com/rrocchio> please let me know if you also
> need a design of the engagement meter pop up we discussed for the home
> page.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/200#issuecomment-131195121>.
>
> RoseRocchio <mailto:notifications@github.com>
> August 14, 2015 at 7:25 AM
>
> @laurencullen <https://github.com/laurencullen> - we need a page that
> explains how the engagement meter works:
>
> Something that introduces it with content like this:
>
> And then an area like this:
>
> *How to get points: *
>
> 1) Setting up a Profile ADD 2 points; DELETE a profile SUBTRACT 2 points
> 2) Create a project ADD 5 points ; DELETE a project SUBTRACT 5 points
> 4) Like a project ADD 1 point
> 5) Comment on a project - ADD 2 points
> 3) Create an Idea ADD 3 points; DELETE an Idea SUBTRACT 3 points
> 4) Like an Idea ADD 1 point
> 5) Comment on an idea - ADD 2 points
> 6) Create a Group ADD 3 points ( DELETE a group - can only be done -
> if you are the only person in the group)
> 7) Join a Group ADD 1 point; LEAVE a group SUBTRACT 1 point
> 8) Awarding a GOLD Sautter Award for your campus = 50 points for you
> and your campus
> 9) Awarding a SILVER Sautter Award for your campus = 25 points for you
> and your campus
> 10) Removing an award subtracts those points
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/200>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by ctrance** [comment]
@krozett - Where can I access the Engagement Meter page?

**Comment by krozett** [comment]
@ctrance Click on the "Engagement Meter" heading on the main page

**Comment by ctrance** [comment]
@krozett - On Lauren's design there's a meter icon right next to the "Engagement Meter" title.

**Comment by ctrance** [comment]
fixed
