### ISSUE TITLE
Badge Assignment

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#202]
Right now, it appears you don't get an option to assign a badge to someone from their profile if they don't already have a badge. Should probably alter the condition that hides that section to leave room for a badge assigner to still assign a badge.

**Comment by krozett** [comment]
Will be fixed once pull #214 goes through

**Comment by ctrance** [comment]
@krozett - Please add instructions how to test this. Thanks!

**Comment by krozett** [comment]
@ctrance You can do this from a user's profile page. There is a "Give badge/award" button in the top left area. But you need to have admin rights first, or be assigned as a badge giver by someone who does own a badge.

**Comment by ctrance** [comment]
@krozett - I can assign badges now, but the app let's me give the same badge to the same person. 
![1](https://cloud.githubusercontent.com/assets/1034174/10798807/9ac8714c-7d66-11e5-8a2f-56c14d7324d7.PNG)

**Comment by joshuaselsky** [comment]
Closing in favor of #281.
