### ISSUE TITLE
Add a Heading to the "Ideas" Detail Page 

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#207]
Add the Ideas Logo and also the Header "Idea Details" to the top of the Ideas Detail page

@krozett  - this is important to give people on the site a sense of where they are - providing good navigation

**Comment by ctrance** [comment]
I still don't see the ideas logo and the header "Idea Details" on ideas detail page.
![capture](https://cloud.githubusercontent.com/assets/1034174/10980429/c7d088ae-83b6-11e5-98bf-4fd84fa65544.PNG)

**Comment by ctrance** [comment]
@joshuaselsky and @shaun965 - Header should be "Idea Details" not "Ideas"

**Comment by ctrance** [comment]
fixed
