### ISSUE TITLE
Tidying up the Project Page

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#208]
@krozett  - this is just what we discussed in the meeting - but I wanted to put it into a ticket:

1) Lets move the top trending project grid underneath the prose on the projects page
2) Lets move the engagement meeter up on the right
3) Add the Word "Project" to the Engagement Meter Label 
4) Take the Labs and the Digital Library off the Engagement Meter display

**Comment by krozett** [comment]
Made the same changes to the Ideas page, for consistency.

**Comment by ctrance** [comment]
fixed
