### ISSUE TITLE
Top 5 Projects by Vote - for Top of Project Page and the HOME page.... (add the VOTES)

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#211]
![image](https://cloud.githubusercontent.com/assets/718820/9286275/e28809ea-42a4-11e5-9fd6-11120241b52d.png)

**Comment by rrocchio** [comment]
@ebollens  - if we can make this happen - then that would be GREAT - I think that the Green +1 is to indicate if logged in whether you voted for something - I think....

**Comment by rrocchio** [comment]
Connect to #31

**Comment by rrocchio** [comment]
Lauren - just change the title... here to be "Top 5 Projects by Vote" - then please assign to Keith

@krozett  - PLEASE go and get the votes - to display on these lists - on the home page, the ideas page and the projects page

**Comment by laurencullen** [comment]
@rrocchio @krozett here are the new proofs for the home page, projects page, and ideas page.

For home page, titles will remain the same but more projects and more ideas links are added. Total project numbers and total votes are displayed in bubbles. Also, added the new section above wave entitled What's New at NEXT.

![ucnext home page 10 16-01](https://cloud.githubusercontent.com/assets/13141571/10553883/4ed26fce-7413-11e5-994c-ec29db3d2784.jpg)


For the projects page, the title of trending projects changed to Top 5 Projects by Vote. In addition, there are engagement bubbles that can be added.

![projects10 16](https://cloud.githubusercontent.com/assets/13141571/10553920/83b8e5b0-7413-11e5-95cf-126d8036e343.jpg)


For the ideas page, the title of trending ideas changed to Top 5 Ideas by Vote. In addition, there are engagement bubbles that can be added.

![ideasloggedin10 16-02](https://cloud.githubusercontent.com/assets/13141571/10553953/b9b34f48-7413-11e5-8503-8ea73ba768bd.jpg)

Please let me kmow if you have any questions or revisions. Thanks!

**Comment by laurencullen** [comment]
@krozett here are the three types of bubbles. Please let me know if you need anything else.

![bubble-lg](https://cloud.githubusercontent.com/assets/13141571/10702852/01bf6bce-7981-11e5-86d6-f41fc1f7696d.png)
![bubble-sm](https://cloud.githubusercontent.com/assets/13141571/10702853/01c1fd08-7981-11e5-8244-042ce4117522.png)
![bubble-med](https://cloud.githubusercontent.com/assets/13141571/10702857/0a543616-7981-11e5-83a4-87a488e6838c.png)

**Comment by krozett** [comment]
Aside from two bugs, #316 and #331, this feature is complete.
