### ISSUE TITLE
Auto-give badges to users who join certain groups

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#215]
Let a badge have any number of badge groups, and if a user joins one of those groups (could be open or invite-only) then they automatically get the badge.

**Comment by ctrance** [comment]
@krozett - I need instructions on how to test this. I just joined a group and it shows on "My Group" page, no badge showing. Am I looking at the right place? Sorry I'm just new with UCNext project.
![capture](https://cloud.githubusercontent.com/assets/1034174/9856870/281c79f2-5acc-11e5-897d-38b51a840c65.PNG)

**Comment by krozett** [comment]
@ctrance Here's how you can test this ticket:
1. Create a new group. Do not join it yet.
2. Create a new badge for testing (you MUST be an admin to create a new badge).
3. While on the badge editing form, look for a Badge Group input which lists all groups. Select the group you created on step 1.
4. Join the group you created in step 1. You should now have the new badge. You can see it by going to your profile page, and click manage badges/awards. (By default the new badge is not seen on your profile, but you can "showcase it" if you want.)

**Comment by ctrance** [comment]
@krozett - I don't have admin account, can you add that role to "ctrance"?

**Comment by krozett** [comment]
@ctrance Unfortunately I am not able to log in to any of my admin accounts, so I cannot make you one. (We really need a password reset...)

@rrocchio (or someone else who has local admin), could you make ctrance an admin?

**Comment by ctrance** [comment]
fixed
