### ISSUE TITLE
Shib errors from UCSC

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#222]
Two folks from UCSC have reported the following error:
{"status":400,"error":"bad_request","error_message":"Client authentication failed"}

**Comment by ctmcintyre** [comment]
This is intermittent.  Eric - Can you look into this?

**Comment by joshuaselsky** [comment]
Closing as we were finally able to recreate it and solve the problem as documented in https://github.com/universityofcalifornia/NeXt/issues/260.
