### ISSUE TITLE
Make Projects more actionable

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#225]
Show off the "supporters" and the "would participate" more clearly - in the card view and the details

**Comment by laurencullen** [comment]
@krozett  and @rrocchio here are proofs of the logged in projects page and project details page. These proofs include increasing the visibility of the supporters and would participate, adding the project search, adding tags, right aligning school names on engagement meter, etc. Please let me know if you need anything else or any revisions. Thanks!

![projects-03](https://cloud.githubusercontent.com/assets/13141571/9558776/9f1181be-4d9e-11e5-9975-db414b78a622.jpg)
![projects-04](https://cloud.githubusercontent.com/assets/13141571/9558780/b8971d74-4d9e-11e5-952b-a10b5edc4286.jpg)

**Comment by joshuaselsky** [comment]
The last remaining items to take care of for Projects and Ideas for this issue are:

* Add the bubbles containing the number of supporters and participants.
* Fix the broken "See More" link by showing a scrolling box (pop-up on mobile) or a separate page containing the people list. This is dependent on effort for the former.

**Comment by ctrance** [comment]
@joshuaselsky @krozett - The only issue I have are cosmetics, please see below:
1. Lauren's design has the bubbles in lighter shade of yellow than the current version and the numbers are blue not black.
2. I think we should reduce the indentation for Trending Projects/Ideas, see phone view below.
![img_9927 1](https://cloud.githubusercontent.com/assets/1034174/12487174/ea8ea5d8-c01a-11e5-9980-416d1607648b.PNG)

**Comment by joshuaselsky** [comment]
* @laurencullen will provide the updated bubble image and the font info
* @krozett will update the indentation to match the home page 
* later on we will revisit with the full-on design review

**Comment by laurencullen** [comment]
@krozett this is what I have for text in yellow bubbles:
  font-family : Open Sans Condensed;
  font-weight : bold;
  font-size : 14px;
  text-transform : uppercase;
  color : #1E4B87;
  text-shadow : 0.77px 0.77px 0px rgba(153, 153, 153, 0.75);

**Comment by laurencullen** [comment]
@krozett attached are larger bubbles. Please let me know if you need anything else. Thanks!

![bubble](https://cloud.githubusercontent.com/assets/13141571/13304931/b05fc678-db0c-11e5-8543-79d42ab41915.png)
![bubbledown](https://cloud.githubusercontent.com/assets/13141571/13304930/b027d236-db0c-11e5-9d7b-328a6348f11a.png)

**Comment by krozett** [comment]
@laurencullen could you also attach a newer version of the larger bubble with the arrow on the left side? We use this image in the total projects/ideas bubbles on the index page.

**Comment by laurencullen** [comment]
@krozett please see attached bubble at a larger size. if you need anything else please let me know.

![projects_left bubble lg](https://cloud.githubusercontent.com/assets/13141571/13446392/14114434-dfc8-11e5-9526-233cbeb65d93.png)

**Comment by krozett** [comment]
@laurencullen actually what I am looking for is this wide bubble:
https://ucnext.org/images/bubbles/right_big.png

**Comment by laurencullen** [comment]
@krozett what size do you need?

**Comment by laurencullen** [comment]
@krozett here it is at 143px wide, let me know if you need something else.

![leftbubblelong](https://cloud.githubusercontent.com/assets/13141571/13446664/30e2420a-dfca-11e5-9706-2b9547e5c8a7.png)

**Comment by krozett** [comment]
@laurencullen thanks!

**Comment by ctrance** [comment]
fixed
