### ISSUE TITLE
Use Mandril to "pull" users into more awareness about their ideas and projects

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#226]
Increase User's connection to UC Next and their Collaborative Engagement efforts:

1) Notify a user when they receive a Badge
2) Notify a user when they are invited to a group
3) Notify a user when their idea/project rises to the top 5 

(rose to finish)

**Comment by krozett** [comment]
We will definitely need a way to let users opt-out of these emails. It might be worth having an in-site notification system as well.

As far as Mandrill goes, it costs money. However, I researched Amazon's offerings and found that they let you send 62k emails per month for EC2 users! See more here:
http://aws.amazon.com/ses/

**Comment by rrocchio** [comment]
SES:  Sending an Email Through the Amazon SES SMTP Interface Programmatically

You can send an email through the Amazon SES SMTP interface by using an SMTP-enabled programming language. You provide the Amazon SES SMTP hostname and port number along with your SMTP credentials and then use the programming language's generic SMTP functions to send the email.

Review Sending an Email Through Amazon SES Using SMTP and then select one of the following tutorials:

    Sending an Email Through the Amazon SES SMTP Interface with C#

    Sending an Email Through the Amazon SES SMTP Interface with Java

**Comment by krozett** [comment]
I'll be talking to Nick Urrea next Monday since he's the one who manages AWS for us. We should just be able to get the SMTP credentials and not have to install the full AWS API.

**Comment by krozett** [comment]
Once this is deployed, we still need to get out of the SES sandbox mode. Until that happens, we are under certain limitations:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

* You can only send mail to the Amazon SES mailbox simulator and to verified email addresses and domains.
* You can only send mail from verified email addresses and domains.
* You can send a maximum of 200 messages per 24-hour period.
* Amazon SES can accept a maximum of one message from your account per second.

With Nick's help, I have verified the ucnext.org domain as well as my own email address for testing. This means emails will only get to you if you are me, or your address ends in @ucnext.org.

This shouldn't stop us from deploying, as sending to unverified email addresses won't cause any visible errors. However, we need to get out of sandbox mode for the emails to actually go through. We'll be doing that next Friday (10/23).

**Comment by krozett** [comment]
We have been out of the sandbox for awhile and the email system is fully functional.
