### ISSUE TITLE
[server] Shibboleth IdP Setups (Overview)

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#23]
* Get permissions from IdPs on all campuses to release `eduPersonPrincipalName`, `givenName`, `cn` and `mail`
* Configure shibboleth2.xml in [chef-NeXt](https://github.com/universityofcalifornia/chef-NeXt) for federated Shibboleth

**Comment by jurowski** [comment]
!!! do also build in the ability to have local database authentication ... for devs especially but will also be useful for external users to create industry events

**Comment by jurowski** [comment]
(don't actually let external users create accounts except through a back-door URL0

**Comment by jurowski** [comment]
SJ: going to break into multiple tasks

**Comment by joshuaselsky** [comment]
Closing because we have successfully integrated with a few different UCs using UC Trust.
