### ISSUE TITLE
Show all organizations on engagement meter

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#234]
Some of the labs have really long names, so I am resorting to use the short names for now. We need to come up with a modified design if we want things like "Los Alamos National Laboratory" to fit next to their bar on the meter.

**Comment by krozett** [comment]
The engagement_meter_display column can be removed completely since all rows now have it set to 1. I want to make sure we are sticking with this behavior before I drop that column.

**Comment by ctrance** [comment]
fixed
