### ISSUE TITLE
Please create golden and silver sautter awards for all the years

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#236]
@laurencullen  - please create the golden and silver awards for 2001 - 2013...

Thanks!

**Comment by laurencullen** [comment]
@rrocchio @krozett here are all the Sautter badges. Please let me know if you need anything else.

![sautter-gold2001](https://cloud.githubusercontent.com/assets/13141571/10002265/0e834716-605b-11e5-871a-d6e86b96704d.png)
![sautter-gold2002](https://cloud.githubusercontent.com/assets/13141571/10002264/0e82f7c0-605b-11e5-9894-e0b82644a4fe.png)
![sautter-gold2003](https://cloud.githubusercontent.com/assets/13141571/10002266/0e8511ea-605b-11e5-97ea-70c4ed70f768.png)
![sautter-gold2004](https://cloud.githubusercontent.com/assets/13141571/10002267/0e865fbe-605b-11e5-8db4-192507ac9694.png)
![sautter-gold2005](https://cloud.githubusercontent.com/assets/13141571/10002269/0e885e2c-605b-11e5-81e1-fb4e805b91d5.png)
![sautter-gold2006](https://cloud.githubusercontent.com/assets/13141571/10002268/0e867c10-605b-11e5-909a-84e4e2d4e855.png)
![sautter-gold2007](https://cloud.githubusercontent.com/assets/13141571/10002270/0e946438-605b-11e5-95b7-81e2271abba5.png)
![sautter-gold2008](https://cloud.githubusercontent.com/assets/13141571/10002271/0e94eb38-605b-11e5-997c-10c98944d8b5.png)
![sautter-gold2009](https://cloud.githubusercontent.com/assets/13141571/10002272/0e9681e6-605b-11e5-892a-11e0992156f2.png)
![sautter-gold2010](https://cloud.githubusercontent.com/assets/13141571/10002273/0e9888e2-605b-11e5-9b65-3fcf0c7b08c8.png)
![sautter-gold2011](https://cloud.githubusercontent.com/assets/13141571/10002275/0e9eec6e-605b-11e5-9f26-40cde8d59db9.png)
![sautter-gold2012](https://cloud.githubusercontent.com/assets/13141571/10002274/0e9a756c-605b-11e5-87c1-8ac62cf0c0a2.png)
![sautter-gold2013](https://cloud.githubusercontent.com/assets/13141571/10002276/0ea5d68c-605b-11e5-8e43-af4427fb3566.png)
![sautter-gold2014](https://cloud.githubusercontent.com/assets/13141571/10002277/0ea8fd44-605b-11e5-89b7-7aa8b96abd1e.png)
![sautter-gold2015](https://cloud.githubusercontent.com/assets/13141571/10002278/0eab531e-605b-11e5-89ac-5f5e1dd2ee51.png)
![sautter-silver2001](https://cloud.githubusercontent.com/assets/13141571/10002280/0ead3d50-605b-11e5-8933-5b2b28dd9ae7.png)
![sautter-silver2002](https://cloud.githubusercontent.com/assets/13141571/10002279/0eac5afc-605b-11e5-9e43-350c73fa77bb.png)
![sautter-silver2003](https://cloud.githubusercontent.com/assets/13141571/10002281/0eb2c6da-605b-11e5-80c6-b65d130bb026.png)
![sautter-silver2004](https://cloud.githubusercontent.com/assets/13141571/10002285/0ec04030-605b-11e5-98c8-b349293e1a2e.png)
![sautter-silver2005](https://cloud.githubusercontent.com/assets/13141571/10002286/0ec04800-605b-11e5-9dfb-801759115445.png)
![sautter-silver2006](https://cloud.githubusercontent.com/assets/13141571/10002282/0ebe764c-605b-11e5-8cc5-9ae1ca80295e.png)
![sautter-silver2007](https://cloud.githubusercontent.com/assets/13141571/10002284/0ebf9310-605b-11e5-8177-6e27dbde5d84.png)
![sautter-silver2008](https://cloud.githubusercontent.com/assets/13141571/10002283/0ebf4888-605b-11e5-811a-49c2046f90b9.png)
![sautter-silver2009](https://cloud.githubusercontent.com/assets/13141571/10002287/0ec4de56-605b-11e5-95ef-de9a3bb7ddd5.png)
![sautter-silver2010](https://cloud.githubusercontent.com/assets/13141571/10002288/0ecfaa8e-605b-11e5-8ea9-4f4f6739cf52.png)
![sautter-silver2011](https://cloud.githubusercontent.com/assets/13141571/10002291/0ed28574-605b-11e5-91a5-92c59f10e9a6.png)
![sautter-silver2012](https://cloud.githubusercontent.com/assets/13141571/10002289/0ed089cc-605b-11e5-8359-ccccd8ddf15d.png)
![sautter-silver2013](https://cloud.githubusercontent.com/assets/13141571/10002292/0ed32dda-605b-11e5-8378-21bd4a8e16f0.png)
![sautter-silver2014](https://cloud.githubusercontent.com/assets/13141571/10002290/0ed209aa-605b-11e5-8511-3069a3015678.png)
![sautter-silver2015](https://cloud.githubusercontent.com/assets/13141571/10002293/0ed76904-605b-11e5-93e8-2abacfb75132.png)

**Comment by laurencullen** [comment]
New badges have been created for Honorable Mention 2008-2015:

![sautter badges hm-40](https://cloud.githubusercontent.com/assets/13141571/10955939/3dd920b6-830c-11e5-9dad-22988e688fea.png)
![sautter badges hm-39](https://cloud.githubusercontent.com/assets/13141571/10955935/3dd67f28-830c-11e5-9752-0c1c6b08435d.png)
![sautter badges hm-38](https://cloud.githubusercontent.com/assets/13141571/10955936/3dd779be-830c-11e5-859a-39af8c17be4a.png)
![sautter badges hm-37](https://cloud.githubusercontent.com/assets/13141571/10955937/3dd85852-830c-11e5-8726-86cf827bccfb.png)
![sautter badges hm-36](https://cloud.githubusercontent.com/assets/13141571/10955938/3dd8a7bc-830c-11e5-9191-f898b303581c.png)
![sautter badges hm-35](https://cloud.githubusercontent.com/assets/13141571/10955940/3ddb983c-830c-11e5-8eb8-92e738dcc98b.png)
![sautter badges hm-34](https://cloud.githubusercontent.com/assets/13141571/10955941/3de68c10-830c-11e5-9aa8-d07649b56887.png)
![sautter badges hm-33](https://cloud.githubusercontent.com/assets/13141571/10955942/3de71aea-830c-11e5-9b00-032d404b6a31.png)

**Comment by laurencullen** [comment]
I've added all badges to UCNext badges area. Please let me know if there is anything else needed on this issue.
