### ISSUE TITLE
Make the federated Shibboleth Login 1) include all locations 2) look better

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#240]
Make the federated Shibboleth Login work across all locations 

 1) have the dropdown include all locations
 2) Chase down the integration elements for every campus/location - 
        a) Some are using InCommon
        b) Some may not be
 3) Get it styled to look better

Action items:  Rose to reach out to Alan @ UCSD and Charles...

**Comment by laurencullen** [comment]
Attached is a proof of the styling of the login. It is all coded in html and css. Please let me know if there are any changes.

![screen shot 2015-09-29 at 4 01 47 pm](https://cloud.githubusercontent.com/assets/13141571/10206282/ec6b5fe8-677a-11e5-8916-6aa768f34b39.png)

**Comment by joshuaselsky** [comment]
The Shibboleth Discovery Service files are now in a [GH repo](https://github.com/universityofcalifornia/shib-ds-NeXt).

**Comment by joshuaselsky** [comment]
Closing because this has been implemented. The UI could still use some help, but we can open a new issue if and when we decide to do that.
