### ISSUE TITLE
Shib Issues - URGENT

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#244]
Looking at the transaction logs, it appears that all campuses are able to log into UC NEXT (but we/I may be interpreting those logs incorrectly).  That said, there are still issues with the UCTrust/Shib login mechanism.  Here's a report I rec'd from someone from UCSB:  

So I gave it a shot. After being redirected to UCSB's SSO page and entering my credentials I got redirected back to ucnext.org - just as expected. However, it doesn't appear that I'm actually logged on. The "Login" link is still in the upper-righthand corner and there's no "Hi Richard" or anything else indicated that the site knows who I am. Also there is no links for adding/modifying data.

**Comment by stevenolen** [comment]
I'm able to log in with UCLA account without any trouble (I see "My Account" at the top after getting redirected back).  Here's the shib attributes in use on the production box: https://github.com/universityofcalifornia/chef-NeXt/blob/master/cookbooks/shibboleth-sp/files/default/ucnext-shibboleth2.xml. If anything needs to be changed, feel free to let me know -- but other than that we haven't touched this config in a month or two..

**Comment by ctmcintyre** [comment]
Yes, and I can login from UCSC with my Shib account.  What I'm confused
about is why are other campuses having trouble?  From the
transaction.log, it /appears/ all campuses have logged in.  Is that a
correction observation?  If so, we're still not out of the wood since
other campuses (UCSB, UCB, UCI?) are still having issues using their
local campus auth.



> Steve Nolen <mailto:notifications@github.com>
> September 15, 2015 at 12:15 PM
>
> I'm able to log in with UCLA account without any trouble (I see "My
> Account" at the top after getting redirected back). Here's the shib
> attributes in use on the production box:
> https://github.com/universityofcalifornia/chef-NeXt/blob/master/cookbooks/shibboleth-sp/files/default/ucnext-shibboleth2.xml.
> If anything needs to be changed, feel free to let me know -- but other
> than that we haven't touched this config in a month or two..
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/244#issuecomment-140505915>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by stevenolen** [comment]
The transaction logs may only imply that someone has *tried* to log in? I don't know my way around the shibd daemon, so I'm not sure what it is that it logs (the email conversation we had previously contained the regex I used, in hopes that if I were grepping too generally, someone could correct me).  

I don't know much about the application stack here, so mostly just making best guess: the config files in use are traversing the actual sp -> idp -> shib-oauth-bridge interaction successfully given that we can log in from UCLA and UCSC. With that in mind, I can only imagine the problem would lie in one of these places: 

  *  shib attribute issues for those campuses (the file I mentioned above is directly implemented with what I received from allan). not sure if this is even possible, but I'm definitely not the shib domain expert :)
  * a bug in the shib-oauth-bridge handoff in certain cases?
  * some sort of campus mis-configuration? Again not really sure if this is a possibility.
  * application layer issue?

**Comment by ctmcintyre** [comment]
Yes, not easy!

Who do we need to confab on this to move it forward?  I'm thinking you,
Keith, Eric and me?

> Steve Nolen <mailto:notifications@github.com>
> September 15, 2015 at 12:41 PM
>
> The transaction logs may only imply that someone has /tried/ to log
> in? I don't know my way around the shibd daemon, so I'm not sure what
> it is that it logs (the email conversation we had previously contained
> the regex I used, in hopes that if I were grepping too generally,
> someone could correct me).
>
> I don't know much about the application stack here, so mostly just
> making best guess: the config files in use are traversing the actual
> sp -> idp -> shib-oauth-bridge interaction successfully given that we
> can log in from UCLA and UCSC. With that in mind, I can only imagine
> the problem would lie in one of these places:
>
>   * shib attribute issues for those campuses (the file I mentioned
>     above is directly implemented with what I received from allan).
>     not sure if this is even possible, but I'm definitely not the shib
>     domain expert :)
>   * a bug in the shib-oauth-bridge handoff in certain cases?
>   * some sort of campus mis-configuration? Again not really sure if
>     this is a possibility.
>   * application layer issue?
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/244#issuecomment-140515026>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by stevenolen** [comment]
@joshuaselsky since our meeting, have the logs returned anything useful here?

**Comment by joshuaselsky** [comment]
I think this issue is outdated. Long story short is that not all campuses are wired into UC Trust yet. @ctmcintyre can this be closed?

**Comment by ctmcintyre** [comment]
Closing!
