### ISSUE TITLE
Social Network pages

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#249]
@rrocchio @ctmcintyre 
The UC Next username is already taken on both Twitter and Facebook:
https://twitter.com/ucnext
https://www.facebook.com/uc.next

Anyone have thoughts on alternative usernames??

Also, to create a FB fan page, I think that it must be associated with a regular page. @rrocchio how is this usually done? Do I create a new FB account under my work email, use my personal FB then add other admins, or is there an existing department account that is used? Please let me know. Thanks!

**Comment by laurencullen** [comment]
@rrocchio @ctmcintyre The Twitter account is now set up! https://twitter.com/UCNextNews

@krozett It can be linked on the website now.

Please let me know any changes you would like to the page or any announcements. Also, I followed a few of Twitter's suggestions.

Facebook page to come soon!

**Comment by ctmcintyre** [comment]
Excellent!

> Lauren Cullen <mailto:notifications@github.com>
> October 21, 2015 at 3:05 PM
>
> @rrocchio <https://github.com/rrocchio> @ctmcintyre
> <https://github.com/ctmcintyre> The Twitter account is now set up!
> https://twitter.com/UCNextNews
>
> @krozett <https://github.com/krozett> It can be linked on the website now.
>
> Please let me know any changes you would like to the page or any
> announcements. Also, I followed a few of Twitter's suggestions.
>
> Facebook page to come soon!
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/249#issuecomment-150038270>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre @rrocchio @krozett The Facebook page is now up: https://www.facebook.com/UCNextConnect

The page is labeled as a company, organization or institution in the category of computers/technology. In this area, they also have the category of education, so please let me know which you prefer because I can easily change it.

Also, if anyone wants to be an admin with their existing FB account, please let me know because I can add you. The email ucnext@ucsc.edu never sent a confirmation reply, so I have both social network accounts connected to lcullen@oit.ucla.edu.

@krozett FB page can be linked to the website now. Thanks!

**Comment by laurencullen** [comment]
@krozett Please link FB icon to: https://www.facebook.com/UCNextConnect
and please link Twitter icon to: https://twitter.com/UCNextNews

These are the last two items for this issue. Thanks!

**Comment by ctrance** [comment]
fixed
