### ISSUE TITLE
[login] Make Shibboleth Login prominent and diminish local login (even disable for Shib campuses)

### ISSUE THREAD

**Issue by pmeads** [universityofcalifornia/NeXt#250]
The local login was only a stopgap until Shibboleth was enabled for all campuses. For campuses that have Shib enabled, we want to ensure that they use it and do not create local accounts. 

The focus of the login page should be the Shib login. Under the Shib login, a diminished local login box should remain for campuses that do not have Shib enabled yet. 

This is mostly design related, however we should also implement code that does not allow local login for campuses where Shibboleth is enabled.

**Comment by pmeads** [comment]
Assigning to @laurencullen for the design portion

**Comment by laurencullen** [comment]
Here's a rough draft design for the login page. Please let me know any changes and if you need anything else.

![loginpage-01](https://cloud.githubusercontent.com/assets/13141571/10380539/4ae9fd6e-6dc9-11e5-897d-78fc0544a1a2.jpg)

**Comment by pmeads** [comment]
Looks good Lauren! I'm thinking the button LOG IN WITH CAMPUS ACCOUNT should have something to draw your eye to it. 

@rrocchio  and @krozett, when a user clicks "Register" under Local Login, in the auth/local/registration/new view, we could add a campus picklist. If a new user chooses one of the campuses enabled for Shib from the picklist, redirect them to the Shib page via auth_oauth2_launch_url(:shibboleth) with a message indicating that they can login with their campus shibboleth account.

**Comment by laurencullen** [comment]
@pmeads As ideas for something to draw the user's eye to the log in with campus account button, we could add the wave icon (from header top right next to the login there) or we could add the UC logo. Please let me know your thoughts.

**Comment by pmeads** [comment]
Maybe if there was a subtle gold outline around the button? even something like having the words inside the button a yellow or gold color. What do you think @rrocchio?

**Comment by laurencullen** [comment]
@pmeads @rrocchio here are comps of the gold outline and text as well as a version with a gold button:

![loginpageorgbtn-01](https://cloud.githubusercontent.com/assets/13141571/10438670/dd3203f6-70e9-11e5-8dfc-80d6707c9cd6.jpg)
![loginpageorgtxt-01](https://cloud.githubusercontent.com/assets/13141571/10438671/dd435822-70e9-11e5-9102-10b939417816.jpg)

Please let me know any feedback.

**Comment by pmeads** [comment]
The second one looks great to me. It leads your eye to the campus login and yet doesn't stand out too much. My vote goes to option 2.

**Comment by ctmcintyre** [comment]
Same.  Option 2

> Philip Meads <mailto:notifications@github.com>
> October 12, 2015 at 2:21 PM
>
> The second one looks great to me. It leads your eye to the campus
> login and yet doesn't stand out too much. My vote goes to option 2.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/250#issuecomment-147526035>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by joshuaselsky** [comment]
Please verify the color scheme of the updated content when testing this.

**Comment by ctrance** [comment]
@joshuaselsky - I don't see the campus login on the test site.

**Comment by joshuaselsky** [comment]
@ctrance on the staging machine, I think we should only enable local login for now because Shibboleth is not set up for this environment. The best way to test this is once it is in production.

**Comment by ctrance** [comment]
@joshuaselsky - Sounds great! Please let me know once prod is updated with this fix.

**Comment by ctrance** [comment]
Lauren's mock up has gold border around the "login with campus account" button, that's missing...
![capture](https://cloud.githubusercontent.com/assets/1034174/11944238/8462bd00-a7f9-11e5-88f9-e9c8c6fad9bb.PNG)

**Comment by ctrance** [comment]
@shaun965 - The shibb login button has gold border now, thanks! Can you also fix its position on tablet view, it's not centered. See below...
![screenshot_20160107-081641](https://cloud.githubusercontent.com/assets/1034174/12175451/2de09882-b517-11e5-9df4-c7eb1f6bcc43.png)

**Comment by ctrance** [comment]
fixed
