### ISSUE TITLE
email invites scheduler throws error on startup

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#253]
It appears that this [line](https://github.com/universityofcalifornia/NeXt/blob/master/app/mailers/event_notifier.rb#L7) is the culprit. 

Here's an extract from the log.

    { 22706240 rufus-scheduler intercepted an error:
      22706240   job:
      22706240     Rufus::Scheduler::InJob "2m" {:no_error=>true, :_t=>120.0}
      22706240   error:
      22706240     22706240
      22706240     NoMethodError
      22706240     undefined method `name' for nil:NilClass
      22706240       /var/www/app/app/mailers/event_notifier.rb:7:in `notify_invite'

**Comment by krozett** [comment]
I may have messed this up, since I was working in the mailers area. Didn't think I committed any of my incomplete code, but I'll check it out.

**Comment by krozett** [comment]
Well, now I know it wasn't me, but I'm still not sure how a nil event got in there in the first place. Put in a kludgey fix to skip the invite if the event is nil.

**Comment by ctrance** [comment]
@joshuaselsky and @krozett How do I get to email invite page?

**Comment by krozett** [comment]
This can be re-tested once the email system is fixed. No longer needs me.

**Comment by ctrance** [comment]
Please let me know once the email system is fixed, so I can re-test.

**Comment by joshuaselsky** [comment]
Since this is related to errors showing up in the logs, I will re-test.

**Comment by joshuaselsky** [comment]
Closing because this error message is no longer occurring on the new staging server!

**Comment by ctrance** [comment]
@joshuaselsky - The event email still not sending email to address listed on the "Invite List". Should I re-open this ticket or just create a new one?

**Comment by joshuaselsky** [comment]
Definitely a new issue! Thanks!
