### ISSUE TITLE
Add people fields to edit project page

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#254]
Let's add the following fields to the Edit Project page:
1. Project Sponsor
2. Project Manager (defaults to logged in user, but is editable)

**Comment by shaun965** [comment]
@joshuaselsky Do we want to create separate tables for these? Are sponsor and managers going to be users?

**Comment by shaun965** [comment]
or should I add these in boolean underneath the project_roles table

**Comment by joshuaselsky** [comment]
* Project sponsor should be a string that will be a persons name. This person will not necessarily be a NeXt user.
* The project manager should be the user name of the logged in user, but the value can be changed (as specified in the initial comment on this issue).

Both of these fields can be added to the `projects` table.

**Comment by ctrance** [comment]
I can't proceed testing, getting error page when going to Projects page
![capture](https://cloud.githubusercontent.com/assets/1034174/11790614/9371e544-a251-11e5-97b3-03a86acbc119.PNG)

**Comment by shaun965** [comment]
This page seems to be working on my computer too while signed out, signed in. Is it because maybe you are an admin and there is a bug for admin?

**Comment by krozett** [comment]
Pull #329 will fix the projects page error.

**Comment by shaun965** [comment]
Thanks so much Keith, it appeared I failed to add that file to my commit.

**Comment by krozett** [comment]
:bowtie:

**Comment by ctrance** [comment]
On create project mode, the "Project Manager" field does not default to logged in user.
![capture](https://cloud.githubusercontent.com/assets/1034174/11814408/700f8156-a2fb-11e5-9b40-218fc65185bb.PNG)

**Comment by ctrance** [comment]
fixed
