### ISSUE TITLE
Better design for notification emails

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#257]
It would probably be good to have the NeXt logo, and some kind of header and footer. What I did for #226 is very basic.

**Comment by laurencullen** [comment]
@krozett @rrocchio Here is a screen shot of a possible design (also emailed). Only added image of badge and UC Next logo. Please let me know any changes.

![screen shot 2015-10-23 at 2 03 22 pm](https://cloud.githubusercontent.com/assets/13141571/10704926/0488c0f4-798f-11e5-9681-f329505e1484.png)

Here is logo at this size:
![email-logo](https://cloud.githubusercontent.com/assets/13141571/10704945/1f016148-798f-11e5-8e25-e13f76fe82a5.png)

Here is example badge at this size:
![testbadge](https://cloud.githubusercontent.com/assets/13141571/10704955/2a81c92c-798f-11e5-9d89-5cd72a7822cd.png)

**Comment by ctrance** [comment]
@krozett Email looks good but "badges page" and "profile preferences page" links are not working. I'll close this and create new issue for the link error.
![capture](https://cloud.githubusercontent.com/assets/1034174/11877871/dd90f1e0-a4a6-11e5-9325-761273559d0a.PNG)
