### ISSUE TITLE
www.ucnext.org gets 400 when using campus auth

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#260]
Reported by Nathan Sheldon (UCSF): Users MUST go to the https://ucnext.org web site (without the “www”) before going through the login process.  Going to https://www.ucnext.org site looks like it’s going to work, but logging in causes the UCNext.org server to return a 400 “bad request” error.  This seems to be a UCNext site configuration issue though, not a Shibboleth one.

Error: {"status":400,"error":"bad_request","error_message":"Client authentication failed"}

I've duplicated this behavior.  THIS might be the issue that some folks that been seeing!

**Comment by ctmcintyre** [comment]
Josh - I'm assigning to you.  I'm not sure who should work on this.

**Comment by joshuaselsky** [comment]
I was just able to recreate at UCLA and received the infamous

`{"status":400,"error":"bad_request","error_message":"Client authentication failed"}` 

This should just be a matter of config like you said.

**Comment by joshuaselsky** [comment]
@ctmcintyre can you try it out again. It should be working now.

**Comment by ctmcintyre** [comment]
Did you just redirect www.ucnext.org to ucnext.org?

> Joshua Selsky <mailto:notifications@github.com>
> October 21, 2015 at 3:13 PM
>
> @ctmcintyre <https://github.com/ctmcintyre> can you try it out again.
> It should be working now.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/260#issuecomment-150039705>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by joshuaselsky** [comment]
Yep.

**Comment by ctmcintyre** [comment]
Perfect

Works now.

I bet that was the ghost issue with shib logins... 

> Joshua Selsky <mailto:notifications@github.com>
> October 21, 2015 at 4:39 PM
>
> Yep.
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/260#issuecomment-150054753>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by joshuaselsky** [comment]
I think so, too. And thank you @stevenolen!

**Comment by stevenolen** [comment]
of course! @joshuaselsky mentioned this to me and I felt like it made the most sense to implement this way: the shib bridge needs to uniquely identify the clients connecting to it and redirect back -- but allowing arbitrary access from both `ucnext.org` and `www.ucnext.org` technically means the bridge has to have two clients set up for this single host.  

It is a pretty common way of handling this -- for ex. `www.twitter.com` redirects you to `twitter.com` and (interestingly) `facebook.com` redirects to you to `www.facebook.com`.

**Comment by stevenolen** [comment]
The redirect is done in nginx, and it's in my task list to reflect those changes in chef, see: https://github.com/universityofcalifornia/chef-NeXt/issues/2
