### ISSUE TITLE
In the Groups Details page, the Membership type does not seem to be saving

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#261]
In the Groups Details page, the Membership type does not seem to be saving - when I try to set it to "invite-only" it doesn't work.

**Comment by joshuaselsky** [comment]
If the group is invite-only, we won't show the Join button. Instead, text will be shown that indicates that the user can contact the contact email address to request an invite.  On the backend, we will still have to prevent users from joining invite-only groups.

**Comment by ctrance** [comment]
@joshuaselsky - I wanted to test saving new invite-only new group but I can't log in to the test site. There's no option for org's login and if I use the local login my email account 'ctrance@oit.ucla.edu' is throwing error.

**Comment by ctrance** [comment]
fixed
