### ISSUE TITLE
Design a Layout for badges

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#262]
Design a Layout for badges - take a look at the Khan academy badges for some input....

**Comment by laurencullen** [comment]
@rrocchio @krozett here is a new layout for badges page

![ucnext badge comp-01](https://cloud.githubusercontent.com/assets/13141571/10701677/becc1b3e-7979-11e5-8397-404066269fc8.jpg)

**Comment by laurencullen** [comment]
@krozett here are the new graphics for badges and awards icons. This way the page heading can match other pages (like Projects, Ideas, etc)

![award-icon](https://cloud.githubusercontent.com/assets/13141571/10701730/096372f0-797a-11e5-93ad-93a11931e788.png)
![badge-icon](https://cloud.githubusercontent.com/assets/13141571/10701729/09631152-797a-11e5-956f-43cc1ef1f54c.png)

**Comment by laurencullen** [comment]
@rrocchio here is a screen shot of the Khan academy badge page - they have added the number of points for high scoring ones... is this something you would like to add?

Please let me know if you have any changes with the proof.

Thanks!

![screen shot 2015-10-23 at 11 31 09 am](https://cloud.githubusercontent.com/assets/13141571/10701767/3f40e344-797a-11e5-9607-c26539307818.png)

**Comment by laurencullen** [comment]
@krozett Rose was asking regarding this so wanted to check in to see if you need anything else. The design is pasted here. It's important to make all the boxes the same height with text continuing when user clicks onto next page. Thanks!

![ucnext badge comp-01](https://cloud.githubusercontent.com/assets/13141571/10947926/c48fb746-82df-11e5-99b6-2e7be8b5f65f.jpg)

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - staging.ucnext Badges page (screenshot below) doesn't look like https://github.com/universityofcalifornia/NeXt/issues/262#issuecomment-153822922 Lauren's design.

 ![capture](https://cloud.githubusercontent.com/assets/1034174/11514714/cf146e8c-982e-11e5-8a25-e8134eefa025.PNG)

**Comment by joshuaselsky** [comment]
This is occurring because we are migrating to a new Chef process for deploying the app. The badge images are just missing.

**Comment by ctrance** [comment]
@joshuaselsky - On Lauren's design all badges and awards have the same tile size, the current version has different tile sizes. Did the missing badge icon affect that too? If yes, I'll just wait for the Chef process to be done.

**Comment by joshuaselsky** [comment]
@ctrance I updated the images on the staging machine and the build process has been updated. The intention is for the tile size to be the same, yes.

**Comment by joshuaselsky** [comment]
@krozett if the header text breaks over three lines, the layout goes off the grid.

**Comment by ctrance** [comment]
@joshuaselsky - Looks much better now, however there are tiles that still larger than others.
![capture](https://cloud.githubusercontent.com/assets/1034174/11565568/63546290-9993-11e5-885b-61f44577ab1b.PNG)

**Comment by ctrance** [comment]
@krozett - badge/award tiles have same size now, however I notice that the columns have been reduced from 3 (Lauren's design) to 2. See below...
![capture](https://cloud.githubusercontent.com/assets/1034174/11639965/da797be0-9ce4-11e5-96c9-38796e3ac380.PNG)

**Comment by krozett** [comment]
I just put in a quick fix for this, it should be back to 3 columns again!

**Comment by joshuaselsky** [comment]
@ctrance try it now! We thought we would be able to fix it before you saw it!

**Comment by ctrance** [comment]
Looking good now!
