### ISSUE TITLE
Add Twitter Feed to homepage

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#263]
Connect to #211

**Comment by laurencullen** [comment]
@rrocchio @krozett Here is a comp of the new homepage with Twitter feed added. It is based on the idea that the feed will display our tweets as well as other tweets with @UCNextNews and #ucnext - if Twitter doesn't allow this, we can retweet ones we like. Please let me know if you have any changes or need anything else.

![ucnext hompage twitter-01](https://cloud.githubusercontent.com/assets/13141571/10704232/45a75050-798a-11e5-85c3-82932fd21429.jpg)

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - I don't see the twitter feed on the homepage just like on Lauren's design, but a link that opens UCNext twitter page. Is that right?

**Comment by ctrance** [comment]
After clearing the cache, the twitter feed shows on FF now.
