### ISSUE TITLE
Badge category list is blank when creating new badge

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#268]
I'm creating a new badge but the Badge category list is empty
![1](https://cloud.githubusercontent.com/assets/1034174/10798189/af5501fa-7d63-11e5-8abd-3b240730da1c.jpg)

**Comment by joshuaselsky** [comment]
The badge categories could be: gold, silver, honorable mention, green, blue.

**Comment by ctrance** [comment]
fixed
