### ISSUE TITLE
Pre-populated Ideas

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#27]
Everyone, please post ideas that we can pre-populate into the "Ideas" section for the ITLC demo.

**Comment by ebollens** [comment]
From today's meeting:

* UC “quora” system
* systemwide tech talks

**Comment by ctmcintyre** [comment]
Adding "Live Feed" to the platform for project milestones, questions, collaboration, networking

**Comment by indifferent66** [comment]
Systemwide employee feedback and appraisal system. This system could help to standardize rating systems, foster cross-campus growth, and provide much needed data on the health of the organization at all levels. Further, it could allow for peer reviewing and continuous feedback channels.

**Comment by indifferent66** [comment]
Technical and administrative cross-training opportunities. Such opportunities could allow for such personnel to shop for courses and certifications that could help individuals move to a function that best fits their interests. Often individuals join the university at a convenient time and may find themselves 'stuck' in a role that matches their skills, but not their desired goals. For instance, employees on the business side may want to move to similiar roles in the medical field. The only way to do achieve this is through work experience or training. This mechanism could allow the latter.

**Comment by rrocchio** [comment]
Make the Shared Time Reporting System Mobile Enabled

**Comment by ctmcintyre** [comment]
Adapt best of private industry organizational cultural design and management to higher ed culture

**Comment by ctmcintyre** [comment]
Heavily incentivize implementation of IT operational efficiencies. Example: Spend $100k to gain $1M in operational savings; get $200k added one-time to budget.

**Comment by rrocchio** [comment]
IDEA:  Modernize the UC Recruit application

When do people search for jobs?  When they are in line at the coffee shop, while sitting in the airport etc..  What kind of device do they use in these places?  Their phones.  With the UC's best attempts to attract a diverse faculty and staff we should be considering how to make our shared applications Responsive and Mobile - Friendly.  It seems  to be an important endeavor to support job seekers using their own devices to find and apply for opportunities.

**Comment by ctmcintyre** [comment]
Like zappos.com HR model, at performance review time, offer all employees $10k if they want to leave UC.

**Comment by ctmcintyre** [comment]
Job rotation between IT staffers in administrative and academic/research areas.  Give traditionally admin IT staff ability to work on curing cancer or finding alien life; and give traditionally research IT staff the ability to make sure entire campus can authenticate and students get into the classes they want.

**Comment by ctmcintyre** [comment]
Offer all UC Staffers paid time to work on UC's "public service" projects
