### ISSUE TITLE
Fix the badge/award "Give This" button spacing

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#276]
If you go to assigning badge/award page, some "Give This" button is sticking on the badge/award and some are not. Please make the button stick to the badge/award it belongs to with a little space in between to improve the look. It causes confusion to the user.
![capture](https://cloud.githubusercontent.com/assets/1034174/10945984/b1f7edb6-82d4-11e5-8331-cd7924fb4c32.PNG)

**Comment by laurencullen** [comment]
Please also see new design for badges. I think that this will make the positioning of the GIVE THIS button clearer.

![ucnext badge comp-01](https://cloud.githubusercontent.com/assets/13141571/10949313/0d4f88ce-82e7-11e5-8141-dc88a0166950.jpg)

**Comment by ctrance** [comment]
fixed
