### ISSUE TITLE
Add badges to associated group

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#279]
@krozett Please add badge icon to associate group so that users can see that there is a badge associated with a certain group. Please add icon to both group listing page and group details page.

If you need any comps or further description of location please let me know.

![screen shot 2015-11-04 at 10 36 34 am](https://cloud.githubusercontent.com/assets/13141571/10948035/5455bc0e-82e0-11e5-9458-aada3ff1f7cb.png)

![screen shot 2015-11-04 at 10 37 25 am](https://cloud.githubusercontent.com/assets/13141571/10948043/5a999374-82e0-11e5-91c3-e35dbcf9c973.png)

**Comment by joshuaselsky** [comment]
Please see #152 for the design for this page. #152 has not been fully implemented.

**Comment by joshuaselsky** [comment]
For now, badges can just be added to the right of the text description. After that, we can fully implement #152.

**Comment by krozett** [comment]
We don't really have space for the badge icons on the groups list view, but we will when #193 is implemented. I implemented it on the group details pages, though.

**Comment by ctrance** [comment]
@krozett and @joshuaselsky - Lauren and I think that it would be better to make the badge on the left side and make the texts in the Description wrapped on the right instead of stuffing the badge on the right corner. What do you guys think?
![capture](https://cloud.githubusercontent.com/assets/1034174/11515527/48861ece-9833-11e5-8baf-42910d3ac632.PNG)

**Comment by joshuaselsky** [comment]
We discussed this and decided to move the badge to the left of the description content.

**Comment by ctrance** [comment]
@krozett - Group details page now shows the badge/award icon on the left side of the description content. However we still need to add the badge/award icon on the Groups listing page.

**Comment by krozett** [comment]
@ctrance The groups page will change drastically when #193 is implemented. There isn't really space to put them now, because the group rows will get too tall. So I'm just going to wait for #193.

**Comment by ctrance** [comment]
@krozett - Cool, if the team decided not to show the badge/award icon on the Groups listing page anymore please feel free to close this ticket. Thanks!
