### ISSUE TITLE
issues with badges on profile page

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#282]
* If you are not an admin, the section doesn't show on the profile page for any user.
* If you are an admin, badges don't show, but the buttons to give or show badges appear. 
* Badges always show up on Eric's profile.

**Comment by joshuaselsky** [comment]
Please also see https://github.com/universityofcalifornia/NeXt/issues/119.

**Comment by krozett** [comment]
@joshuaselsky what was the thing you wanted to make note of in #119?

**Comment by joshuaselsky** [comment]
Just that there is an opportunity to handle this issue as part of the larger UX rework in #119.

**Comment by krozett** [comment]
True, but I wanted to at least nail this bug now. #119 might just be a lot of CSS and moving HTML around, I don't trust myself to remember to fix this. :wink: 

Anyway, it was a quick fix.

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - I can't proceed testing this due to #293.

**Comment by ctrance** [comment]
Badges now show for both admin and non-admin users in the Profile page.
