### ISSUE TITLE
add password validation for local accounts

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#288]
Keep it simple for now. 

* Must be at least 8 characters
* Must contain at least one letter and one number

**Comment by ctrance** [comment]
@shaun965 and @joshuaselsky - Instead of clearing the whole form when there's error on password, is it possible to only clear the password fields? This way user will not retype other info.

**Comment by ctrance** [comment]
The password validation is working good. I'll close this ticket and create new issue for https://github.com/universityofcalifornia/NeXt/issues/288#issuecomment-161101302
