### ISSUE TITLE
Badge images don't appear and overlap text on tablet view

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#292]
I tried viewing on tablet but the badge images overlap the text (see screenshot below). Also I notice that only 1 badge image appears all others don't show up.
![screenshot_20151118-075213](https://cloud.githubusercontent.com/assets/1034174/11246029/c3c29446-8dca-11e5-8f2d-e7c99e4a375b.png)

**Comment by krozett** [comment]
This page is going through a redesign anyway, so it will be fixed as part of #262.

**Comment by joshuaselsky** [comment]
@ctrance we will be fixing this as part of #262, but left this issue open for you.

**Comment by ctrance** [comment]
Will close this once #262 is fixed

**Comment by ctrance** [comment]
fixed
