### ISSUE TITLE
Giving myself badge throws error

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#293]
I'm trying to give badge "2015 MMWCON Attendee" to myself but got the error below...
![capture](https://cloud.githubusercontent.com/assets/1034174/11246194/7f3a32b0-8dcb-11e5-8aca-033597423e67.PNG)

**Comment by joshuaselsky** [comment]
@ctrance which username were you logged in as when this occurred?

**Comment by ctrance** [comment]
@joshuaselsky - ctrance@ucla.edu

**Comment by krozett** [comment]
I'm unable to reproduce this on my local instance. Can someone forward me the error log for this?

**Comment by ctrance** [comment]
@krozett - Right now if I go to My Account "https://staging.ucnext.org/users/190" I'm getting the error page below. Maybe there's something wrong with my account. I remember @joshuaselsky gave me admin access to the stage site.

![capture](https://cloud.githubusercontent.com/assets/1034174/11350008/3bd68fba-91e4-11e5-8e7b-9a6229e93e4a.PNG)

**Comment by krozett** [comment]
I can reproduce the issue by giving a user an award, showcasing it, and then visiting their profile page. Awards and badges are 99% the same, but we got bit by that 1%.

**Comment by ctrance** [comment]
fixed
