### ISSUE TITLE
Project comment is missing 

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#294]
I can't test "comment on a project" effect on Engagement Meter #123 since there's no comment field/button on the Project details page.

**Comment by ctrance** [comment]
@joshuaselsky - I posted my comment at 9:22 am but the box shows 17:22.
![capture](https://cloud.githubusercontent.com/assets/1034174/12122138/1d9f88aa-b38e-11e5-8c62-d282b2e00b82.PNG)

**Comment by ctrance** [comment]
@joshuaselsky - I think we should make the delete comment message much clearer, maybe "Are you sure you want to delete this comment?"
![capture](https://cloud.githubusercontent.com/assets/1034174/12123013/4d063116-b393-11e5-869c-86e1eb7bcf81.PNG)

**Comment by pmeads** [comment]
@joshuaselsky the records are inserted in the defined timezone of the app. Rails defaults to UTC. in config/application.rb, we should set the timezone to config.time_zone = 'Pacific Time (US & Canada)'. I'll add this to a pull request with some other bug fixes

**Comment by joshuaselsky** [comment]
I would prefer if we stick to UTC in the database because then we can handle other timezones in the view layer. Can you make the fix in the controller or view?

**Comment by pmeads** [comment]
b/c we're not storing the timezone for the user in the user table, we'll need to handle it via JS. there's a gem called "local_time" from basecamp that has a Coffeescript asset and a helper that will do what we want: "Local Time is a Rails engine with helpers and JavaScript for displaying times and dates to users in their local time."  Should we try it out or write a custom JS/helper?

https://github.com/basecamp/local_time

**Comment by joshuaselsky** [comment]
IMO the best way to handle this is to use the local TZ in the user's browser in order to render all dates. It is the least invasive way to implement it and avoids storing "view logic" (i.e., the local or even server timezone) with values in the DB which is only a recipe for trouble later.

**Comment by ctrance** [comment]
fixed
