### ISSUE TITLE
Joining a Sautter Award Winner group automatically adds Sautter Award badge

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#295]
I joined group "Golden Sautter Award Winners - 2004" then the app added "26 points" on the engagement meter. Then I checked my profile and it also added the "2004 Golden Sautter Award Winner" badge. Is that right?

**Comment by krozett** [comment]
This is correct. You got 1 point for joining the group and 25 points for the award. (Even though the "about engagement meter" page says 50 points, it's really 25 points in the database.)

**Comment by ctrance** [comment]
@krozett - @rrocchio  comment on #123 says 50 points too, not 25 though.

**Comment by joshuaselsky** [comment]
Closing because we verified the points were correct.
