### ISSUE TITLE
Can't see joined members in the Group details page

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#297]
It would be nice to see who joined the group " Create a Group ADD 3 points ( DELETE a group - can only be done - if you are the only person in the group)". I can test delete groups that I created for now, since there's no way to see who the group members are in the Group page.

**Comment by krozett** [comment]
We decided to implement a user list that looks like the one on the badge details pages.

**Comment by ctrance** [comment]
fixed
