### ISSUE TITLE
add Badges as top-level menu item

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#299]
The menu item can link to the existing page that lists all of the badges in the system.  This will help surface a part of the engagement / gaming aspect of the app.

**Comment by joshuaselsky** [comment]
Please see the third comment in this issue for the icon. https://github.com/universityofcalifornia/NeXt/issues/262

**Comment by laurencullen** [comment]
@krozett Here is the icon for the nav:
![badgeicon-02](https://cloud.githubusercontent.com/assets/13141571/11313916/ade89220-8f95-11e5-9528-7109f7d330d8.png)

Please let me know if you need anything else.

**Comment by krozett** [comment]
Good thing I wasn't relying on Bootstrap columns here, it turned out to be a trivial change. :P

**Comment by ctrance** [comment]
fixed
