### ISSUE TITLE
make people page responsive

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#304]
It is the one top-level page that is not responsive.

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - On iPad, there's excessive margin on the left (see screenshot)
![img_0366 1](https://cloud.githubusercontent.com/assets/1034174/12649658/60d660d6-c594-11e5-8b54-25cd44799669.PNG)

**Comment by joshuaselsky** [comment]
@ctrance this issue should go away now that the people page requires users to login and once users are logged in the profile photos will show. I am going to mark this as "ready for testing" again.

**Comment by ctrance** [comment]
@joshuaselsky - it's fixed now, thanks!
![capture](https://cloud.githubusercontent.com/assets/1034174/12896720/6adfdaea-ce58-11e5-8a29-55d19769d680.PNG)
