### ISSUE TITLE
Create badge for Multi Campus

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#305]
Create new badge for "Multi Campus" to show collaboration between campuses.

**Comment by laurencullen** [comment]
Here is the new badge - @rrocchio and @ctmcintyre please let me know if you have any changes. This one was requested by Chris Hoffman at Berkeley for the group of librarians working together. Would you also like to add a group for them?

@joshuaselsky would you like for me to add this to staging, prod or both?

![multicampus](https://cloud.githubusercontent.com/assets/13141571/11383276/fbd2a150-92bb-11e5-99ec-638e25dfff4a.png)

**Comment by joshuaselsky** [comment]
Both and thank you!

**Comment by laurencullen** [comment]
This badge is now up on staging and prod: https://ucnext.org/badges/61 Please let me know if you have any changes and if you would like for me to add a group for this one.

**Comment by joshuaselsky** [comment]
Closing, cleaning house and this has been done.
