### ISSUE TITLE
Design Layout for Badge Details page

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#306]
This layout will replace: https://ucnext.org/badges/1

Include all info on badge and look at badge input page for reference. Add list of people who have this badge awarded to them.

**Comment by laurencullen** [comment]
@rrocchio @joshuaselsky @krozett Here is a proof of this page. I used award as an example but it would be the same for badge - just say badge in the details box instead. Please let me know any revisions. Thanks!

![ucnext badge details comp](https://cloud.githubusercontent.com/assets/13141571/11384632/3d6b5242-92c6-11e5-81b0-2a11f80d5c2e.jpg)

**Comment by ctrance** [comment]
fixed
