### ISSUE TITLE
Groups search in the Events form doesn't return all groups

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#312]
I was creating an event and wanted to add the group I belong to which is Technology Acquisition Support Group (https://staging.ucnext.org/groups/33) but when I search it in the "Groups" field it doesn't come up.

**Comment by joshuaselsky** [comment]
@ctrance can you retest because we cannot recreate this issue.

**Comment by ctrance** [comment]
@joshuaselsky - I still get this bug, below are the steps to replicate it:
1. Logged in as "ctrance@ucla.edu" (admin)
2. Join a group
3. Create new event, then search for the newly joined Group 
![untitled](https://cloud.githubusercontent.com/assets/1034174/12173729/610c2ee2-b50d-11e5-8758-24c8e33e6a58.png)

**Comment by krozett** [comment]
I was able to reproduce the bug. The search excludes groups that the current user is a member of, for some unknown reason. I took out the filtering and it works now.

**Comment by ctrance** [comment]
@krozett - Sounds good! I also got a bug where newly created group (not yet a member) doesn't show in "Groups". Once the fixes are deployed to stage site please let me know so I can retest. Thanks!

**Comment by ctrance** [comment]
fixed
