### ISSUE TITLE
Clicking a name link on People page throws error if user is not logged in

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#313]
I wasn't logged in then click a name link on People page, the error message shows.
![capture](https://cloud.githubusercontent.com/assets/1034174/11516657/777b5356-9839-11e5-9c64-3d111722770a.PNG)

**Comment by pmeads** [comment]
I think that's b/c shibboleth is not set up on the staging server.

On Tue, Dec 1, 2015 at 2:42 PM, ctrance <notifications@github.com> wrote:

> I wasn't logged in then click a name link on People page, the error
> message shows.
> [image: capture]
> <https://cloud.githubusercontent.com/assets/1034174/11516657/777b5356-9839-11e5-9c64-3d111722770a.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/313>.
>



-- 
Philip Meads
Database Administrator
UCSC
831 459 1705
philme@ucsc.edu

**Comment by ctrance** [comment]
Fixed, the app is not throwing error anymore. We still need to redirect to People page after successful login which is covered by #336.

Closing this :)
