### ISSUE TITLE
add a search people function

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#315]
The initial design is here: #195

**Comment by joshuaselsky** [comment]
Closing because the existing search already searches people.

**Comment by ctrance** [comment]
@joshuaselsky - I tried searching for my name (using the main search tool) while in People page but it didn't return any result.

**Comment by joshuaselsky** [comment]
@ctrance -- if you tried on the staging machine, this occurs because we have not indexed people.

**Comment by ctrance** [comment]
@joshuaselsky - Yes, I tested this on staging machine. It's working on prod, you're right! Closing this :)

**Comment by joshuaselsky** [comment]
@ctrance in the interim, could you try adding a new account and then searching for it? Or you could try in the production app.

**Comment by ctrance** [comment]
@joshuaselsky - created new account also appeared when I search for it.
