### ISSUE TITLE
home page issues with votes and bubbles

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#316]
* Total projects and total ideas should show the number of each, not the votes.
* The layout of the projects and ideas lists need to updated so the text doesn't cause the bubbles to wrap.

**Comment by ctrance** [comment]
@krozett - On phone view, the bubble for total projects is missing while the bubble for total ideas is cutoff. See below...
![img_9226 1](https://cloud.githubusercontent.com/assets/1034174/11640371/0e2151e6-9ce7-11e5-9ef9-9c2b35d1bd18.PNG)

**Comment by ctrance** [comment]
fixed
