### ISSUE TITLE
Badges self-removal doesn't delete badge assignment

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#319]
@krozett - I went to My Account > Manage Badges/Awards then removed 2015 UCCSC Attendee badge. After clicking the button the badge disappeared but when I go to "Badges" I still see myself as a recipient.

**Comment by joshuaselsky** [comment]
@krozett can you try and recreate and close if you can't?

**Comment by krozett** [comment]
Works on my machine! :+1:
