### ISSUE TITLE
BUG: timestamps for events

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#320]
Event #13 (Intro to Lean) has a start time of 9:09am and an end time of 10:10am, when I selected and submitted 9am to 11am...  I don't see anywhere to update or change the minute, just the hour for the start and end times.

**Comment by joshuaselsky** [comment]
@ctrance this is already fixed and deployed to the staging environment, correct?

**Comment by ctrance** [comment]
@joshuaselsky - We've fixed the minute rendering issue but we need to change the time selection to allow minutes to be updated. Perhaps we can change from time list to a time input box so user can just type in the hour and minute instead of selecting from a list?

**Comment by joshuaselsky** [comment]
* On mobile, display the native time-picker HTML5-style
* On web, display a plain input box

**Comment by krozett** [comment]
Support for this input type is not very widespread on desktop platforms:

So I decided to only use native controls for mobile devices (I detect this using the Modernizr library, checking for devices that support both touch and the datetime input type). For other devices, I keep the date picker part of the widget, but leave the time alone. The user has to type in the time by hand. I also make the widget open when clicking into the text field, so it doesn't obliterate the existing field.

**Comment by ctrance** [comment]
New dateTime input works good.
