### ISSUE TITLE
admin feature: transfer founder

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#323]
On the edit project page, an admin should be able to transfer a founder to a different NeXt user.

**Comment by joshuaselsky** [comment]
* Admins will need to be able to edit projects.
* The new founder should receive an email alerting them.
* On the edit projects page, there should be an input box for the new founder's email address.
* The email address of the new founder must match that of an existing next user. If it doesn't, show an error message.

**Comment by ctrance** [comment]
fixed
