### ISSUE TITLE
add rapporteur

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#326]
https://github.com/codeschool/rapporteur/blob/master/README.md

**Comment by joshuaselsky** [comment]
@ctrance to test this you can navigate to https://staging.ucnext.org/status.json - this new page lists the git commit hash and deployment time for the most recent app deployment.

**Comment by ctrance** [comment]
@joshuaselsky - recent commit code and time shows but somehow there's a time difference (see below). Maybe it's not set to our timezone? If that's fine, then we can close this :)
![capture](https://cloud.githubusercontent.com/assets/1034174/11851674/b118b5c6-a3e8-11e5-91f2-a90670cd7550.PNG)

**Comment by joshuaselsky** [comment]
The status.json page shows the time in a very specific format. The format is called ISO 8601 and it is basically the different fields in a date listed from left to right in order of increasing specificity with the timezone abbreviation at the end. The Z timezone is [Zulu](http://www.navy.mil/navydata/questions/zulutime.html) time. (In case you wanted to know random technical info about formatting dates ...)

**Comment by ctrance** [comment]
@joshuaselsky - Got it, timezone is zulu that's why the time difference is 9 hrs. I'll close this then, thanks!
