### ISSUE TITLE
ideas should have campus-level visibility

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#334]
An idea should be able to be marked as visible to only a particular campus and in that case it should only be visible and actionable to logged in users from the particular campus.

**Comment by joshuaselsky** [comment]
For ideas that are set to campus-level visibility, we should investigate showing them in a separate table on the main Ideas page. It will also be important to filter campus-level ideas from search results (and the trending ideas table) depending on who is logged-in.

**Comment by joshuaselsky** [comment]
We decided to include campus-specific ideas in the main table and projects that are specific to each campus will have the associated campus logo in the project tile. "Global" projects will have a logo containing UC-Wide.

The idea is that this keeps the UI simple.

**Comment by joshuaselsky** [comment]
Please also change the text for Trending Ideas to be Trending UC-Wide Ideas.

**Comment by krozett** [comment]
The "Trending UC-Wide Ideas" is going to look bad for now until we go through all the page designs. Please ignore the ugliness for now.

**Comment by ctrance** [comment]
Working good.
