### ISSUE TITLE
projects should have campus-level visibility

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#335]
An project should be able to be marked as visible to only a particular campus and in that case it should only be visible and actionable to logged in users from the particular campus.

**Comment by joshuaselsky** [comment]
For projects that are set to campus-level visibility, we should investigate showing them in a separate table on the main Ideas page. It will also be important to filter campus-level proejcts from search results (and the trending ideas table) depending on who is logged-in.

**Comment by joshuaselsky** [comment]
We decided to include campus-specific projects in the main table and projects that are specific to each campus will have the associated campus logo in the project tile. "Global" projects will have a logo containing UC-Wide. 

The idea is that this keeps the UI simple.

**Comment by joshuaselsky** [comment]
@laurencullen for the UC-Wide logo.

**Comment by joshuaselsky** [comment]
Please also change the text for Trending Projects to be Trending UC-Wide Projects.

**Comment by laurencullen** [comment]
Attached the UC-WIDE logo - there are three color options: the cyan blue isn't accessible but matches UC's brand color, the dark blue is accessible, the dark gray is accessible. Please let me know if you need anything else for this.

![uc wide logo-01](https://cloud.githubusercontent.com/assets/13141571/12766379/6d44b7a0-c9b8-11e5-994d-a029304b1a97.png)
![uc wide logo-02](https://cloud.githubusercontent.com/assets/13141571/12766380/6d4a00ac-c9b8-11e5-993e-d35b321f5864.png)
![uc wide logo-03](https://cloud.githubusercontent.com/assets/13141571/12766381/6d4f7424-c9b8-11e5-97f3-06ce4f772944.png)

**Comment by krozett** [comment]
The "Trending UC-Wide Projects" is going to look bad for now until we go through all the page designs. Please ignore the ugliness for now.

**Comment by ctrance** [comment]
@krozett @joshuaselsky - "UC Wide" logo appears though the project is campus specific, please see screenshot below:
![capture](https://cloud.githubusercontent.com/assets/1034174/13324217/83fdef26-db91-11e5-9b7f-1cd587f56291.PNG)

**Comment by ctrance** [comment]
Working good
