### ISSUE TITLE
redirect to current page after login

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#336]
If a user tries to access a page that is blocked by login, they should be redirected to that page after a successful login. There is an existing implementation of this in [application_controller.rb](https://github.com/universityofcalifornia/NeXt/blob/master/app/controllers/application_controller.rb#L16) that appears not to work. The existing redirect method is used by the code fixed as part of #313.

**Comment by ctrance** [comment]
fixed
