### ISSUE TITLE
Fix Award/Badge email broken links 

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#338]
@krozett - I opened the award/badge email that I received from the app. But when I click the "badges page" link (not logged in) I get error page and also if I click "profile preferences page" I get a blank page.
![capture](https://cloud.githubusercontent.com/assets/1034174/11877988/a9fb61ca-a4a7-11e5-9dd7-ecc87216324e.PNG)

**Comment by krozett** [comment]
@ctrance could you please paste the URLs here?

**Comment by ctrance** [comment]
@krozett and @joshuaselsky - I don't get a blank page when clicking "badges page" link anymore. However if I'm logged out and just click that link I can see my badges, but if I'm logged out and select a person on People list the app is redirecting to login page (see below). Should we do the same? Or it's fine to make people's award/badges public?

![capture](https://cloud.githubusercontent.com/assets/1034174/11943333/cfeff7cc-a7f1-11e5-9688-782293c9f7f0.PNG)

**Comment by krozett** [comment]
We're going to address this in #133. Badges and profiles will both follow the user's privacy setting.
