### ISSUE TITLE
Receiving 2004 Golden Sautter Award didn't auto-join group associated with it

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#339]
Admin (ctrance@ucla.edu) gave user (ctrance@oit.ucla.edu) 2004 Golden Sautter Award but when the recipient logs in the group "Golden Sautter Award Winners - 2004" doesn't appear on "My Groups" list.

**Comment by krozett** [comment]
When you join a group, it gives you any badges associated with the group. But it doesn't work the opposite way. If you add a badge, it doesn't automatically make you join the group.

**Comment by ctrance** [comment]
@krozett - I think it would make sense to auto-join the group on badge/award assignment. After all the group name says <badge/award> Winners. However this is just my opinion and would follow the agreed requirements on this issue.

**Comment by joshuaselsky** [comment]
We decided to implement this. If users join a group, they will receive all of the badges that group has.

**Comment by ctrance** [comment]
@joshuaselsky - Got it, not the other way around. I'll close this then.
