### ISSUE TITLE
Project pages are down

### ISSUE THREAD

**Issue by loganfranken** [universityofcalifornia/NeXt#343]
Hey there!

Looks like the project pages are down?
https://ucnext.org/projects/15

**Comment by joshuaselsky** [comment]
Thanks for the bug report!  You are looking at a brand new migration process and a brand new app. :)

**Comment by joshuaselsky** [comment]
... and we're back. Can you check it out and let us know if it is working for you?

**Comment by ctmcintyre** [comment]
Looks good!

> Joshua Selsky <mailto:notifications@github.com>
> December 21, 2015 at 9:06 AM
>
> ... and we're back. Can you check it out and let us know if it is
> working for you?
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/343#issuecomment-166360870>.
>
> Logan Franken <mailto:notifications@github.com>
> December 21, 2015 at 8:45 AM
>
> Hey there!
>
> Looks like the project pages are down?
> https://ucnext.org/projects/15
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/343>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by loganfranken** [comment]
Looks good to me too! Thanks!
