### ISSUE TITLE
update character set and collation sequence in the db to support UTF-8

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#344]
If I add a comment with an emoji, comment creation fails at the ActiveRecord layer with the following message.

    Mysql2::Error: Incorrect string value: '\xE2\x98\x95\xEF\xB8\x8F' for column 'body' at row 1: INSERT INTO `comments` (`body`, `commentable_id`, `commentable_type`, `created_at`, `lft`, `rgt`, `updated_at`, `user_id`) VALUES ('☕️', 1, 'Project', '2016-01-05 17:13:22', 33, 34, '2016-01-05 17:13:22', 108)`

If the emoji is in a nested comment, the error message does not appear and the comment is also not inserted, so it seems like there is also an issue with displaying error messages for nested comments.

**Comment by krozett** [comment]
Check string encodings, the last time I checked everything was set to Swedish. :disappointed:

**Comment by pmeads** [comment]
yeah, there seems to be two issues. there is a bug in the replay in that any errors in the reply disappear with no notice. but also there seems to be a charset issue on at least the staging server. I was able to insert the emoji successfully on my dev box running mysql so wasn't able to reproduce the problem. On my dev box the comment table charset is UTF8.  Is the backend mysql on the staging server?

**Comment by joshuaselsky** [comment]
On both staging and prod, the charset for the database is `latin1` and it looks like the collation for all character-based columns (varchar, text) is `latin1_swedish_ci` (I didn't verify every table).  Easy enough to fix. This must be a relic from the initial Chef deployments. I will make sure that Chef is updated as well even though now it is a bit after the fact. I am glad I tried the emoji!  :zap:

**Comment by joshuaselsky** [comment]
Oh, and @pmeads, yep, it is MySQL on both staging and prod.

**Comment by joshuaselsky** [comment]
I am going to change the title of this issue and make a new one for the missing error messages for nested comments.

To support emoji in the db, here's what has to be done. I have NOT TESTED this yet, but I wanted to document the steps for feedback and future use.

1. Backup the database.
2. Stop the app.
3. Drop the database.
4. Set the innodb properties as described [here](https://gist.github.com/gregawoods/b26751a623a56aa0a75d).
5. Import the backed up database.
6. `ALTER DATABASE next CHARACTER SET utf8mb4_unicode_ci COLLATE utf8mb4_unicode_ci;`
7. For each table, `ALTER TABLE $table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`
8. Update the relevant database.yml to use the correct encoding and collation. 
9. Test! 

More info:
* http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci/766996#766996
* http://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/

**Comment by pmeads** [comment]
A couple things to consider here:
The article says utf8mb4_unicode_ci was supported in mysql 5.5. I think the production version of MySQL is 5.1

Only the columns that store emoji should be utf8mb4_unicode_ci. So, I wouldn't even make tables utf8mb4_unicode_ci. Only the text column storing the emoji needs to have that charset. The reason behind that is you really want your data as compressed as possible, that way more data fits in each page of each index and is more likely to be fetched from memory rather than disk. In other words, you want as much as you can in memory. A smaller footprint means you can cram more data in the buffer pool and thus you have a faster app b/c it doesn't have to go to disk as often. 

An optimized database that accepts emoji would be laid out this way:
* system/app only tables should be latin1
* tables that accept user input should be utf8
* tables that also accept emoji should have those columns be utf8mb4_unicode_ci. 

The MySQL db I am using is 5.1 and the charset is CHARSET=utf8 COLLATE=utf8_unicode_ci. The coffee mug emoji stored just fine in the config but perhaps that is b/c it is only 3 bytes. A four byte emoji may need that new  utf8mb4_unicode_ci charset  (which I don't think exists for 5.1).

**Comment by pmeads** [comment]
I think if you only change the text column to utf8mb4_unicode_ci in the comment table, you can skip step 4. We aren't indexing that field in MySQL and aren't likely to.

**Comment by joshuaselsky** [comment]
Being able to avoid dropping and recreating the DB would be nice. I did try to set the string columns to utf8mb4_unicode_ci in the comments table and I received the key-length warning documented in the blog post. Is the warning simply that the index would only be built off a truncated section of the column? For a giant text blob even that isn't so bad.

**Comment by pmeads** [comment]
What version of MySQL is the staging db? It should be the exact same as production if possible

**Comment by pmeads** [comment]
OK, I read your post more closely this time. The only column that needs utf8mb4_unicode_ci is comments.body. If you changed the charset of comments.commentable_type to utf8mb4_unicode_ci you would get the index warning. That column should be latin1 as type will never have a non-western char. It should also be no longer than the length of the name of any objects we want to make commentable.

**Comment by joshuaselsky** [comment]
We decided to implement the following:

* For any column that would store emoji, update the charset to `utf8mb4_unicode_ci`.
* For any other column that would accept user data, update the charset to `utf-8`.

**Comment by joshuaselsky** [comment]
@pmeads do you think we can handle the charset changes using migrations instead of a script like we discussed?

**Comment by pmeads** [comment]
I'm not sure actually. I think if the test env was also using MySQL then absolutely. These migrations might fail for sqlite. I'll look into it.

**Comment by pmeads** [comment]
I did create a migration changing all text fields to utf8mb4. When I use the comments feature it isn't working on my laptop. I had to first upgrade my MySQL install to 5.7. However, I don't thing the MySQL OSX binary comes with utf8mb4. At least, it isn't in the share/mysql/charset/Index.xml file where it should be.

**Comment by pmeads** [comment]
this is the code for the migration to change a charset for the database, table and column

Database:
execute "ALTER DATABASE next DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci"
Table:
execute("ALTER TABLE comments CHARACTER SET utf8 COLLATE utf8_unicode_ci")
Column:
execute("ALTER TABLE comments MODIFY `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin")

**Comment by joshuaselsky** [comment]
@pmeads Your PR is now on staging.ucnext.org. Did you leave the name columns on the different relations out for a reason?

**Comment by pmeads** [comment]
I only included fields that contain descriptions, summaries, comments, etc. where I thought someone might use an emoiji.

**Comment by joshuaselsky** [comment]
I would like to add the capability for 4-byte UTF-8 characters to the name fields too. It's incongruent with the rest of the fields that allow this new capability and also I think in names people might want to use emoji or e.g., Chinese glyphs. Are you up for the change? If not, I can take care of it.
