### ISSUE TITLE
add the ability to edit comments

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#348]
Admins and the user who created the comment should be able to edit the content. 

Nice to haves:
* Some kind of indication in the UI that the comment was edited.
* An audit trail in the db (e.g., by using the Rails updated_at timestamp column idiom).

**Comment by pmeads** [comment]
@joshuaselsky Are you thinking of keeping a record of the edits of a comment. 
for instance a table like
comment_history
* id
* comment_id (id of comment that was edited)
* body (text of the edit)
* created_at (date of the edit)

where each time an edit happens for a comment, it is logged in the comment_history table for that comment?

**Comment by joshuaselsky** [comment]
No, I think that is overkill.  I just meant that we should use the Rails `timestamps` macro on the comments table. It looks like it is [already there](https://github.com/universityofcalifornia/NeXt/blob/master/db/migrate/20150522214804_create_comments.rb#L12), so the `updated_at` timestamp will be updated on edits.

**Comment by ctrance** [comment]
fixed
