### ISSUE TITLE
UCOP issue with Shib Auth

### ISSUE THREAD

**Issue by ctmcintyre** [universityofcalifornia/NeXt#354]
Mark Weiss from UCOP put in all the correct metadata, is able to select UCOP from the Campus ACcount list and successfully authenticate, but Next continues to show "Login" instead of "My Account"

**Comment by joshuaselsky** [comment]
We are looking into this. It looks like our UCSD Shib endpoint has an out-of-date URL for the UCOP IdP.

**Comment by joshuaselsky** [comment]
UCOP has verified that authentication is now working for their campus. The issue was that the UCOP metadata was incorrectly configured in the UCSD SP.
