### ISSUE TITLE
Joining "invite only" groups didn't notify user on Groups page

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#358]
@joshuaselsky @krozett @shaun965 - I was on the main Groups page and click "Join" button on Test Group 8 which is an invite-only group. The page just refreshed and didn't notify me, I have to go to the details page to know that it's an invite-only group. I think it would be nice to notify if the group is invite only upon joining.

**Comment by joshuaselsky** [comment]
It seems like the real fix here is to not show the join button if the group is invite-only.

**Comment by ctrance** [comment]
@joshuaselsky - You're right, the Join button should be hidden instead.

**Comment by krozett** [comment]
@ctrance Did the system put you in the group? I'm hoping we at least implemented the "stop the user from joining" part on the back end.

**Comment by ctrance** [comment]
@krozett - I was not able to join the group when I click "Join" button on an invite-only group. Instead the page just refreshed with no notification that I cannot join it. I like @joshuaselsky suggestion which is to hide the Join button for groups that have restrictions.

**Comment by krozett** [comment]
Rather than remove the button entirely, I just made it non-clickable text that says "invite only". I think that's more informative, as a user might wonder why there is no "join" button and think it's a bug. I did the same thing on the group details page, in place of the join button.

**Comment by ctrance** [comment]
fixed
