### ISSUE TITLE
Trying to edit a project with no founder throws an exception

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#361]
https://staging.ucnext.org/projects/7/edit

undefined method 'user' for nil:NilClass
`@founder_email = @project.project_roles.where(admin: true).first.user.email`
app/controllers/projects_controller.rb:61:in 'edit'

This is happening because there was no founder for this project.

**Comment by krozett** [comment]
I'm doing a quick fix by using the try() function around method calls which might be invoked on nils. I think a better solution would be to find out why we have projects with no founders. Does this make sense? If a project must always have a founder then there needs to be stronger checking in the model's validations.

**Comment by joshuaselsky** [comment]
It seems to me that for a project to exist, it must also have a founder. Perhaps the founder column was added after the project in question was created in the DB.

**Comment by joshuaselsky** [comment]
@krozett I fixed this same problem in another issue. https://github.com/universityofcalifornia/NeXt/issues/373 It seems like we have projects that were created before the founder functionality was added to the app.

**Comment by joshuaselsky** [comment]
* Stronger validation has been added to disallow nil founders for new or edited projects.
* Any project on staging or prod without a founder has been updated to include one.
