### ISSUE TITLE
E-mails From Staging

### ISSUE THREAD

**Issue by loganfranken** [universityofcalifornia/NeXt#366]
Hey there!

Just wanted to let you know that I received an e-mail telling me that I got a Supporter on my project (https://ucnext.org/projects/14); however, the e-mail directed me to the *staging website*.

If you want to keep using me as a guinea pig, that's totally cool with me!

(Just wasn't sure if you knew that e-mails were getting sent out from staging or not)

**Comment by joshuaselsky** [comment]
Thank you for being a guinea pig! We cloned the prod db into our staging environment in order to start with some existing projects / ideas so that's a legitimate email from the staging machine.

**Comment by joshuaselsky** [comment]
We will resolve this with #377.
