### ISSUE TITLE
Add "Transfer Founder" to Ideas too

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#367]
Make the "Transfer Founder" from Projects available for Ideas too.

**Comment by joshuaselsky** [comment]
When a user neglects to fill in a founder, they are redirected to the view idea page with an error message. The user should stay on the edit idea page.

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 Can we change the current error message "...Please enter in an email for the transfer founder field." to "...Please enter the new founder's email in the Transfer Founder field"?

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - I still see the same message "All ideas now must have a founder! Please enter in an email for the transfer founder field."

Can we change it to "All ideas now must have a founder! Please enter the missing email address for the Transfer Founder field."?

**Comment by ctrance** [comment]
fixed
