### ISSUE TITLE
edit project / idea visibility

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#371]
* Users should not be able to downgrade the visibility of an idea or project, but they can always upgrade to more visibility. (The idea is that a downgrade to campus-level visibility would entail a heavy weight audit of votes and supporters)
* However, users should be able to convert back and forth from public to private.

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - How do I edit the visibility of Ideas/Projects? When I go to the Edit Details page I don't see any buttons about visibility. Can you please help me with some instructions? Thanks!

**Comment by joshuaselsky** [comment]
Some fixes:
* Users should not be able to edit their campus affiliation once it is set.
* If the user does not have a campus, their email address should be the campus identifier.
* The user's campus image should show up on their profile.

**Comment by joshuaselsky** [comment]
@krozett can you make a separate issue that documents the additional work necessary to properly implement the previous comment?

**Comment by joshuaselsky** [comment]
Here's the [info about eduPersonPrincipalName](https://www.incommon.org/federation/attributesummary.html#eduPersonPrincipal).

**Comment by krozett** [comment]
New issue #415 was created to address the campus issue, so the feature is ready for testing again.

**Comment by ctrance** [comment]
Ideas and Projects Visibility are working good now.
