### ISSUE TITLE
update to transfer founder

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#375]
In some cases when transferring a founder, it is desirable to remove the old founder from the list of project roles.  Next to the the Transfer Founder input box, a checkbox could be added to remove the founder from the project altogether.

**Comment by joshuaselsky** [comment]
@shaun965 please also make sure that collaborators cannot remove founders.

**Comment by shaun965** [comment]
For now, if the checkbox is ticked, I am deleting the previous founders participation and support in the project.

**Comment by ctrance** [comment]
Working good!
