### ISSUE TITLE
Event does not send email to address listed on the "Invite List"

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#378]
@joshuaselsky @krozett - I created an event and filled in the "Invite List" field with just 1 email address "ctrance@oit.ucla.edu" but I didn't receive any email from the app.

**Comment by joshuaselsky** [comment]
Can you check to see if the email was filtered out by the spam filter?

**Comment by ctrance** [comment]
@joshuaselsky - I checked and no ucnext email got filtered out. I had emails from ucnext app for the badge/project/ideas this morning too that went directly to my inbox.

**Comment by joshuaselsky** [comment]
It looks like this feature was only partially. The [code](https://github.com/universityofcalifornia/NeXt/blob/master/app/models/event.rb#L99) refers to an instance variable that does not exist.

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 I still didn't get event's invitation email notification

**Comment by joshuaselsky** [comment]
@shaun965 

There are a few issues that need to be fixed here.
* When the email is sent, the `responded` column is updated. This is incorrect and a new column called `email_sent` should be used.
* The email text needs to be updated. It should say, "You have been invited to the event EVENT_NAME. Please RSVP by clicking Accept or Decline.", where Accept and Decline are links to the appropriate action in the app.
* When a user clicks on either Accept or Decline their answer should be recorded. Currently in invites_controller.rb there is a bug in the set_data method on line 29 that causes an exception to be raised.

**Comment by ctrance** [comment]
The app is sending event email now but found some issues. I'll create those issues separately and close this.
