### ISSUE TITLE
[design] Define User Interface Tasks

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#39]
Right now, the [roadmap](https://github.com/universityofcalifornia/NeXt/wiki/Planning:-Roadmap) states:

* Define and implement a look-and-feel for the site including masthead, content region and footer
* Define common user interfaces such as typography, buttons, panels, forms and user-friendly selection boxes

This task is a meta task where someone needs to define the tasks that are required for UI design, which should then be broken into their own issues.

**Comment by rrocchio** [comment]
Since this is related to Design, I think we should divide up these tasks after we select a design

**Comment by rrocchio** [comment]
@laurencullen  - does this make sense?  If we do it this way, then future development can make use of these objects....  - some of the pages will have unique items, but designing these components will be useful to the developers and will let us expand and grow with the UI design

**Comment by rrocchio** [comment]
@laurencullen  - actually - I will separate these into different tasks - sorry for the confusion

**Comment by rrocchio** [comment]
I have carved these tasks up into their own tasks - so closing this one!
