### ISSUE TITLE
when an event is edited, new invites should be sent

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#390]
If a user edits an event and changes the invite list, 
* any new user in the list should receive an invite
* any user that was removed should have their invite removed as long as they have not responded

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - I got "someting went wrong" page when the deleted email tries to accept the event invitaton.
![capture](https://cloud.githubusercontent.com/assets/1034174/13189684/afd0dd4e-d70d-11e5-8683-8b226b547d97.PNG)

**Comment by shaun965** [comment]
Hey Catherine, what do you mean by deleted user? So you sent an invite and an email to the person and then deleted the invite afterwards?

**Comment by ctrance** [comment]
@shaun965 - I meant I deleted the "email address" in the Invite List, then when the user with the deleted email address clicks the accept/decline link on the invitation I got the error page above.

**Comment by joshuaselsky** [comment]
New enhancement:

* If a user has accepted or declined, the user cannot be removed from the invite list.

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - Everything works good now, but can we show a message when trying to delete accepted/declined person from the Invite List? At first the person got deleted after saving but going back to the Event still show the person.

**Comment by ctrance** [comment]
Will test this once staging sends email notification.

**Comment by ctrance** [comment]
fixed
