### ISSUE TITLE
EventsController assumes that an event exists

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#391]
In the `before_action` for edit, update and destroy, the code assumes that `find_event` will always return an event and raises a `NoMethodError` if an event cannot be found.

**Comment by ctrance** [comment]
@joshuaselsky and @shaun965 - I'm not sure how to test this one. Can you please help me with some instructions? Thanks!

**Comment by joshuaselsky** [comment]
I will test it out - I should have not given this the Ready for Testing label.
