### ISSUE TITLE
 Invite List shows the invitees differently 

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#398]
@joshuaselsky @shaun965 - If I separate the email by comma the invitees are listed one bullet per email but if I separate the email by semi-colon or by white space then app listed all emails in one bullet.
![capture](https://cloud.githubusercontent.com/assets/1034174/13083012/03381228-d488-11e5-8b92-791054e13887.PNG)

**Comment by shaun965** [comment]
We decided to only allow comma's to separate the emails. We will have validation that will reject update if it is not correctly formatted

**Comment by ctrance** [comment]
Fixed.
