### ISSUE TITLE
Event Accept/Decline button click sends user to the landing page

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#400]
@joshuaselsky @shaun965 - When the user clicks the "Accept" or "Decline" button from the event's email they are sent to the front page https://staging.ucnext.org/

Should we take them to the Login page instead?

**Comment by joshuaselsky** [comment]
We decided to send the user back to the login page and once they login, the will be redirected to the page for the event.

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - The accept/decline email link now opens the Login page, but after logging in I was not redirected to the event page but on the home page.

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - staging site does not send email, cannot test this right now.

**Comment by joshuaselsky** [comment]
Remember that on staging we have an email whitelist. Only users in the list in [this file](https://github.com/universityofcalifornia/NeXt/blob/master/config/whitelist_email.yml) will receive emails.

**Comment by ctrance** [comment]
@joshuaselsky Thanks for reminding me, I totally forgot about the whitelist! 

The issue has been fixed, I'm now redirected to the event's details page after successfully logging in upon accepting/declining the event. Closing this.
