### ISSUE TITLE
No indication which invitees accepted or declined on event's page

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#401]
@joshuaselsky @shaun965 - Looking at Event's page, I could not tell who accepted or declined the invite. Should we add that?

**Comment by joshuaselsky** [comment]
Next to each email address we will show:
* a green checkmark if the user accepted
* a red x if the user declined
* nothing if the user has not taken action

**Comment by laurencullen** [comment]
@shaun965 please see attached icons and let me know if you need anything else.

![events icons_accepted](https://cloud.githubusercontent.com/assets/13141571/13305597/3259e04c-db11-11e5-8e12-5d485f86afba.png)
![events icons_declined](https://cloud.githubusercontent.com/assets/13141571/13305598/325d651e-db11-11e5-8e00-096fa6005b13.png)

**Comment by ctrance** [comment]
fixed
