### ISSUE TITLE
Getting email address error when Admin changes Profile Visibility of other accounts

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#402]
@joshuaselsky @krozett - When admin (ctrance@ucla.edu) try to change the Profile Visibility of other account (ctrance@oit.ucla.edu), the app throws error "The email you are trying to change to already exists"

**Comment by krozett** [comment]
This actually had nothing to do with profile visibility. If you tried to edit any other user as a super admin, it would check that user's current email against the logged-in user's email, see they were different, and then try to change it (and fail because that email is taken).

**Comment by ctrance** [comment]
Fixed.
