### ISSUE TITLE
Campus Specific dropdown list shows all campus for Non-Admin

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#410]
@joshuaselsky @krozett - For Non-Admin users, should we hide other campuses that they are not associated with and just show their campus in the "Campus Specific" dropdown?

**Comment by joshuaselsky** [comment]
Yes, because they wouldn't be able to see any of the projects / ideas anyway.

**Comment by joshuaselsky** [comment]
In our meeting, we discussed the fact that @krozett had already implemented multi-campus projects and ideas behind the scenes. We decided to just implement multi-select in the UI because it will allow for more flexibility even if users decide to only select one campus. It also avoids having custom mappings for the case where Berkeley has its associated Labs.

**Comment by ctrance** [comment]
@joshuaselsky @krozett - I'm able to assign multi-campus for projects and ides and the privacy is working good too. However, if it's multi-campus, the UI only show 1 campus logo on the projects/ideas list
![capture](https://cloud.githubusercontent.com/assets/1034174/13753678/290f4c1a-e9d1-11e5-8530-01294158019a.PNG)

**Comment by joshuaselsky** [comment]
@laurencullen could you create a "multi-campus" image similar the UC-Wide one? This would be shown in the case where a project or idea was restricted to two or more campuses.

**Comment by laurencullen** [comment]
@joshuaselsky here are three color versions of the image to choose from. I would choose UCNext blue one but the UC blue one matches the UC-WIDE logo.

![multi-campus_black](https://cloud.githubusercontent.com/assets/13141571/13789991/9ee71256-eaa3-11e5-9e8b-37c89f7764b3.png)
![multi-campus_ucblue](https://cloud.githubusercontent.com/assets/13141571/13789990/9ee4d2a2-eaa3-11e5-8704-20f0a61761be.png)
![multi-campus_ucnextblue](https://cloud.githubusercontent.com/assets/13141571/13789992/9eeb1428-eaa3-11e5-9213-1d7aaa5208c5.png)

**Comment by joshuaselsky** [comment]
@krozett can you drop this in for the multi-campus case?

**Comment by ctrance** [comment]
fixed
