### ISSUE TITLE
Campus affiliation should come from Shibboleth only

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#415]
This was originally a comment from #371, but it's large enough that it needs its own issue.

These things need to happen:
- Users should not be able to change their campus (though they can change their position)
- Users should only have one campus (right now it's a many-to-many relationship)
- When creating an account, match the Shibboleth [eduPersonPrincipalName](https://www.incommon.org/federation/attributesummary.html#eduPersonPrincipal) to their campus so it is set
- Set the campus for any campus-less users based on their email address, and pray to the [Lords of Kobol](https://en.wikipedia.org/wiki/Lords_of_Kobol) that they're not using a generic gmail address (or fix them manually)
- Display the campus logo on the user's profile page

Issue #370 should be implemented ASAP, so we don't get any more local users that would require fixing.

**Comment by krozett** [comment]
The one thing I didn't finish on this task is allowing the user to set/change their position. I ripped out the whole section on the edit user form. I want to make sure the campus logic works first (as all the Shib stuff was coded blind), then I'll add that stuff back in.

**Comment by ctrance** [comment]
@krozett @joshuaselsky - Campus logo now appears on the profile and Shibb login is working on stage site. 

However, I was not able to test the following since the campus selection does not show when I edit the profile and I cannot create campus accounts just local accounts:
- Users should not be able to change their campus (though they can change their position)
- Users should only have one campus (right now it's a many-to-many relationship)
- When creating an account, match the Shibboleth eduPersonPrincipalName to their campus so it is set
- Set the campus for any campus-less users based on their email address, and pray to the Lords of Kobol that they're not using a generic gmail address (or fix them manually)

**Comment by krozett** [comment]
@ctrance Here's how to verify that the features were done correctly:

- Users should not be able to change their campus (though they can change their position)
 - **Test that users with a campus can edit their position on their profile page, while users without a campus set (like new local users) don't have that option. Also just verify that there isn't any way in the "position" section of the edit profile page to change campus.**
- Users should only have one campus (right now it's a many-to-many relationship)
 - **Unfortunately there's no way to test this other than manually adding entries in the database.**
- When creating an account, match the Shibboleth eduPersonPrincipalName to their campus so it is set
 - **The only way to test this is to ask a UC person without a Next account to create an account, and verify that it sets their campus correctly.**
- Set the campus for any campus-less users based on their email address, and pray to the Lords of Kobol that they're not using a generic gmail address (or fix them manually)
 - **This requires manually paging through the list of people and making sure that all accounts have a campus log, except for non-local users. We can also check to see that their campus matches their email address, but it would be crazy to check all of them.**

**Comment by ctrance** [comment]
@krozett - I was able to test all cases you mentioned above except for "Users should only have one campus (right now it's a many-to-many relationship)
Unfortunately there's no way to test this other than manually adding entries in the database."

Closing this.
