### ISSUE TITLE
App still sends email even if user opted not to receive any UC Next email

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#434]
@joshuaselsky @shaun965 - User "ctrance@oit.ucla.edu" checked "don't want to receive emails from UC Next" box but app still sent event invitation. Is event invitation email excluded? If yes, what are the only emails we don't send if user opted to to receive email?

**Comment by joshuaselsky** [comment]
I think this feature should allow users to opt-out of all emails except for reset password which is always sent. It is not implemented that way currently. 

@shaun965 can you add the opt-out to the event and activity summary emails?

**Comment by ctrance** [comment]
fixed
