### ISSUE TITLE
Badge link on email should take the user to the login page

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#435]
I clicked the badge link on the email I received from the app when I was awarded a badge/award but it took me to the home page with error message "This user's profile is private".
![capture](https://cloud.githubusercontent.com/assets/1034174/14296038/22236766-fb2d-11e5-8395-ace899294aa5.PNG)

**Comment by joshuaselsky** [comment]
Is it possible that you clicked the link in the email while you were logged into the app as a different user?

**Comment by ctrance** [comment]
@joshuaselsky - I logged out (login button was showing) before clicking the email link, unless the app is not fully logging out users.

**Comment by ctrance** [comment]
@joshuaselsky - I logged out (login button was showing) before clicking the email link, unless the app is not fully logging out users.

**Comment by ctrance** [comment]
fixed
