### ISSUE TITLE
2016 badges

### ISSUE THREAD

**Issue by laurencullen** [universityofcalifornia/NeXt#445]
Sautter badges for 2016 and 2017
UCCSC 2016 presenter and attendee
Please let meknow if you need anything else with these

![sautter badges_hm2017](https://cloud.githubusercontent.com/assets/13141571/15691960/8e502a02-2740-11e6-9258-f9e7827800b5.png)
![sautter badges_silver2017](https://cloud.githubusercontent.com/assets/13141571/15691956/8e4b401e-2740-11e6-8a00-a906de88af23.png)
![sautter badges_golden2017](https://cloud.githubusercontent.com/assets/13141571/15691955/8e4a524e-2740-11e6-9fea-fd5018d3af46.png)
![sautter badges_hm2016](https://cloud.githubusercontent.com/assets/13141571/15691959/8e4f396c-2740-11e6-9d6e-5d9cf5d2975b.png)
![sautter badges_silver2016](https://cloud.githubusercontent.com/assets/13141571/15691957/8e4c84e2-2740-11e6-9d9e-e59857b869a6.png)
![sautter badges_golden2016](https://cloud.githubusercontent.com/assets/13141571/15691958/8e4dae8a-2740-11e6-9beb-eb3d40badbfc.png)
![new badges 2016_uccsc presenter 2016](https://cloud.githubusercontent.com/assets/13141571/15691962/8e6f349c-2740-11e6-935f-b62d5338c706.png)
![new badges 2016_uccsc attendee 2016](https://cloud.githubusercontent.com/assets/13141571/15691961/8e6db2fc-2740-11e6-9625-b58566a9fa3f.png)

**Comment by laurencullen** [comment]
@joshuaselsky not sure who to assign. Please let me know if you need anything else with these.

**Comment by joshuaselsky** [comment]
Someone with an admin account just needs to upload these to staging and production.

**Comment by ctmcintyre** [comment]
Beautiful1

> Lauren Cullen <mailto:notifications@github.com>
> May 31, 2016 at 3:01 PM
>
> Sautter badges for 2016 and 2017
> UCCSC 2016 presenter and attendee
> Please let meknow if you need anything else with these
>
> sautter badges_hm2017
> <https://cloud.githubusercontent.com/assets/13141571/15691960/8e502a02-2740-11e6-9258-f9e7827800b5.png>
> sautter badges_silver2017
> <https://cloud.githubusercontent.com/assets/13141571/15691956/8e4b401e-2740-11e6-8a00-a906de88af23.png>
> sautter badges_golden2017
> <https://cloud.githubusercontent.com/assets/13141571/15691955/8e4a524e-2740-11e6-9fea-fd5018d3af46.png>
> sautter badges_hm2016
> <https://cloud.githubusercontent.com/assets/13141571/15691959/8e4f396c-2740-11e6-9d6e-5d9cf5d2975b.png>
> sautter badges_silver2016
> <https://cloud.githubusercontent.com/assets/13141571/15691957/8e4c84e2-2740-11e6-9d9e-e59857b869a6.png>
> sautter badges_golden2016
> <https://cloud.githubusercontent.com/assets/13141571/15691958/8e4dae8a-2740-11e6-9beb-eb3d40badbfc.png>
> new badges 2016_uccsc presenter 2016
> <https://cloud.githubusercontent.com/assets/13141571/15691962/8e6f349c-2740-11e6-935f-b62d5338c706.png>
> new badges 2016_uccsc attendee 2016
> <https://cloud.githubusercontent.com/assets/13141571/15691961/8e6db2fc-2740-11e6-9625-b58566a9fa3f.png>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/445>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJQaksJXTO4agyrJ2Ts1SIcUrxpkRQCRks5qHK_JgaJpZM4IrAHc>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by laurencullen** [comment]
@ctmcintyre thanks! 
@rrocchio @joshuaselsky the badges are now up on staging and production. Please let me know if anything else is needed with these.
