### ISSUE TITLE
Check into Elastic Search - looks like the VOTES indexes might be broken

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#446]
Check into Elastic Search - looks like the VOTES indexes might be broken

**Comment by krozett** [comment]
The issue was a broken elasticsearch index. For reference, you can rebuild the indexes by doing:
`RAILS_ENV=production RELOAD_INDICES=1 bin/rails server` from the app directory. We'll have to do this regularly until the underlying problem is fixed.
