### ISSUE TITLE
[design] MANAGE the Design Contest for the UC NeXt site

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#51]
This task is about sourcing designs for the UC Next website.  The thought is to use the websiite - http://www.designcrowd.com to get this done.

This way we will get options and then we can vote on them...

**Comment by jurowski** [comment]
I've got a subscription to this site, there might be some good infograph ideas that we could implement to help w/ marketing and the homepage: http://piktochart.com/v2/

**Comment by rrocchio** [comment]
Ok - so I have saved a DRAFT of the Creative Brief - will discuss today, before I pull the trigger

![screen shot 2015-05-08 at 7 10 40 am](https://cloud.githubusercontent.com/assets/718820/7537960/7bc5d5f2-f551-11e4-824b-dd3a3910a663.png)

**Comment by rrocchio** [comment]
OK - so for 20 designs and it is $340 and if we want CSS code that adds $150 more... discuss usefulness of the CSS code
![screen shot 2015-05-08 at 7 12 52 am](https://cloud.githubusercontent.com/assets/718820/7537998/c5c9a1c4-f551-11e4-8b70-9c8bf0b7c731.png)

**Comment by jurowski** [comment]
CSS cost: worth it. CSS can be tedious to get just right when trying to replicate a look/feel, so I'd say go for it.

**Comment by rrocchio** [comment]
Meeting notes: ...- lightblub...-> blue print --> paper airplane ( teamwork - collaboration... - assembly) -> rocket ( new service )

**Comment by jurowski** [comment]
For the "lightbulb" stage... when someone is putting an idea together, it might be cool to show a campfire w/ people sitting around it, discussing... perhaps w/ stars/moon above (dreaming of what could be)

**Comment by rrocchio** [comment]
OK - here are the progressions of logos from one of the designers:
![logo 1](https://cloud.githubusercontent.com/assets/718820/7779715/a70c7c12-008b-11e5-871c-9ed43721c31b.JPG)
![Uploading logo 2.JPG…]()
![logo3](https://cloud.githubusercontent.com/assets/718820/7779714/a70c6e52-008b-11e5-84c5-b831eb953c33.JPG)

**Comment by jurowski** [comment]
If you do end up keeping both the lightbulb and the rocket and lose the
face, you could pipe that blue line on the bottom of the X over to the
bottom of the dots on the idea, as if the idea was being pushed through a
pipeline until it was ready to become rocketfuel.

Yes, it is Friday.

**Comment by rrocchio** [comment]
closing this out - now that Lauren is on board
