### ISSUE TITLE
[badges] Badging for Skill Competency - courses taken, certificates earned etc...

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#53]
This is for people to put these badges on their digital profiles - so that they can show off their accomplishments

**Comment by krozett** [comment]
See https://www.khanacademy.org/badges for some good ideas. @rrocchio and I talked about having different categories of badges based on rarity, prestige, how they are earned, etc. Would also be good to have a place for users to showcase certain badges (within a certain limit) and from there have a link to the page with all their badges.

**Comment by krozett** [comment]
Badges are now fully functional! I'm sure we'll have some tweaks to make but you can now create badges, assign people to be badge editors/givers, edit them, give them to users. If you're a user you can choose to showcase certain badges of yours on your profile. All non-showcased badges appear on a separate page which is linked from your profile.

**Comment by ctrance** [comment]
Badges/awards are working good now.
