### ISSUE TITLE
[people] Include the detailed profile fields into the People "profile" that you get under the Nav

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#54]
When users go in and edit their PROFILEs - many of the fields don't show up on the view that comes up off of the person's name link under the People Nav

**Comment by rrocchio** [comment]
Users will get upset - if they work on Adding all sorts of details - such as included in the 'EDIT PROFILE' screen and then no one can FIND those Details....

**Comment by pmeads** [comment]
I was only able to find 2 fields on the people profile detail (user/show.erb) view that were missing from the people edit  (user/_form.erb): the user.name_suffix and position.description. I added these fields in a branch off my fork and created a pull request for you to review.

**Comment by rrocchio** [comment]
@ebollens  - I don't see this pull request - do you see it?

**Comment by rrocchio** [comment]
@pmeads  - it seems like you finished this, once its done we can submit it to QA, I am adding a QA resource to the project soon!

**Comment by pmeads** [comment]
@rrocchio - there was a merge request that Eric merged 2 weeks ago. check #66

**Comment by pmeads** [comment]
pull request merged. closing
