### ISSUE TITLE
[ideas] on the IDEAS board NeXters should be able to change their VOTES 

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#55]
NeXters should be able to change their VOTES on ideas

**Comment by pmeads** [comment]
Based on whether you are a supporter or a participator, you should have buttons available on the top right of the idea detail page. Supporters of an idea might have "I wish to participate" and also "I no longer support this idea." Participators might have "I support this idea but can not participate" and maybe "I no longer support this idea" to bow out altogether.

**Comment by pmeads** [comment]
"withdraw support" or "withdraw participation"

**Comment by rrocchio** [comment]
I think that the appropriate action is to just "Withdraw Support", "Withdraw Participation"

**Comment by rrocchio** [comment]
Future - might break this into:  Support, Interest, Commitment

**Comment by pmeads** [comment]
this functionality is ready in pull request #99.

**Comment by ctrance** [comment]
fixed
