### ISSUE TITLE
[events] build event MVC

### ISSUE THREAD

**Issue by jurowski** [universityofcalifornia/NeXt#57]

**Comment by jurowski** [comment]
Assumptions
-----------------
events are public by default
events can be set to be visible to one or more NeXt groups
events are one-time (develop recurring events later)
    (for now, you can copy in details from a previous event you own)

Event Attributes
---------------------
name
description
start date
stop date
start time
stop time
location
promo_image
event url
map url
number_going
number_invited

event belongs_to
------------
owner (mandatory)
group (optional)

event has_many
------------
editors
presenters
attendees
invitees
groups
tags
uploaded_event_images_by_attendees
comments
reviews

**Comment by chabgood** [comment]
Maybe have a clone button next to events that you own?

**Comment by jurowski** [comment]
Chis is developing the events features in the branch "event_build_mvc_57"

**Comment by jurowski** [comment]
Relationships between event and group:
 1)  ownership: an event belongs to a group (optional)
  1) related, as in a "tag" or "potentially interested": 
      events:groups many-to-many

Some examples of "groups":
--financial applications developers
--java developers
--java spring security
--mysql developers
--database developers
--informatica
--identity management
--network security
