### ISSUE TITLE
[groups] Groups Discussion Ticket (overview)

### ISSUE THREAD

**Issue by jurowski** [universityofcalifornia/NeXt#58]
If we want people to feel involved, we should give them "groups" to join on NeXt.

A group has a particular shared interest. The shared interest could be to discuss a project or idea or set of projects/ideas. 

Similar to an email discussion group, but with many more features because it's linked to the other NeXt  attributes.

You subscribe/unsubscribe.
You can get notices when someone posts something on the group site.
Badges could be group-specific.

Settings:
-----------
Invites can be sent by "group admins only" or "by any group member".
A group can be "invite only" or "open to the public".
A group can be "unlimited qty" or "limited to a max number of people".

**Comment by rrocchio** [comment]
Groups or Teams ?

**Comment by rrocchio** [comment]
Dev Channels - for teams - IRC, Slack ...

**Comment by rrocchio** [comment]
We NEED to think about ways to encourage "Mentoring" and "Coaching" - GENIUS bar - having people "manning" the Genius bar concept....

**Comment by rrocchio** [comment]
Project teams are linked to projects, but projects could be linked to groups

**Comment by jurowski** [comment]
Some examples of "groups":
--financial applications developers
--java developers
--java spring security
--mysql developers
--database developers
--informatica
--identity management
--network security

**Comment by jurowski** [comment]
Estimating 24 hours for remaining groups functionality. Will break into 3 or more tasks.

**Comment by jurowski** [comment]
making this an "overview" discussion ticket; creating 3 others.

**Comment by krozett** [comment]
Closing this as it is now just a discussion ticket and doesn't have any requirements.
