### ISSUE TITLE
[activity feed] Display an activity feed: people creating events or ideas, joining a group or a project

### ISSUE THREAD

**Issue by jurowski** [universityofcalifornia/NeXt#68]

**Comment by jurowski** [comment]
Rose also brought up this site as a potential method of showing recent activity (in this case it is used to show the latest social media items): https://social.chapman.edu/

**Comment by rrocchio** [comment]
@jurowski  - not sure that this is in our current DEV plan, but I think it would be nice in the future

**Comment by chabgood** [comment]
since we are running node we can do websockets and have the feed show up as they are created or updated.
