### ISSUE TITLE
[Projects]  Enhance the Project details

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#69]
This task is about enhancing the project specific details:

1) Add the ability to upload documents  ( maybe the limit is 2-3)
2) Add a status field for what stage the project is in - proposal, analysis, prototype, development, rollout, production 
3) Add information for resources needed  by the project
4) Add voting similar to the Ideas voting

**Comment by krozett** [comment]
2) It turns out projects already have statuses, and these 3 are the available ones: forming, active, abandoned. Is this a different status field or the same one? If the same, do we need to keep any of the old statuses around?

**Comment by krozett** [comment]
3) Should these resources be free-formed or is it more like picking from a list like the competencies are?

**Comment by rrocchio** [comment]
@krozett  - 

Lets do a combo - so Resources needed should fall into 3 categories:

1) Infrastructure Resources (Physical or Virtual):  HW, VMs for DEV/TEST/PROD, Storage, Networking, Devices for testing... 
2) Expertise Resources Needed:  A DBA, an HPC expert, A UX Designer  ( The competency list may work here)
3) Business Partner Collaborators Needed:  HR Specialist, Marketing Specialist etc...

**Comment by rrocchio** [comment]
@krozett  - it turns out that Eric already had a "status field on the form", but it only had these values in tint:
"forming" "active" or "abandoned"....
I think that we take his original status field and change it to "phase"  and for use these values:  
(1) forming  -  recruiting resources
(2) Active -  fully resourced
(3) Successfully completed
(4) Deployed
(5) Abandoned

**Comment by krozett** [comment]
@rose - okay, I updated the text to say "phase" and added the new phases.
You will need to run `bundle exec rake db:seed RAILS_ENV=development` to update the list.

I only changed the user-facing text but kept the internal name as "project_status". It doesn't seem worthwhile to change it everywhere internally unless we are really being strict about this.

**Comment by krozett** [comment]
@rose - it seems like both "Expertise Resources Needed" and "Business Partner Collaborators Needed" fall under "competencies". What do you think about putting them both under the heading of "Staff Resources Needed", and it will pull from the list of competencies? And change "Infrastructure Resources Needed" to "Technical Resources Needed"?

**Comment by ctrance** [comment]
@krozett - "Infrastructure Resources Needed" shows a blank list. "Phase" is missing (3) Successfully completed and (4) Deployed. I see "documentation" field but does that allow uploading of 2-3 docs?

**Comment by krozett** [comment]
@ctrance The "Infrastructure Resources Needed" list is blank because we haven't added any resources yet. Maybe we should allow free-forming this. I'll add the missing phases as well.

The documentation field is actually meant for a URL. To upload the docs, you must visit a project detail page. In the upper right there is a button that says "Manage Documents". Click that and you can add/edit/delete documents for the project.

**Comment by ctrance** [comment]
@krozett - Thanks for the clarification! I have a question on uploading docs >> Is there any restrictions on uploading docs for projects? I went to "NeXt Ideation Platform" and didn't see a "Manage Documents" button. Is it only the founder who can upload docs? How about the participants/supporters?

**Comment by ctrance** [comment]
I still don't see the missing phases "Successfully completed" and "Deployed"

**Comment by ctrance** [comment]
fixed
