### ISSUE TITLE
Idea Comments

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#7]
This relates to #1 

  * Comments with support for replies (cyclical association)
    * Can be deleted by admins, but not by founder

**Comment by ebollens** [comment]
This is on the roadmap as something that we want to have for the initial release. Assigning it to milestone 1.0.

**Comment by pmeads** [comment]
Pull request merged in #71

**Comment by ctrance** [comment]
I'll test this once I got admin access

**Comment by ctrance** [comment]
Ideas have cyclical comments now. However, when I log in as a super admin I don't see a delete comment button. Are we still allowing super admins to delete comments?

**Comment by pmeads** [comment]
super admin deletes need to be implemented. Who else should delete a comment? Shouldn't the commenter be able to delete their own comment or edit their comment. Please see issue #229 and give your opinion. thx

**Comment by ctrance** [comment]
@pmeads - I think commenter should be able to delete/edit their own comments. Founder and Super Admin can only delete comments unless its their own comment.

**Comment by ctrance** [comment]
@joshuaselsky - Working good, we just have to correct the comment timestamp and the delete message as mentioned on #294. I'll close this once we made those corrections.

**Comment by ctrance** [comment]
fixed
