### ISSUE TITLE
[Projects]  - Change current "status field" to "Phase" field & add values

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#78]
@krozett - it turns out that Eric already had a "status field on the form", but it only had these values in tint:
"forming" "active" or "abandoned"....
I think that we take his original status field and change it to "phase" and for use these values:

(1) forming - recruiting resources
(2) Active - fully resourced
(3) Successfully completed
(4) Deployed
(5) Abandoned

**Comment by rrocchio** [comment]
@krozett  - has this code been merged?

**Comment by krozett** [comment]
@rrocchio - yes, but we'll need to re-seed the data in order to see the new values in production.

**Comment by ctrance** [comment]
fixed
