### ISSUE TITLE
Flashes are not working correctly

### ISSUE THREAD

**Issue by krozett** [universityofcalifornia/NeXt#80]
There's two issues here:
1. Flashes are losing their styling and any HTML that went into them. (For example, go to a project page you haven't voted on yet, vote for it, and look at the alerts. You'll see escaped HTML rather than actual tags.) Somewhere down the pipeline we are escaping HTML that should not be escaped.
2. Flashes don't display at all when a return_to is specified in params. I suspect this has to do with the `redirect_to` method in ApplicationController, because it doesn't seem to pass along the existing options when a return_to is given. (To replicate, vote on a project from the projects index page. It should show a flash like the above case but nothing is shown.)

**Comment by rrocchio** [comment]
Some issues with flashes on the messaging... - Sandon suggests chabgood@gmail.com

**Comment by krozett** [comment]
This problem doesn't exist on ucnext.org, waiting for an up-to-date deploy to see if this is still an issue. It may be something to do with my local server.

**Comment by krozett** [comment]
This is still an issue. It wasn't showing up on ucnext.org at the time because that code was not up to date.

**Comment by krozett** [comment]
This is now fixed.
