### ISSUE TITLE
[server] Need the smtp server address to use for sending email from the UC Next App

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#85]
Since we are going to be sending email from the UC Next App, we need the smtp server address that it will go out thru.

We will use UCSC's and Charles will create a Team account on that server, that the email will come ffrom

**Comment by ctmcintyre** [comment]
I'm not sure of the entire spec here, so please let me know if I'm 
missing something.

I can request a functional account on the UCSC Google email server.  
This will allow IMAP and SMTP so we can receive and send email.

Our domain is "@ucsc.edu", so I'm thinking "ucnext@ucsc.edu" would be 
best.  I've already reserved that name as a google group, so if everyone 
likes the name I can have it changed to a single address for the platform.

Other options include:

  * AWS SES (https://aws.amazon.com/ses/) - outbound email only
  * AWS Workmail (https://aws.amazon.com/workmail/) - fully functional,
    like gmail

C





> RoseRocchio <mailto:notifications@github.com>
> June 12, 2015 at 8:38 AM
>
> Assigned #85 
> <https://github.com/universityofcalifornia/NeXt/issues/85> to 
> @ctmcintyre <https://github.com/ctmcintyre>.
>
> ---
> Reply to this email directly or view it on GitHub 
> <https://github.com/universityofcalifornia/NeXt/issues/85#event-329680466>.
>
> RoseRocchio <mailto:notifications@github.com>
> June 12, 2015 at 8:38 AM
>
> Since we are going to be sending email from the UC Next App, we need 
> the smtp server address that it will go out thru.
>
> We will use UCSC's and Charles will create a Team account on that 
> server, that the email will come ffrom
>
> ---
> Reply to this email directly or view it on GitHub 
> <https://github.com/universityofcalifornia/NeXt/issues/85>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by ctmcintyre** [comment]
OK.  I've got a google email account for "ucnext@ucsc.edu" that supports IMAP and SMTP.  Who wants it?
